### ISSUE TITLE
Broken JS Console Output for Objects and Arrays

### ISSUE THREAD

**Issue by paulkanja** [deadlyjack/Acode#1005]
I've been using the app for the past few years and the JS console has been working fine. However, today when I tried inspecting a few objects (an empty array using `[]`, an empty Set using `new Set()`, etc) it shows `[object HTMLElement]` instead of the data:
![Screenshot_20240812-134436](https://github.com/user-attachments/assets/15bfa737-b09b-45df-a4ff-703ce69770bf)

Based on the output, I believe the console may be serializing the passed HTML elements instead of rendering them correctly

**Edit:**
After struggling with the problem for a bit, I put down the app for a few hours. I opened it again and now it just... works?

**Comment by sebastianjnuwu** [comment]
If it's working, don't touch it lol

**Comment by sebastianjnuwu** [comment]
For me, the opposite happens. I go to sleep, when it dawns, the problems continue.

**Comment by ByteJoseph** [comment]
is that issue solved ?
