### ISSUE TITLE
error

### ISSUE THREAD

**Issue by voSTSov** [deadlyjack/Acode#1007]
https://github.com/user-attachments/assets/a9f9629f-b14a-4eba-a5f8-6bfc707d42b7

Please tell me what the problem is, acodex works but still gives an error, maybe I didn’t download some additional package?
 Or is there another option to solve this problem?
HarmonyOS 3.1.0

**Comment by bajrangCoder** [comment]
Both are different things , you can't combine both.

> Btw this is plugin specific issues, open it there

**Comment by voSTSov** [comment]
I didn't understand you

**Comment by bajrangCoder** [comment]
I mean python plugin and AcodeX plugin is different, you can't combine them .
If you have installed module in AcodeX then run your code through Acode using command like `python`
