### ISSUE TITLE
Suggeste for Fix rename file bug

### ISSUE THREAD

**Issue by techcodeofficial** [deadlyjack/Acode#1009]
Hello acode devloper for fix rename file error in acode you can copy file content and create new file with new name and insert content to new file and delete old file

**Comment by sebastianjnuwu** [comment]
I think this fits with my problem.

**Comment by bajrangCoder** [comment]
> Hello acode devloper for fix rename file error in acode you can copy file content and create new file with new name and insert content to new file and delete old file

Nice idea 👍 

I will try to implement it but maybe we need to accept some performance decrement but that's acceptable

**Comment by techcodeofficial** [comment]
> > Hello acode devloper for fix rename file error in acode you can copy file content and create new file with new name and insert content to new file and delete old file
> 
> Nice idea 👍
> 
> I will try to implement it but maybe we need to accept some performance decrement but that's acceptable



> > Hello acode devloper for fix rename file error in acode you can copy file content and create new file with new name and insert content to new file and delete old file
> 
> Nice idea 👍
> 
> I will try to implement it but maybe we need to accept some performance decrement but that's acceptable

thanks 🙏

**Comment by techcodeofficial** [comment]
Yes it's nice Idea 💡 
Thank you 🙏

**Comment by bajrangCoder** [comment]
This solution is not ideal for directories, so currently this is added for files only

**Comment by 1Code-JS** [comment]
> This solution is not ideal for directories, so currently this is added for files only

If AcodeX plugin is present and it's server is running on Termux, use `mv` command

Or (this method could probably cause performance issues if the directory (especially `.git`) has a lot of (sometimes large) files):
1. Create a new directory with a new name
2. If there's are files, move(if can't, copy file and then delete old one) it's files from the old directory to the new one
3. Repeat steps 1 and 2 for subdirectories
4. Delete old directory once all files have been moved

**Comment by bajrangCoder** [comment]
First is planned but that's plugin related.
And second method isn't ideal for directories, there will many new issues/errors

**Comment by peasneovoyager2banana2** [comment]
https://github.com/user-attachments/assets/19dabbf8-6cb6-4cea-b92d-0d2e6eb4ed1d
