### ISSUE TITLE
Hi can you put auto-import in jsx files😁

### ISSUE THREAD

**Issue by M23jJohn** [deadlyjack/Acode#1027]

**Comment by bajrangCoder** [comment]
LSP things

**Comment by M23jJohn** [comment]
????

**Comment by bajrangCoder** [comment]
Actually these auto import etc features are provided by the LSP client and Acode don't have any built-in one.
So You will get these features from LSP client available as plugins on Acode Plugins Store

**Comment by M23jJohn** [comment]
Can you recommend these plugins

**Comment by bajrangCoder** [comment]
Search for these keywords in acode plugin store, you will get some :

- `Lsp`
- `Language Client`
