### ISSUE TITLE
Bug for instal plugin error

### ISSUE THREAD

**Issue by Maouuusamaaa** [deadlyjack/Acode#1051]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Uploading Screenshot_20241016-200315_Acode.jpg…]()

### Environment

![Screenshot_20241016-200315_Acode](https://github.com/user-attachments/assets/cb2f1cdd-6dfb-4e1f-91a9-682219b29fd0)

### If applicable, add mockups / screenshots regarding your vission

![Screenshot_20241016-200315_Acode](https://github.com/user-attachments/assets/919f8ab0-a02b-4a30-a830-7a9a12fba68b)

Help to fix

### If applicable, attach your Acode.log file to this issue.

<details><summary>Acode.log</summary><pre>

</pre></details>

**Comment by bajrangCoder** [comment]
Share information regarding your device and app version etc
