### ISSUE TITLE
Autocomplete html tags

### ISSUE THREAD

**Issue by ayeminnkyaww** [deadlyjack/Acode#1055]
### Check for existing issues

- [ ] Completed

### Describe the feature

I want request autocomplete html tags feacture. In Acode app, If I want to write tags,  I will need to write full opening tag. That's no good I think. Actually, when I need to wirte h1 tag, I want to write just the "h1" and then I will enter it will be autocomple. 

Thank you very much.

**Comment by bajrangCoder** [comment]
Duplicate https://github.com/deadlyjack/Acode/issues/578
