### ISSUE TITLE
Open git repo as directory with all files open in 'active files' panel

### ISSUE THREAD

**Issue by nathaneltitane** [deadlyjack/Acode#106]
I've been using spck editor for a while now and decided to go look at what the competition has to offer :)
Your editor is great and seems to offer plenty flexibility and stability.

Before actually labeling this as a bug:is there actually a way to open an authenticated git repo as a folder and have it reside in the left hand panel for quick project access?

If not, it would be a beautiful addition to your editor!

Thank you

**Comment by 80avin** [comment]
I second this. It would really help those who frequently explore Open Source code.

A minimal implementation could be:

1. Click `Open repo` in menu.
2. Enter url to repo.
  a. It should clone that repo to a temporary location, and open that directory as Workspace.

No other integration is necessary.
In future, it may provide a feed of recommended repositories based on user's interests, but that's not necessary.

**Comment by nathaneltitane** [comment]
🥲
