### ISSUE TITLE
Add Eruda-Vue plugging

### ISSUE THREAD

**Issue by CodeWithSushil** [deadlyjack/Acode#1065]
### Check for existing issues

- [X] Completed

### Describe the feature

`eruda-vue` is a new plugging of Eruda console. This plugging help to vue App. I request to you this plugging adding in eruda console when developer working in vue that time vue console enable by default disabled `vue Dev-tool`. No need to used 3rd parties plugging and install.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot_2024-11-02-08-22-35-189_com android chrome](https://github.com/user-attachments/assets/6f8dd469-a2eb-4d54-bef0-ba936cb5a8c8)

_No response_

**Comment by bajrangCoder** [comment]
Have you tried by loading this vue eruda plugin from the eruda console snippet tab. As eruda allow to load it's plugin from there

**Comment by CodeWithSushil** [comment]
Yes, plugging working on `chrome browser` only, not working in `Acode editor` show blank screen.
