### ISSUE TITLE
Reload on file change is annoying 

### ISSUE THREAD

**Issue by SuperninjaXII** [deadlyjack/Acode#1073]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

You see asks you to reload on every file change please remove as things like prettier , pretterd , go fmt or any lining and auto generation in the background becomes annoying 
![Screenshot_20241112-195403](https://github.com/user-attachments/assets/d1f46bec-29d8-47e6-838e-8aa02f56e8c3)

### Environment

Android version 13 update path 1septmber 1
OEM : Tecno
Acode version: 1.10.42
Web view:130
![Screenshot_20241112-203908](https://github.com/user-attachments/assets/b984fe3e-2d75-4a2a-9e65-e558716bec32)

### If applicable, add mockups / screenshots regarding your vission

![Screenshot_20241112-195403](https://github.com/user-attachments/assets/731436b1-e5b4-4191-b8f2-bbab1aefbe1f)

### If applicable, attach your Acode.log file to this issue.

<details><summary>Acode.log</summary><pre>

</pre></details>

**Comment by bajrangCoder** [comment]
There is a option that disable it in `Settings>App Settings`
