### ISSUE TITLE
Add support for SFTP symlinks

### ISSUE THREAD

**Issue by coder-newcomer** [deadlyjack/Acode#1076]
### Check for existing issues

- [x] Completed

### Describe the feature

Actually the main goal is support for Acode to be able to read directory or file symlinks.

![Screenshot_2024-11-14-11-01-20-753_com foxdebug acode](https://github.com/user-attachments/assets/bf3b2317-b7a1-4654-b7a0-60c1e1c69e19)
(`storage` folder accessed via SFTP which contains symlinked directory created by `termux-setup-storage` command)

I'm working NodeJS coding files inside Termux and `pnpm` usually work managing package by using symlinks. However Android Internal Storage is an emulated filesystem that doesn't support symlinks (or I suppose permission restrictions because I'm in non-root device) so I can't put my work on Internal Storage and instead keep it inside Termux.

![Screenshot_2024-11-14-10-55-32-220_com termux](https://github.com/user-attachments/assets/558b83e1-228b-4b93-888a-87af2f8821b1)
(Symlinks created using `termux-setup-storage` command)

Now accessing the Termux private storage is the challenge, my first workaround is by using Termux storage access provided from DocumentsUI. It works quite well, however it's comes to an issue that **it doesn't support rename operation**, this could be a hassle.

![Screenshot_2024-11-14-11-09-34-317_me zhanghai android files](https://github.com/user-attachments/assets/6bf7bf43-4af2-411a-abf4-ed9d594271e5)
(Try to rename file using [Material Files](/zhanghai/MaterialFiles) with Termux private directory access via DocumentsUI)

Another workaround is by using a file server, I had thought about setting up an FTP server in Termux but I haven't found the right tool for it. So I thought about using SSH instead. I set up an SSH server with [Termux-SSH](/dmdhrumilmistry/Termux-SSH) and it works fine, except for the symlinks support so I can access both Internal Storage and SD Card in the same place. This is just a small request actually, I hope it can be easily implemented...

---

I once use Acode plugin called [AcodeX](https://acode.app/plugin/bajrangcoder.acodex) which allow to execute Termux command inside the editor. However you need to install NodeJS package `acodex-server` to be installed and running as well. But I thought using SSH feature directly within AcodeX without any bridge (except the SSH server itself) would be a better approach.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot_2024-11-14-10-58-10-158_com cxinventor file explorer](https://github.com/user-attachments/assets/4b53c759-bae9-486e-a75c-4cb93dca9983)
(Cx File Explorer able to list symlinks)

**Comment by bajrangCoder** [comment]
> I once use Acode plugin called AcodeX which allow to execute Termux command inside the editor. However you need to install NodeJS package acodex-server to be installed and running as well. But I thought using SSH feature directly within AcodeX without any bridge (except the SSH server itself) would be a better approach.

Let the ssh shell related stuff to be handled by AcodeX itself, As we are not going to reimplement terminal stuffs in Acode .

**Comment by bajrangCoder** [comment]
Hmm, currently Acode doesn't indicate symlinks, it just open that folder if it able to. Btw why using SFTP , as using "Add Path"(a.k.a External storage thing) you can access sd card , termux private directory etc and that will be also able to access symlinks

**Comment by coder-newcomer** [comment]
Actually as I mentioned before, it's doesn't support rename over the Termux private directory. I don't know if it's actually Termux issue, but it's annoying if I must rename by go over Termux and back again.

However since this is general SFTP related stuff, it can be useful for another case beside mine.

**Comment by bajrangCoder** [comment]
> Actually as I mentioned before, it's doesn't support rename over the Termux private directory. I don't know if it's actually Termux issue, but it's annoying if I must rename by go over Termux and back again.

That's due to termux security restrictions. But this kind of fix this : https://github.com/deadlyjack/Acode/issues/1009

> However since this is general SFTP related stuff, it can be useful for another case beside mine.

Yes, this should be fixed.
