### ISSUE TITLE
The connection to the server is unsuccessful

### ISSUE THREAD

**Issue by appliyard** [deadlyjack/Acode#113]
When I switch another app, and switch to Acode again sometime application error occured and forced to reopen Acode. 
![Screenshot_20201024-181645](https://user-images.githubusercontent.com/72886082/97079587-4d890a00-1630-11eb-849c-a9568253c4ab.png)

**Comment by deadlyjack** [comment]
Please provide more details about your device.

**Comment by appliyard** [comment]
[Info from Device Info HW](https://1drv.ms/u/s!AjQOzQQWZek0ksZ4a95gj-2wvRMCRQ)
