### ISSUE TITLE
Lags when scrolling

### ISSUE THREAD

**Issue by blackeangel** [deadlyjack/Acode#122]
Lags when scrolling, when many code. Details on the video. (google drive) https://drive.google.com/file/d/1UtNYtlA1JPBF4DieIEmEWP6P0nCR5HJy/view?usp=drivesdk

**Comment by deadlyjack** [comment]
Please provide information about:

- App version
- Device
- Android version

**Comment by blackeangel** [comment]
> Please provide information about:
> 
> * App version
> * Device
> * Android version

1. App last : 1.1.14.136
2. Redmi Note 9s
3. Android 10, Miui 12

**Comment by deadlyjack** [comment]
Turn on 'show touches' in developer options, it will be visible in screen recording what are you doing and it will help me to guess the issue.

**Comment by blackeangel** [comment]
> Turn on 'show touches' in developer options, it will be visible in screen recording what are you doing and it will help me to guess the issue.

Video (google disk) https://drive.google.com/file/d/1gh1BJe1MRa5tAwoiGlIkRD4Oe5YDkP59/view?usp=drivesdk

**Comment by tienomeis** [comment]
I also experience lacks whenever the lines are long. When there are really long lines, e.g. long scentences in html without line breaks, then the editor becomes nearly when viewing this lines.

**Comment by daniuwo** [comment]
Compared with the sidebar, the editor scrolling is delayed.
[https://drive.google.com/file/d/1XZSWqzPbpe3B0-e-zWrd1nY8SXaa6Nzf/view?usp=sharing](https://drive.google.com/file/d/1XZSWqzPbpe3B0-e-zWrd1nY8SXaa6Nzf/view?usp=sharing)

**Comment by deadlyjack** [comment]
Thanks for providing me with details. I'll look into it and fix the issue.

**Comment by unoukujou** [comment]
Same issue for me. Scrollbar can scroll very smoothly. But scrolling in the editor is very sticky and hard to navigate.
