### ISSUE TITLE
ANSI file with german special-characters is opened as UTF8

### ISSUE THREAD

**Issue by Micha-he** [deadlyjack/Acode#129]
Transferred errors from my Google review:

A local ANSI file with german special-characters (°äöüÄÖÜß) is opened as UTF8.
If I switch manually to ANSI-Windows1252 encoding, additional characters are inserted (on each encoding-change).

**Comment by Micha-he** [comment]
Still exists in V1.5.4.

**Comment by deadlyjack** [comment]
Please move this issue to https://github.com/ajaxorg/ace

**Comment by Micha-he** [comment]
Done: https://github.com/ajaxorg/ace/issues/5230#issue-1782001196
