### ISSUE TITLE
[Feature Request] Samba / SMB Server Access

### ISSUE THREAD

**Issue by richaardvark** [deadlyjack/Acode#139]
Hello, I have been using Acode for the past couple of weeks and have been very happy! One feature I would really love added would be the ability to connect to Windows/Samba server share locations and directories. The FTP client connectivity feature is great, but it would be so helpful if SMB connections were also supported. Perhaps the existing "FTP" menu option title could be changed to "Network" or "Remote Location..." and then just add another radio button next to the existing two FTP connection options, for a new samba connection.

Perhaps implementing this feature is not as simple as it might seems to be and isn't likely to ever be implemented, but I just wanted to at least ask.

Thank you!

**Comment by deadlyjack** [comment]
Thanks for the suggestion, I'll try to implement it.

**Comment by gmiwoj** [comment]
totally agree. mixplorer has samba  and i litrrally use it a hundred times a day for different things, its riddiculusly useful and convenient feature to have

**Comment by TarcisioMenezes** [comment]
Any news about the SMB implementation?
I just downloaded the app but all the files I need to edit are shared through SMB. 
Thank you.

**Comment by deadlyjack** [comment]
Working on it. Soon it will be available.

**Comment by TarcisioMenezes** [comment]
Awesome! Any expected date ? Looking forward for that.

**Comment by deadlyjack** [comment]
I've found a library for [SMB](jcifs.smb.NtlmPasswordAuthentication) in java. I just have to create Cordova plugin for it which would be a great time consuming task. And also I'm working on other commercial project i.e. I'm not able to give much time Acode. But I'll try to finish it as soon as possible.

**Comment by SomenteRafael** [comment]
Awesome workaroud (maybe not even that, if I can say): use CIFS! Wow, magically got smb supporting *_* : https://github.com/wa2c/cifs-documents-provider

It integrantes with android DocumentsProviderUI (i.e. adds doc. Prov. source) - at least it's what I understood... Anemo does the same...
By the way... it supports (S)FTP too...

:B
