### ISSUE TITLE
Add the ability to insert a timestamp

### ISSUE THREAD

**Issue by blackeangel** [deadlyjack/Acode#141]
Add the ability to insert a timestamp, in various ways, as a comment. In the menu under the pencil, where is the insert.
For example:
![Screenshot_2020-12-01-10-53-10-284_com rhmsoft edit pro](https://user-images.githubusercontent.com/20953770/100712348-ada76480-33c3-11eb-9e16-9e26038688ed.jpg)

**Comment by deadlyjack** [comment]
Thanks for suggestion, I'll add it.
