### ISSUE TITLE
FTP Unknown Command

### ISSUE THREAD

**Issue by hibatica** [deadlyjack/Acode#147]
I used `tcpsvd -vE 0.0.0.0 8021 busybox ftpd -w ./projects`
A code logged on fine but apon saving a file it returned 
```
tcpsvd: start 31313 127.0.0.1:8021-127.0.0.1:33578
tcpsvd: status 1/30
tcpsvd: end 31313 exit 0
tcpsvd: status 0/30
```

And Acode gave this error

![Screenshot_20201215-185601_Acode](https://user-images.githubusercontent.com/47132148/102290811-65319000-3f07-11eb-9a33-e844d1c8d8c3.jpg)

When going to ftp://localhost:8021 it shows all the files in the projects folder so I assume the termux side is working.

**Comment by flleeppyy** [comment]
I assume you're using Termux to host FTP in your projects folder so you can access them through Acode's FTP function, correct?

**Comment by hibatica** [comment]
> I assume you're using Termux to host FTP in your projects folder so you can access them through Acode's FTP function, correct?

Correct!

**Comment by flleeppyy** [comment]
You can save yourself so much hassle if you run `termux-setup-storage`, then go to Acode > Top right dropdown menu > Open Folder > Add button at the top > Add path > Name it `termux`, click `select path`, then you'll drag out the menu from the left and click Termux

**Comment by flleeppyy** [comment]
Should note that running `termux-setup-storage` will create a new folder called `storage` with a few other subfolders, of which containg `shared` which is connected to the root of your android filesystem (Where your stuff is, like Downloads, DCIM, Pictures, Android, etc)
