### ISSUE TITLE
Issue while creating a Firebase App

### ISSUE THREAD

**Issue by asatyammis** [deadlyjack/Acode#152]
# Issue while creating and initialising a Firebase app
When I create a Firebase App, and initialise the Firebase config, an error occurs in the console stating 'Uncaught ReferenceError: firebase is not defined' where firebase is a variable created by the JavaScript file imported from the Firebase website.
The code work fine on every other code editor on Android as well as PC.
<br>
## Screenshots of the code and console error respectively.
<br>
![Screenshot_20210120-154351_Acode](https://user-images.githubusercontent.com/70370034/105160261-0aa6d780-5b36-11eb-8524-6e490c47a842.jpg)
![Screenshot_20210120-154403_Chrome](https://user-images.githubusercontent.com/70370034/105160290-15616c80-5b36-11eb-9c58-00c82d6ccfaa.jpg)

**Comment by flleeppyy** [comment]
Incase screenshots arent showing for some folks
![Screenshot_20210120-154351_Acode](https://user-images.githubusercontent.com/70370034/105160261-0aa6d780-5b36-11eb-8524-6e490c47a842.jpg)

![Screenshot_20210120-154403_Chrome](https://user-images.githubusercontent.com/70370034/105160290-15616c80-5b36-11eb-9c58-00c82d6ccfaa.jpg)

**Comment by flleeppyy** [comment]
I haven't messed with firebase before, but have you tried going directly to the firebase library and seeing if it loads? (https://gstatic.com/firebasejs/8.2.3/firebase-app.js)

**Comment by asatyammis** [comment]
> I haven't messed with firebase before, but have you tried going directly to the firebase library and seeing if it loads? (https://gstatic.com/firebasejs/8.2.3/firebase-app.js)

Yeah! That was the first thing which I did when I got the error, but the page loads correctly.
