### ISSUE TITLE
PHP syntax color error when using heredoc

### ISSUE THREAD

**Issue by mahendra232** [deadlyjack/Acode#165]
When i'm using heredoc, the code below heredoc line became green

![Screenshot_20210210_194046_com.foxdebug.acodefree.jpg](https://user-images.githubusercontent.com/19867396/107511400-05d6c000-6bd8-11eb-91e1-8c507c80fd13.jpg)

**Comment by deadlyjack** [comment]
Thanks for reporting this issue, I'll take a look into it and fix it as soon as possible.
