### ISSUE TITLE
Tab size saved but not re-applied

### ISSUE THREAD

**Issue by gt-nik** [deadlyjack/Acode#175]
Hi all,

[for Acode version 1.2.143]
1. I set the "Tab size" editor setting to 8 and my tab-delimited text file appears in columns as expected.
2. When i re-open the same file, the text not appears in columns (columns are not justified as step 1) although the "Tab size" editor setting is still 8.
3. To see again the text in columns as step 1, every time i open the file i have to change the "Tab size" to any other value and again change it to 8.

Best regards
Thanks

**Comment by deadlyjack** [comment]
Thanks for reporting the issue. I'll check this and fix it as soon as possible.

**Comment by gt-nik** [comment]
version 1.2.149 did NOT fix the problem.

**Comment by gt-nik** [comment]
> deadlyjack moved this from To-do to Done

sorry, version 1.4.163 and the problem still exist.

**Comment by gt-nik** [comment]
version 1.4.164 did NOT fix the problem.
