### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [deadlyjack/Acode#183]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the
screenshots in fastlane. This is just one way that you can also add screenshots to the app view
if you can. If you added screenshots (then F-Droid is happy) and if you can't add any -> then
you can close the issue because it was only an info. Thank you that your app is available in
fdroid. Very much for your attention.

**Comment by deadlyjack** [comment]
Sure I'll do it as soon as possible.

**Comment by shuvashish76** [comment]
@IzzySoft request to provide fastlane metadata from PlayStore & merge with F-Droid.

**Comment by IzzySoft** [comment]
Huh? Why me? I don't have them, the app is not in my repo. But I can provide my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance.

**Comment by shuvashish76** [comment]
Sorry to ping you here, the PlayStore version images are too small & when I tried to download them they're in `.webp` format. So need to convert them to `.png` format.
Plus I guess after the fastlane merge it won't automatically picked by F-Droid 1st time. Need F-Droid maintainers intervention or create an issue on F-Droid data. So I thought better to request you in this case.

**Comment by IzzySoft** [comment]
I understand your reasoning, but I cannot do everything everywhere, sorry. And what makes you think that if I retrieve the images from there that they would be larger? Further, merging images is only possible here in the app's repo. F-Droid no longer accepts graphics into its metadata repository. Which is why I posted the link to my cheat-sheet above: it's up to @deadlyjack to do that – who wrote "as soon as possible" 2 years ago :speak_no_evil:

**Comment by shuvashish76** [comment]
> And what makes you think that if I retrieve the images from there that they would be larger?

I thought you use some script or something, automation for retrieve/resize/compress, again sorry.
PR images converted using [Image resizer](https://www.f-droid.org/packages/ru.tech.imageresizershrinker/) & reduced file size using  [FFShare](https://www.f-droid.org/packages/com.caydey.ffshare/).

**Comment by IzzySoft** [comment]
Ah. Well, kinda. But that would result in all the stuff being integrated with my repo, so I had to cleanup again. And I still had to open the PR etc pp. As pointed out, I'm already quite busy at too many other corners, spending about 4h every day on "public goods". Need to budget my time, as unfortunately there's no such thing as "unconditional basic income" yet which would allow me dropping some time from my "day job" :wink:

**Comment by IzzySoft** [comment]
That looks fine! Now don't forget to have the YAML updated at F-Droid. What time do you plan the next release? If the YAML update at F-Droid happens right before the build starts, that'd be ideal (the build is when metadata would be picked up).
