### ISSUE TITLE
Sometimes marked boundary points are below the screen

### ISSUE THREAD

**Issue by jidanni** [deadlyjack/Acode#205]
Sometimes the marked area boundary points are below the bottom of the screen.
![Screenshot_20210502-125054.jpg](https://user-images.githubusercontent.com/1230959/116802431-30844500-ab45-11eb-93af-506ab6793ab7.jpg)

We must realize the problem and move the screen up by hand:
![Screenshot_20210502-125105.jpg](https://user-images.githubusercontent.com/1230959/116802439-46920580-ab45-11eb-895c-630a07e8b957.jpg)

**Comment by RoHBee** [comment]
This problem is in every test editors. And its not a problem.
