### ISSUE TITLE
Can't save file in f-droid version missing Select document (documents provider) option

### ISSUE THREAD

**Issue by Neuro-NX** [deadlyjack/Acode#209]
I am unable to save a file in Acode from F-droid. `Internal storage` shows no files, and the `Select document `(documents provider) option to save from another app is missing. This issue does not occur in the version in Google Play.

**Comment by fabriziodsp-ransom** [comment]
You should use the Google Play version to avoid these kinds of errors due
to Google Play's release being stable.

**Comment by tukusejssirs** [comment]
This issue is duplicate of #188.

I too installed the app from F-Droid, but I don’t think that Google should be the solution.
