### ISSUE TITLE
[Feature Request] Node js / Terminal support

### ISSUE THREAD

**Issue by hyxud** [deadlyjack/Acode#227]
Is it possible to add a Node Terminal Like [Termux](https://termux.com/) that Allows you to Host Node Server and Run Node apps?

**Comment by sub-zero1** [comment]
I think this app needs to have an inbuilt terminal to run node

**Comment by sxnsei-dev** [comment]
> I think this app needs to have an inbuilt terminal to run node

yes it does need an integrated terminal to run Nodejs and Such. you can still Work with [Termux](https://termux.com) or any other terminal emulator to Run node but it would be nice to have a built-in terminal

**Comment by sub-zero1** [comment]
Yh

**Comment by McJoe21** [comment]
Yay good for running bots locally on your own phone so you don't need computer 😜
