### ISSUE TITLE
<a href="../index.html">home</a>    URLs can't up an direction level

### ISSUE THREAD

**Issue by phantombill** [deadlyjack/Acode#228]

**Comment by azclub-ltd** [comment]
No description? Not enough information

**Comment by ArcadeDuo** [comment]
Yes, I also tried to use direction levels on URLs and it doesn't work. I can provide screenshots of it if you want.

**Comment by McJoe21** [comment]
And it doesn't even allow for `/` at end alone with out the `index.html`
