### ISSUE TITLE
Keyboard related bug

### ISSUE THREAD

**Issue by random-guy1285** [deadlyjack/Acode#233]
When pressing the  "123"  button on SwiftKey keyboard to type other symbols, the keyboard closes. This happens only in acode.

**Comment by random-guy1285** [comment]
I have basically no knowledge of the github ui. Please excuse mistakes

**Comment by azclub-ltd** [comment]
Hacker keyboard and Gboard is best for coding, please switch to them if you can.

**Comment by random-guy1285** [comment]
I have tried gboard and it was not functional.
