### ISSUE TITLE
ENHANCEMENT: Syntax support for nullish coalescing and optional chaining

### ISSUE THREAD

**Issue by MagesticChicen** [deadlyjack/Acode#237]
Currently, the editor does not support syntax highlighting for  `nullish coalescing` OR `optional chaining`

> Instead, this is interpreted as an syntax error since the editor is expecting ```() ? :``` but is getting ```?. ```

**See screenshots below**
![Screenshot_20210819-114033_Acode](https://user-images.githubusercontent.com/60527324/130055485-d6bad422-1fe8-43a0-a304-01a31f9ceb91.png)
![Screenshot_20210819-114253_Acode](https://user-images.githubusercontent.com/60527324/130055601-93af851b-a9b3-4b00-98dd-4d26c51ff043.png)
Support for these functions would be appreciated
More informations into the functions:
[Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), 
[Nullish Coalescing ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

**Comment by deadlyjack** [comment]
Move this issue to https://github.com/ajaxorg/ace
