### ISSUE TITLE
ENHANCEMENT: Ability to disable array beutifying

### ISSUE THREAD

**Issue by MagesticChicen** [deadlyjack/Acode#238]
The current system for beautifying code awkwardly splits each array instance into its own line, while this is ideal for Arrays containing lengthy instances. See the example below from one of my files which demonstrates the flaws of this not being a toggleable option: 
![Screenshot_20210820-182033_Acode](https://user-images.githubusercontent.com/60527324/130270828-7d60460e-0e19-4ee5-b851-abcf387de9cb.png)
![Screenshot_20210820-182043_Acode](https://user-images.githubusercontent.com/60527324/130270834-36f45388-74e0-4b15-815b-cd837f7f0835.png)
Look at these abominations! 
I'm sure some others have had to experience these eye sores, so a option to disable it would be greatly appreciated

**Comment by McJoe21** [comment]
Cool idea
