### ISSUE TITLE
Showing blank when selecting a folder

### ISSUE THREAD

**Issue by Johnsiras** [deadlyjack/Acode#239]
I can't pick a folder to save a file.. cause it's glitching.. idk how to fix so I just need help a bit. Here's a pic.
![Screenshot_2021-08-25-20-31-10-73](https://user-images.githubusercontent.com/78542955/130790966-8365fa97-b00c-4357-9870-d42718520ee2.png)

**Comment by deadlyjack** [comment]
Please provide more information how to regenerate this.

**Comment by frytkisasmaczne** [comment]
i have this too, tried google play, fdroid and github builds.
it's on all of them.
i just installed the app and tried to open files with it, in-app folder selection screen blinks two items - internal storage and sd card for a while, and then it's like some background-colored overlay appears on top of that.
i changed the themes around a bit, didn't fix it.
the folder selector still kind of receives touch, i clicked where internal storage blinked and got into it, the folders there normally appeared, but without the link to root folder

**Comment by deadlyjack** [comment]
App version? Device details?

**Comment by frytkisasmaczne** [comment]
version 1.2.143
lg v30 on android 8, 1440x2880, rounded corners

**Comment by deadlyjack** [comment]
Please update the app and check if issue still exists and repone this issue.

**Comment by frytkisasmaczne** [comment]
It persists in the fdroid build as of about 6 hours ago.
This problem doesn't appear on xperia xz1 compact.
I suspect it's about the rounded corners most likely, possibly about the 2:1 resolution ratio, that's less likely.

Dnia 29 września 2021 18:53:53 CEST, Ajit Kumar ***@***.***> napisał(a):
