### ISSUE TITLE
Enter filename when I want to the file

### ISSUE THREAD

**Issue by tukusejssirs** [deadlyjack/Acode#250]
It lokks like a strange design decision. Every time I create a new file, Acode asks me for a filename. I know of no other text editor (Linux/Win/Android) that does this.

I’d like to choose filename at save time.To autosave the session, you could save it with some generated filename under `/sdcard/Android/data/…`.

**Comment by deadlyjack** [comment]
Thanks for suggestion and I appreciate it. I'll think about improving it.
