### ISSUE TITLE
Version 1.4.159 does not start

### ISSUE THREAD

**Issue by papoloop** [deadlyjack/Acode#252]
On Oppo Reno 2Z with ColorOS 11 the app does not start and only shows the logo.
Back to 1.3.155.
Thanks

**Comment by tukusejssirs** [comment]
I too see the startup animation booting indefinitely. I am on Android 11 rooted on Samsung Note 10+.

**Comment by anedroid** [comment]
I can confirm this bug on my Moto g7 Power, LineageOS, Android 11

**Comment by xuruicheng96** [comment]
Same on OnePlus 7 android 11

**Comment by azclub-ltd** [comment]
Bug is fixed on the latest version

**Comment by anedroid** [comment]
Not available on F-Droid yet. I will use 1.3.55 until Acode will be published in repository, I know it takes some time.

**Comment by Helaxious** [comment]
I am too using 1.4.159 on F-Droid and it doesn't boot, I am using Android 11 too, I have a Moto G 9 Play, but downgrading the app solves the issue.

**Comment by deadlyjack** [comment]
This is issue has been fixed in latest version. i.e. 1.4.163

**Comment by OliverLew** [comment]
@deadlyjack is there going to be a GitHub release, so that f-droid can update? (I don't know, maybe or a git tag)

**Comment by tukusejssirs** [comment]
> @deadlyjack is there going to be a GitHub release, so that f-droid can update? (I don't know, maybe or a git tag)

@deadlyjack, I think it should be automated: whenever there is new release (e.g. a new tag), a new GitHubvrelease should be created (via a CI tool).
