### ISSUE TITLE
On `v1.3.155`, when opening key bindings file, it is empty and cannot be saved

### ISSUE THREAD

**Issue by tukusejssirs** [deadlyjack/Acode#253]
I opened the `.key-bindings.json` file from the settings in `v1.3.155`, but only empty file is open (it wasn’t empty in prior versions). When I wanted to restore the contents from the `v1.2.143` version, but it failed to save.

I use Android 11 rooted on Samsung Note 10+.

**Comment by deadlyjack** [comment]
Thank you for reporting this issue. It will be fixed soon.

**Comment by deadlyjack** [comment]
This issue has been fixed.
