### ISSUE TITLE
Last update don't start

### ISSUE THREAD

**Issue by gelderode** [deadlyjack/Acode#254]
Splashscreen stats on.
Android One / version 11

**Comment by xuruicheng96** [comment]
Yep I can confirm, tried on two of my Android phones, it stuck on the startup animation.

**Comment by gelderode** [comment]
Thanks for all the work.
I realy like the editor, use it a lot.
I reloaded the previous version and that one works perfect. So I can  do
editing till fixed update .

Greetings.



Op di 14 sep. 2021 01:31 schreef Ray Xu ***@***.***>:

**Comment by azclub-ltd** [comment]
which acode version are you using ?

**Comment by memosk8** [comment]
1.4.159 installed from f-droid on a motoG6 play with android 9 in my case, and just didn't start, so I had to go back to 1.3.155

**Comment by azclub-ltd** [comment]
Use the latest version, 1.4.164. Though this version have rename problem. But hope that it will fixed soon.

**Comment by mvolfik** [comment]
159 isn't on F-Droid yet, is there a reason for that? New to this libre worlds, so idk how F-Droid publishing works
