### ISSUE TITLE
File browser only showing image files

### ISSUE THREAD

**Issue by drandrewthomas** [deadlyjack/Acode#259]
Hi,

I'm having problems opening html and javascript files in the otherwise excellent paid version of acode. Basically, the file browser is only showing the image files, so I can't select and load the code files. Unfortunately, that means I can't use acode now as the file browser seems the only way to open files. I've attached screenshots of the folder list in acode and one of the folders in CX File Explorer so you can see that files other than images are there.

I have this problem on an S6 Lite tablet and S20 Ultra smartphone. I just had acode update and still have the problem. In case it helps, both devices are Android 11 and I don't remember having any issues when running Android 10 (although that could be a red herring). However, possibly the new Android 11 file access permissions for files outside the app's folder are the problem.

I hope you can solve this so I can get using acode again.

Thanks,

Andrew.

![CXFileList_1](https://user-images.githubusercontent.com/5571782/133844240-f8414b58-e34b-46af-b49e-960dd483a6b1.jpg)
![AcodeFileList_1](https://user-images.githubusercontent.com/5571782/133844243-9c76d8d2-575d-4eff-aaa8-e09656f45e5f.jpg)

**Comment by azclub-ltd** [comment]
Make sure you are using the latest version of acode b'cz it is working fine on my device. Try clearing data and restart. If the problem persist the comment here with with device model android version and acode version. And also try changing theme.

**Comment by drandrewthomas** [comment]
Hi,

Thanks for your reply. Yes, as previously mentioned I was using the latest version. Your idea of clearing the data and cache, albeit rather drastic, worked. However it seems only because it made acode ask for file permissions again, which resulted in an error that acode couldn't run, but then it worked after I'd closed and restarted the app again.

So when I then went into the file browser I could not open the internal storage until I clicked the link and gave acode 'all file' permissions: and that link only appeared after clearing the cache/data (see screenshots).

So the issue seems to be that acode ends up with some sort of legacy permissions when installed on a device that upgrades to Android 11, and doesn't show the link asking for all file permissions until data/cache are cleared. I assume Android 11 then only allows it access to safe files like images and so the file browser can't show 'unsafe' files like html, css and js.

I hope that helps with this issue as it could be very confusing if others have to clear their data and cache (and so all the coding, etc, preferences) when their device moves to v11. Or, maybe even they will give up on acode because they can't open code files and don't know they have to clear the data and lose all their settings and preferences.

Thanks,

Andrew.

![acode1](https://user-images.githubusercontent.com/5571782/133910079-e710c359-480e-464e-a796-ed6c023ec402.jpg)

![acode2](https://user-images.githubusercontent.com/5571782/133910077-8facf3a3-d1ec-4d8a-9c65-6f55665b1d97.jpg)

**Comment by azclub-ltd** [comment]
You said right. It may cause bad user experience. Android is increasing its security day by day. People who upgraded their phone to android 11 facing a lot of problem not only in this app but also in other apps. If you think, your problem is solved you may close this issues.
