### ISSUE TITLE
Acode stucks on "connecting..." screen

### ISSUE THREAD

**Issue by SofiaRedmond** [deadlyjack/Acode#260]
I'm trying to log in with my SFTP server credentials to connect, but the app stucks on the "connecting..." screen. 

My credentials are not incorrect because I have a file management app through SFTP and it works properly. 

![Screenshot_20210918-162204](https://user-images.githubusercontent.com/86848962/133910780-c6105c04-f1f8-4386-a6e5-331237d0e602.png)

(I think this can help)
Every time I connect to my SFTP server for the first time in an app, this window appears.

![Screenshot_20210918-181347](https://user-images.githubusercontent.com/86848962/133910844-13589df5-cce8-40cc-8975-97b891e2f3d9.png)

I think this is what prevents Acode from connecting properly to the SFTP server.

**Comment by azclub-ltd** [comment]
Click always. You are connecting to sftp using rsa file. To connect with rsa file first time you need to accept rsa fingerprint as a trusted fingerprint. Without accepting it you can't really connect. Then comment if it is working or not

**Comment by SofiaRedmond** [comment]
> Click always. You are connecting to sftp using rsa file. To connect with rsa file first time you need to accept rsa fingerprint as a trusted fingerprint. Without accepting it you can't really connect. Then comment if it is working or not

I meant that maybe that's why Acode can't connect to my SFTP server.

**Comment by azclub-ltd** [comment]
Oh I see.. Acode is not prompting for rsa fingerprint. Yeah, you said right. That could be a problem. Dev can fix it by prompting user for accepting and save the fingerprint or dev also can fix it by adding another input file where user can select their saved fingerprint.

**Comment by deadlyjack** [comment]
Thanks for reporting, I'll try to fix it soon.
