### ISSUE TITLE
[Feature Request] Add a button to copy the full file path

### ISSUE THREAD

**Issue by userbrdev** [deadlyjack/Acode#267]
Add a button to copy the full file path
on this    ###screen.
![Screenshot_20210926073347](https://user-images.githubusercontent.com/83094160/134808078-e2ce9297-3ab4-41d4-9c33-cd3ec718f8ed.jpg)

**Comment by deadlyjack** [comment]
This is an unnecessary feature request. I'm closing it.

**Comment by aisbergde** [comment]
If this is an "unnecessary feature request":
What is the recommended way?
For example using a desktop editor I can "open the file in a file explorer". Then I can do, what is possible to do in a file explorer.

Or is the idea to only use, what is possible to when sharing the file?

Often I just need the filename, to create a link. Currently I have no idea how to get the filename of any file in the folder.

**Comment by deadlyjack** [comment]
Thanks for the suggestion. I can add a feature to open the file in another app. It might be helpful.
