### ISSUE TITLE
Add margin on right

### ISSUE THREAD

**Issue by holiq** [deadlyjack/Acode#268]
Please add a margin on the right side of the editor, as seen in line 17 it's too tight so it's hard to click

![Screenshot_20210928-231849_Acode](https://user-images.githubusercontent.com/30729921/135126318-8aff91ea-79ff-417a-b5b0-583c8b19c9cf.png)

**Comment by deadlyjack** [comment]
Using the arrow button would be helpful. Closing this issue.
