### ISSUE TITLE
SFTP / FTP Bug

### ISSUE THREAD

**Issue by ke8lne** [deadlyjack/Acode#274]
This problem suddenly occurs when saving a file through SFTP/FTP then closes the connection.

When the connection is closed, many problems will occur like unable to view/load the remote directory and saving the file, stuck in the 'saving...' message until you restart the app.

Switching task/other app will close the connection and that's disturbing.

I have to use this app for editing my files from my vps. Thanks for fixing this bug in advance.

**Comment by deadlyjack** [comment]
Please provide the app version, device information, I'll try to fix this issue as soon as possible.

**Comment by Playit3110** [comment]
It happens from version 1.3.155 till the most recent one (1.3.155, 1.4.159, 1.4.164) on an android 11 device.

**Comment by Robin-Sch** [comment]
@Playit3110 did you find a way to use a private key for sftp?

**Comment by Playit3110** [comment]
It still breaks after some time and i have to reopen the app and reload the connection

**Comment by Robin-Sch** [comment]
It never works for me and always gives the error Unsupported type: PRIVATE KEY

**Comment by Playit3110** [comment]
There you have made a mistake. There are two files, the private (id_rsa) and public (id_rsa.pub) key. The public is on the server you want to connect to and the private is the one you select

**Comment by Robin-Sch** [comment]
I know, and I'm 100% sure I give it the file to my private key

**Comment by Playit3110** [comment]
You can look inside the file. It should start with `-----BEGIN RSA PRIVATE KEY-----` or simular

**Comment by Robin-Sch** [comment]
I know what public and private keys are, I'm 100% sure. And it does start with that.

**Comment by Playit3110** [comment]
You can only try to generate a new key pair and try it again

**Comment by deadlyjack** [comment]
I've updated Maverick Synergy Java SSH API. I think it might work after the update. Please wait for version ^1.5.4 on play store.

**Comment by Robin-Sch** [comment]
What about fdroid?

**Comment by deadlyjack** [comment]
I have no Idea how to update there.

**Comment by Robin-Sch** [comment]
since the version on fdroid is the latest (1.5.3) I would guess it'll auto fetch version 1.5.4 when you release it, but I'm not sure

I'll let you know if it does or doesn't

**Comment by Playit3110** [comment]
The bug still appears in version 1.5.4
