### ISSUE TITLE
App doesn't allow } to be entered on physical keyboard with German QWERTZ Layout

### ISSUE THREAD

**Issue by Fighter1000** [deadlyjack/Acode#279]
The editor doesn't allow a } character to be entered on a physical keyboard with a German QWERTZ layout. The device I experienced this on is a Samsung Galaxy Tab S7+ with Android 11. This applies to both the Book Cover keyboard connected via pins on the bottom of the tablet and to external keyboards plugged in using an USB-C hub. The issue doesn't occur with the software keyboard or when setting the keyboard layout to QWERTY in the settings. The key works in some apps, so it isn't a hardware or OS problem (though interestingly, the Overleaf editor has this exact issue) The app version is 1.4.164 from the Play Store.

Please fix this, as it would be very annoying to use the app otherwise. Thank you.

Edit: It may be helpful to know that entering a closing curly brace on QWERTZ is done with Alt Gr + 0

**Comment by ImpatientHippo** [comment]
Same Problem on FP4 running Android 11 and a Medion BT Keyboard.

Also:
*other apps work (did not find another one with that problem)
*open curly brace works
*closing curly brace from onscreen KB works

This really sucks if you are into programming!

ACode version in use: 1.4.164

**Comment by claude0001** [comment]
On an F(x)tec Pro1 with built-in QWERTZ keyboard, I also encounter this. There seems to be a clash with the default key-bindings when trying to enter the "}" character via the hw keyboard.

The following workaround did the trick for me:

In the default ".key-bindings.json", change the following keybinds:

> "foldOther": {
>   "description": "Fold other",
>   "key": "Alt-0"
> },
> "unfoldall": {
>   "description": "Unfold all",
>   "key": "Alt-Shift-0"
> },

to

> "foldOther": {
>   "description": "Fold other",
>   "key": "Alt-1"
> },
> "unfoldall": {
>   "description": "Unfold all",
>   "key": "Alt-Shift-1"
> },
 
Not that the app needs to be restarted for the changed key-bidings to take effect. With this I can now type both curly brackets just fine. ACode version: 1.4.164.

**Comment by Alestrix** [comment]
> In the default ".key-bindings.json", change the following keybinds

Where can I find this? I couldn't find a ˋ.key-bindings.jsonˋ key in the settings.json. And I cannot simply edit files in the acode's program directory.
