### ISSUE TITLE
Svelte syntax highlighting not working

### ISSUE THREAD

**Issue by qxb3** [deadlyjack/Acode#282]
![Screenshot_2021-10-23-08-09-06-087_com foxdebug acodefree](https://user-images.githubusercontent.com/59109346/138534722-84bf0e2b-d54e-4ed5-9baf-57052895365b.jpg)

**Comment by deadlyjack** [comment]
Thanks for reporting it, I'll enable it, for now, you can choose 'HTML' syntax highliting.

**Comment by Rar9** [comment]
Is this working? 

Or is any specific config change required for .svelte files?
