### ISSUE TITLE
Arrow keys of Hacker's Keyboard in console

### ISSUE THREAD

**Issue by IMMSPgisgroup** [deadlyjack/Acode#285]
It is helpfull, may be, to use arrow keys  of Hacker's Keyboard in Acode console like keyboard arrow keys in desctop browser console.
![image](https://user-images.githubusercontent.com/33963849/140402760-d86ba599-3ee5-40bf-859a-5abc4301d236.png)

**Comment by deadlyjack** [comment]
Thanks for the great suggestion. I'll enable arrows keys to be used in the console.
