### ISSUE TITLE
"Read Only" option is not sticky after program exit.

### ISSUE THREAD

**Issue by siubb** [deadlyjack/Acode#288]
On other editor, the supposed behavior is either:

1. The program remembers this setting for each file. It sticks even after program exit, and reopen.
2. It is program-wide, the editor is effectively a "viewer" now, for all files.

(One more suggestion.
In Read-Only mode, probably the cursor can be hidden / disabled.
Coz I guess most people are not interested at the cursor in this mode, or they prefer less distractions.)

I have tried a lot of editors / viewers.
This is no doubt one of the best.
Please keep up the good work.

**Comment by deadlyjack** [comment]
Thanks for the suggestion. I'll keep it in mind to fix it.
