### ISSUE TITLE
Selection bar color in 'Default' was not easy to see with a light editor.

### ISSUE THREAD

**Issue by 14725** [deadlyjack/Acode#289]
I'm using ACode 1.4.164 on a Android 6.0 with com.google.android.webview 55.0.

I perfer light theme (instead of a dark one) with a light editor background, and I love the default theme. However, when I use these things, I can't see the select bar(? and please tell me what it is) due to the color. 

I tried to use the custom theme, however there's no setting related to that thing directly, but the "Text main color".

Is it possible to devide these tow color into two settings and fix the default theme? 
![IMG_20211111_163642](https://user-images.githubusercontent.com/32530438/141266499-3b51166e-7c35-47aa-a9cf-771c9421a477.png)
![IMG_20211111_163711](https://user-images.githubusercontent.com/32530438/141266537-013318a9-ffe5-45be-9917-aaca480ce824.png)

**Comment by deadlyjack** [comment]
Thanks for reporting this issue, will be fixed soon.
