### ISSUE TITLE
[Feature Request] - Support SFTP

### ISSUE THREAD

**Issue by veeshi** [deadlyjack/Acode#29]
Currently Acode supports FTP & FTPS. It would be nice in instances where these can't be used to be able to use SFTP, FTP over SSH.

**Comment by partyp770** [comment]
Yes please! I'd like this as well.

**Comment by usernein** [comment]
@partyp770 +1 for SFTP

**Comment by Kenilworth** [comment]
Yes, pls add

**Comment by kacperleague9** [comment]
+1

**Comment by guidokl** [comment]
+1
