### ISSUE TITLE
Manual setup quick tools (add or remove buttons)

### ISSUE THREAD

**Issue by OmlineEditor** [deadlyjack/Acode#296]
I have a cursor movement button and tab. I don't need these buttons and I want to customize the buttons individually, add a buttons and remove a buttons so that there is more space.

![1](https://user-images.githubusercontent.com/13348933/143724980-7c399cbe-e434-426a-b4e5-5ce9dfe129af.jpg)

**Comment by leandrocm86** [comment]
+1 for this! I just started using Acode and what I liked the most is this "quick tools" bar.
It REALLY helps the main purpose of the app: editing.
But there are some buttons I don't use, while there could be others I would, like Toggle comment (Ctrl-/), Remove line and other keyboard buttons such as HOME and END.

**Comment by Indranil012** [comment]
+1

**Comment by deadlyjack** [comment]
Sure, I'll add it.
