### ISSUE TITLE
FEATURE REQUEST: Load entire github repo on selection?

### ISSUE THREAD

**Issue by nathaneltitane** [deadlyjack/Acode#300]
Hello,

Unless I am mistaken, Acode only supports loading one file at a time regardless of its source (local, github, etc).
Could you provide a way/option to load an entire github repo/project for editing (stripped of any history of course as it could make the app unusable if not done properly) to facilitate **project** editing rather than single instance file based edits?

Thanks!

**Comment by AncientIs** [comment]
Thanks!!
