### ISSUE TITLE
#Feature_Request: Please add Vim mode.

### ISSUE THREAD

**Issue by Mesum-Hussain** [deadlyjack/Acode#302]
Please add a toggle button in the editor settings which enables Vim mode:

After enabling Vim mode, there should be a radio button on the editor screen somewhere on the top (so that it's pressed only deliberately and not by mistake, but still be reachable enough to be convenient to use) which toggles between insert mode and navigation mode (also known as normal mode in Vim). In insert mode the keyboard should appear and the user should be able to type the code. In the navigation mode a square box almost the size of the virtual keyboard (preferably with rounded corners and a blur glass look) should appear, and the cursor should become box like (just like in Vim, but slightly transparent just like highlight, for an elegant look) and that square box at the bottom should act like a trackpad to control the boxey cursor. Swiping and holding it should accelerate the cursor to move fast. Cursor animations are also preferable (like in Neovide editor).

Hope it gets through, would make the user experience for coding on Android a lot better.

Thank you 😊.

**Comment by bajrangCoder** [comment]
Check Vim plugin
