### ISSUE TITLE
"save as" actually deletes, overwrites, and commits without my knowledge 

### ISSUE THREAD

**Issue by cubetronic** [deadlyjack/Acode#303]
i was working on a file in my github repo. i had made some changes, but also introduced a bug, so i wanted to save those changes elsewhere without affecting my github repo. so i selected "save as" and chose a local folder, giving it a new name to identify it. acode didn't ask me about a commit message or anything.

then i wanted to reload the file from github. to my surprise, 2 commits had been made: the original file had been deleted, and a new file with the new name and changes and bug had been saved.

i would think that before making a commit, it should ask me if i want to commit.

now i have to clean up a mess, and it's a permanent mess in my commit history.

**Comment by cubetronic** [comment]
to be more specific...

1. work on a file in a github repo
2. select "save as"
3. select local folder
4. rename the file
5. save.

what i expected:
- the github repo should be untouched
- a new file in a local folder with a name i just specified should exist as i saved it.
- i should now be working on that local file, not associated with any repo.

what happened:
- a local file was saved as expected. the contents and filename were as expected.
- two commits had been made to my repo without my knowledge or authorization or opportunity for commit message.
  1. the original file was deleted
  2. a new file was committed with the new name and new contents identical to the file saved locally.
- i was probably left with the active window working on the github online file.

my main concern is that it made a commit (2 of them) without my authorization. secondary to that is that it didn't inform me that a commit had been made: i was surprised to find that commits had been made, and i wouldn't have known it unless i were looking through things.

**Comment by deadlyjack** [comment]
Try new update 1.6.0 (231). If the issue still persist you can reopen this issue.
