### ISSUE TITLE
disabling internet access

### ISSUE THREAD

**Issue by OmlineEditor** [deadlyjack/Acode#307]
I see that your program connects to the Internet without my knowledge. As I understand it, she checks for updates on the foxdebug.com website. I ask you to make it possible to disable checking for updates and disable Internet access without my knowledge.

**Comment by mkp95** [comment]
Just disable the data access permission from permission manager of your device

**Comment by OmlineEditor** [comment]
> Just disable the data access permission from permission manager of your device

I did so, but this method is not correct, it is better to turn off the update check in the program settings

**Comment by McJoe21** [comment]
Turn off your mobile data or WiFi easy

**Comment by OmlineEditor** [comment]
> Turn off your mobile data or WiFi easy

this is not a solution to the problem. It's a crutch

**Comment by McJoe21** [comment]
> > Turn off your mobile data or WiFi easy
> 
> this is not a solution to the problem. It's a crutch

Just trying to help

**Comment by deadlyjack** [comment]
Hi, I've removed any request going to foxdebug.com.
