### ISSUE TITLE
new menu items (line selection)

### ISSUE THREAD

**Issue by OmlineEditor** [deadlyjack/Acode#308]
please add several options to this menu:
- select the entire line from the cursor to the end
- select the entire line regardless of the cursor position
![add](https://user-images.githubusercontent.com/13348933/148421414-9542b27f-e12b-4bd0-81c8-5ef4165f46d6.jpg)

**Comment by deepkrg17** [comment]
Select the entire line from the cursor to the end : `Shift+End` / `Alt+Shift+Right` .
You can read [Acode Key-bindings](https://acode.foxdebug.com/docs/key-bindings) for more.

**Comment by OmlineEditor** [comment]
`Shift+End` - select the line to the end from the **_current_** cursor position (the first point is solved thank you)
`Alt+Shift+Right` - select the **_entire_** text to the end from the **_current_** cursor position

but there is a second:
I need to select **_only_** the entire line **_regardless_** of the current cursor position.

**Comment by deepkrg17** [comment]
I have never heard about such shortcut.
But there is a solution which most o the people use.
`Home` or `Alt+Left` to go to the line start  and then select to line end.

**Comment by OmlineEditor** [comment]
I don't have a home button on my phone, so I won't be able to use your method quickly. please add an option:
select only the entire line regardless of the current cursor position.

this will help in the implementation in the future for this request https://github.com/deadlyjack/Acode/issues/296

**Comment by deadlyjack** [comment]
Added features triple tap to select line.
