### ISSUE TITLE
Feature Request: Option To Select File Encoding and Option to select Line Endings (Unix or Windows)

### ISSUE THREAD

**Issue by krazyabouttechnology** [deadlyjack/Acode#309]
1. File encoding selection ability like ANSI, UTF-8, UTF-16 etc while saving would be great. If big/little endian can also be selected, even better.

2. Option to choose which line ending character to use CR/LF or CR. That will allow to preserve the file structure.

**Comment by RokeJulianLockhart** [comment]
@bajrangCoder, is the encoding and line ending character type automatically inferred from the file when opening it? As an example, when I open a CRLF file, does ACode automatically select the correct types?

**Comment by bajrangCoder** [comment]
Hmm(except some cases)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/deadlyjack/Acode/issues/309#issuecomment-2323262982

@bajrangCoder, can you elaborate?
