### ISSUE TITLE
Better support for long filenames

### ISSUE THREAD

**Issue by aisbergde** [deadlyjack/Acode#311]
Long filenames are truncated. I would to request implementation of ways to see the whole filenames, for example line wrap.
![Screenshot_2022-01-09-18-52-57-864_com.foxdebug.acodefree.jpg](https://user-images.githubusercontent.com/9020187/148694291-94b1ae51-69ac-49f0-bfe6-1809c3301ff5.jpg)
![Screenshot_2022-01-09-18-52-23-649_com.foxdebug.acodefree.jpg](https://user-images.githubusercontent.com/9020187/148694298-91b8a9e5-f954-4821-9390-20ec05cec058.jpg)

**Comment by deadlyjack** [comment]
You can see the full filename by long taping on file then info.
