### ISSUE TITLE
FEATURE REQUEST save cursor position when opening a file

### ISSUE THREAD

**Issue by OmlineEditor** [deadlyjack/Acode#314]
I often edit the same files. I open them and want the cursor position to be the same as it was at the time of opening and closing the file last time. so it's more convenient than every time from the moonshine I started permating and looking for a place where I finished editing

**Comment by deadlyjack** [comment]
Already implemented.

**Comment by OmlineEditor** [comment]
please indicate starting from which version you are implementing this functionality

**Comment by deadlyjack** [comment]
v1.6.0 (version code 197) will be released on GitHub, telegram and play store soon. please wait for the update

**Comment by OmlineEditor** [comment]
I'm using f-droid and waiting for you to fix the build problem https://github.com/deadlyjack/Acode/issues/410
