### ISSUE TITLE
Support zip file

### ISSUE THREAD

**Issue by adbenitez** [deadlyjack/Acode#322]
currently the only feature that I miss from **Squircle IDE** that is not present in Acode to replace it completely is the option to zip selected files, I need an easy way to zip some html, js, css, etc. files in a package for an app that opens this packages as "web apps" and wanted to recommend Acode as the preferred IDE on Android to create such "apps" since the integrated web server is just what I needed.

BTW, thanks for the great work!

**Comment by McJoe21** [comment]
Why cant you just extract the files

**Comment by adbenitez** [comment]
it is not about extracting but compressing, to package as a webxdc app (an offline web app that is a zip containing the resources, check webxdc.org)
