### ISSUE TITLE
Incorrect indent when auto-save beautifying

### ISSUE THREAD

**Issue by 14725** [deadlyjack/Acode#325]
```js
switch('...'){
  case 1:
  case 2:
  case 3:
  case 1024:
    alert('I like it!');
    break;
  default:
    alert("???");
}
var a = "We'll at the start without tabs";
```

after beautify:

```js
switch ('...') {
  case 1:
    case 2:
      case 3:
        case 1024:
          alert('I like it!');
          break;
        default:
          alert("???");
        }
        var a = "We'll at the start without tabs";
```

I run ACode 1.4.164 with Webview 55.0 (com.google.android.webview)

**Comment by deepkrg17** [comment]
Update the app.
You can join telegram group [Acode editor](https://t.me/foxdebug_acode/).
Latest version - [1.4.168](https://t.me/foxdebug_acode/40286)

**Comment by 14725** [comment]
Thank you for your concern.

I may update it after it's official publish, as the Telegram is banned in my country.
