### ISSUE TITLE
RegEx documentation?

### ISSUE THREAD

**Issue by peoute** [deadlyjack/Acode#327]
I couldn't find a reference to the implementation of RegEx in find/replace. I saw where to turn it on in the app, but couldn't get it to find or replace newlines with \n.

Is this possible?

**Comment by deepkrg17** [comment]
You can find line ends using regex with '$' .

**Comment by deepkrg17** [comment]
You can find line ends using RegEx with '$' .

**Comment by peoute** [comment]
Thanks. I did see it recognized ^ for beginning and $ for line end, but I was actually wanting to replace all spaces with \n for new lines to put everything on its own line.

Any place I can see what all RegEx patterns work?

**Comment by deepkrg17** [comment]
It is simple javascript RegEx.

And RegEx is almost same for all languages.
All main expressions are same.

**Comment by deepkrg17** [comment]
It is simple JavaScript RegEx.

And RegEx is almost same for all languages.
All main expressions are same.
You can learn from any resources like w3schools, MDN..

**Comment by peoute** [comment]
Ok. I could not get it to recognize new line. Do you expect it should? I tried:
\n
\\n
/\n/

**Comment by GrennKren** [comment]
I also can't replace new line using `$` to cartridge return `\r` to replace the end of a character to make the entire code fit on one line. 
`\r` just literally replaced as `\r` and not catridge return.

**Comment by sekedus** [comment]
Tracked this in existing issue #280
