### ISSUE TITLE
Files can no longer be opened in-app

### ISSUE THREAD

**Issue by Etanarvazac** [deadlyjack/Acode#334]
Folder view no longer shows files in any folders (see image). I am only able to add files to Acode by sending them from a file manager app. There is no option in the menu (there's a option to close, but that's it. see image)

![SmartSelect_20220131-193725_Acode.jpg](https://user-images.githubusercontent.com/55290878/151895875-40a1bc10-b8f9-4a71-b2dc-9f25e2899817.jpg)

![SmartSelect_20220131-193926_Acode.jpg](https://user-images.githubusercontent.com/55290878/151896022-89ff199b-c896-4eb5-b0bd-ddf50402781f.jpg)

**Comment by JavesBastatas** [comment]
Same, i also experienced this issue after the update.

**Comment by mkp95** [comment]
I had set Acode as default for some file ext in my phone. Now it's not opening the file from the intent. After the update it started happening.

**Comment by ManuelPeh76** [comment]
Same problem

**Comment by Refaza** [comment]
This must have happened because of permissions issue. I also experienced this problem. You have to add the folder path in the Files menu (+ icon) and allow Acode to access that folder.

**Comment by Etanarvazac** [comment]
> This must have happened due to permissions issue. I also experienced this problem. You have to add the folder path in the Files menu (+ icon) and allow Acode to access that folder.

These are the only 3 options I have in Files -> + icon

![SmartSelect_20220210-202942_Acode.jpg](https://user-images.githubusercontent.com/55290878/153524483-11d665d9-a22f-4ab0-9f45-f6a95f043563.jpg)

**Comment by Etanarvazac** [comment]
> > This must have happened due to permissions issue. I also experienced this problem. You have to add the folder path in the Files menu (+ icon) and allow Acode to access that folder.
> 
> These are the only 3 options I have in Files -> + icon
> 
> ![SmartSelect_20220210-202942_Acode.jpg](https://user-images.githubusercontent.com/55290878/153524483-11d665d9-a22f-4ab0-9f45-f6a95f043563.jpg)

Figured it out. Ib your message, it was assuming we were already on root "/" directory. Mine was still on the folder itself.

**Comment by deadlyjack** [comment]
Hi please read this https://acode.foxdebug.com/faqs/224761680 for more information. Closing this because it won't be fixed.
