### ISSUE TITLE
[FEATURE REQUEST] — Allow Acode To Stay In A Git Directory After Editing A File

### ISSUE THREAD

**Issue by Col-Serra** [deadlyjack/Acode#337]
Want to be able to stay in a directory after editing a file on GitHub without being returned to GitHub dashboard

**Comment by deadlyjack** [comment]
Thanks for the suggestion. I'm adding it to my to-do list.

**Comment by deadlyjack** [comment]
Instead of this, [isomorphic-git](https://isomorphic-git.org/) will be implemented in upcoming updates.
