### ISSUE TITLE
Overscroll-behavior css property doesn't seem to be respected by in app browser

### ISSUE THREAD

**Issue by Vixeliz** [deadlyjack/Acode#338]
Even if I set overscroll-behavior in css to be none of contain neither prevent refreshing when pulling down. I am doing some gamedev in acode and am trying to implement touch controls which they work in normal browser but whenever pulling down on in app browser it just refreshes

**Comment by deadlyjack** [comment]
Yes, I've fixed it in the latest version 1.5.2. Please wait for the update.

**Comment by Vixeliz** [comment]
Wonderful got the update! Thank you so much for this project it is truly amazing i hope to donate more in the future.
