### ISSUE TITLE
Console doesn't show error line number

### ISSUE THREAD

**Issue by Refaza** [deadlyjack/Acode#343]
On the legacy console it doesn't show the line number for error. It does show the line number for log. On the Eruda console it's show number but it doesn't seem like the actual line number.

![Screenshot_2022-02-09-15-39-34-22_e3c1f266f17b29c7b40472751f031275](https://user-images.githubusercontent.com/75516541/153162588-bb6689bf-16bd-47a3-9916-43abbe99b8af.jpg)
![Screenshot_2022-02-09-15-58-49-60_e3c1f266f17b29c7b40472751f031275](https://user-images.githubusercontent.com/75516541/153162678-a39da001-a7f9-42fb-9e29-f6f2088d2544.jpg)
![Screenshot_2022-02-09-15-40-35-29_e3c1f266f17b29c7b40472751f031275](https://user-images.githubusercontent.com/75516541/153162736-26f23d8c-8bd8-40ec-8e18-c8395261324b.jpg)
![Screenshot_2022-02-09-15-58-01-37_e3c1f266f17b29c7b40472751f031275](https://user-images.githubusercontent.com/75516541/153163096-5df1e870-c96d-47b3-9158-81fc84e33f9a.jpg)

**Comment by RickyM7** [comment]
Also the "check syntax error" option isn't working too.

**Comment by deadlyjack** [comment]
Thanks for informing me. I'll look into it and fix it in upcoming version.
