### ISSUE TITLE
Cannot scroll through file list on left side

### ISSUE THREAD

**Issue by niccokunzmann** [deadlyjack/Acode#352]
I use acode 1.4.164 from F-Droid on Android 6.

On the right side, faced with many files, I cannot scroll through them all. The ones at the bottom stay hidden. It does not scroll at all for me.

![Screenshot_20220217-172419](https://user-images.githubusercontent.com/564768/154831038-611da349-7614-41d3-a289-934cc42befa1.png)

**Comment by deadlyjack** [comment]
Update it from github. If you still face this issue let me know I'll reopen this issue.

**Comment by niccokunzmann** [comment]
Thanks! And thanks for ACode!
