### ISSUE TITLE
File Tab gets stuck if lifted during screen rotation

### ISSUE THREAD

**Issue by niccokunzmann** [deadlyjack/Acode#353]
I use Acode 1.4.164 from F-Droid. When I pick up a file name and drag it over to another location in the editor, and then, I rotate the screen, this tab does no attach any more.

![Screenshot_20220215-084457](https://user-images.githubusercontent.com/564768/154834051-548ade54-a8a8-4ede-8fc7-2738c2c6f453.png)
![Screenshot_20220215-084451](https://user-images.githubusercontent.com/564768/154834059-f17f0b1c-68d3-485b-b0e8-9e1b9a49790f.png)

**Comment by deadlyjack** [comment]
Fixed in v1.6.0 (222)
