### ISSUE TITLE
Tab size option doesn't work

### ISSUE THREAD

**Issue by FS-21** [deadlyjack/Acode#354]
Hi,

Under Android 12 (Galaxy Tab S8+), if I set any value (10, 20, 40, 120, 240, ... ) in:
**Settings -> Editor Settings -> Tab size**
tabs doesn't grow in width, they have always the default small size when I installed the app in Play Store.

**Comment by Ilithy** [comment]
Same finding for me,
Device:
Pixel 6 pro
Grapheneos - Android 12
Acode ver. 1.5.3
Install from: Github

**Comment by FS-21** [comment]
**Only as informative feedback**
I still reproduce the bug in the latest stable 1.5.5 at Google Play.

**Comment by deadlyjack** [comment]
Fixed in latest version v1.6.0 (197)

**Comment by FS-21** [comment]
No, it doesn't work with 1.6.0 released at Google play. Tested with Smartphone and tablet. You can put any number that the size won't change (I tried restarting the app after applying changes)

**Comment by FS-21** [comment]
![Screenshot_20220806-123332_Acode](https://user-images.githubusercontent.com/1371539/183245401-a00d096c-0fa9-4499-a908-93a6ba0249b8.jpg)

**Comment by FS-21** [comment]
Can you re-open the issue or I create a new one?

**Comment by deadlyjack** [comment]
Wait for the update.

**Comment by FS-21** [comment]
> Wait for the update. Update is not out yet.

Sorry but I updated to 1.6.0 (203), tried different values and still broken
