### ISSUE TITLE
No option to use microphone

### ISSUE THREAD

**Issue by kylejcassaday** [deadlyjack/Acode#359]
Hi I just recently installed this app and I noticed that when typing in the code editor there is no option to use the microphone to help write the code in the editor. I was recently using dcoder and I really enjoyed that function on it. If there's any way to include that on this app, I would be grateful. This is a great app thank you so much for building it.

**Comment by deepkrg17** [comment]
Can you please clear your concern ?

**Comment by cha0s** [comment]
Try:

`Settings -> App Settings -> Keyboard mode -> SHOW SUGGESTIONS`
