### ISSUE TITLE
App restarts , all foldings are lost

### ISSUE THREAD

**Issue by gitgerodot** [deadlyjack/Acode#360]
Hi,
When I edit my code, it has a lot of nested functions in it ,so I use code folding feature extensively. When I switch from app to home screen or another app and then switch back after 5 or 10 seconds , all folds are preserved and unchanged – everything is as I left it.

But , if I switch from app for a longer period or do some actions which may affect device memory ( install/delete some another app, open some new google tabs, watch youtube), and then return back to an app it seems to be restarting from zero – loading ‘A’ screen ,etc. 
Though I get returned to the line on which I left off, all my folds now are lost, as if I used ‘unfold all’ command. 

 Is it possible:
1.  to save the state of all folds?
2. to avoid app’s reloading and keep it persistent so that I could return to an app even after a day pause and still see all my folds as if I left them minute ago. 

How is that related to android memory management system? Why does Acode reload so often?

So i want this app working persistently in background mode somehow ..

**Comment by deadlyjack** [comment]
Hi, thanks for reporting this issue. I'm adding it to my to-do list. I'll try to fix it next update i.e. ^1.5.4. Thank you.
