### ISSUE TITLE
Can't access android/data in Acode.

### ISSUE THREAD

**Issue by RadioactiveRocket** [deadlyjack/Acode#364]
I know this is probably a silly question, but is it possible to acess files from android/data in Acode?

Version: 1.5.3

Device: Samsung S10

**Comment by deepkrg17** [comment]
Simple answer : You can't.
As you know it's a sily question.

**Comment by WeirdCircumstances** [comment]
This is a stupid answer

**Comment by deadlyjack** [comment]
It is not possible in Android 10 or larger.

**Comment by asl97** [comment]
Just wanted to share that it's possible with the use of third party apps right now, just need to find a FTP server that can access android/data and acode can edit through the ftp server

One such app is [MaterialFiles](https://github.com/zhanghai/MaterialFiles), using it's "add storage" "android/data" then sharing it via it's builtin ftp server, note that the author mention the [workaround](https://github.com/zhanghai/MaterialFiles/commit/5e7f24d9eea7418113b24287034c7d90d2d71852)  it's using will probably [stop working in future android](https://github.com/zhanghai/MaterialFiles/issues/384) 

It's slower and there are risk with this approach though, it is an ftp server after all.

Related issue:  #453
____

Someone willing can probably implement the workaround directly in acode and it would be faster and safer
