### ISSUE TITLE
Only shows limited number of Github branches (30)

### ISSUE THREAD

**Issue by nihilok** [deadlyjack/Acode#365]
As per title, the app only shows a limited number of Github branches for a given repo. When trying to access a branch in a particular repo I am unable to because the branches are shown in alphabetical order and only the first 30 are displayed (this is the default for the branches endpoint).

In the absence of pagination controls, I would suggest changing the default to the maximum of 100 branches per page. If you have fewer branches obviously this makes no difference, but would a huge help if you have more than 30.

Might be just a case of changing:
https://github.com/deadlyjack/Acode/blob/50f247ac4d4d623da6e7e655a4c97b3f421c42c9/src/lib/GitHubAPI/Repository.js#L168-L170
to
```
listBranches(cb) {
    return this._request('GET', `/repos/${this.__fullname}/branches`, {per_page: 100}, cb);
}
```

I'm struggling to build from the readme instructions due (I think) to deprecated packages and/or outdated JDK version??? Otherwise, I'd open a PR.

**Comment by deadlyjack** [comment]
Thanks for reporting this issue and for the help. I really appreciate it.
