### ISSUE TITLE
Markdown preview always shows blank page

### ISSUE THREAD

**Issue by af4jm** [deadlyjack/Acode#370]
both internal and in browser, previewing the HTML rendering of Markdown gives nothing but a blank screen... in the browser it shows that it's still loading, with the progress bar at around 10%, but even after several minutes there's no change

seems like the internal server/renderer is frozen

**Comment by deadlyjack** [comment]
Thanks for reporting it. I'm working on a fix. It'll be fixed in the next update i.e. ^1.5.4

**Comment by HackYardo** [comment]
Version 1.6.0(211), can view SVG at localhost:8158 but not MD,  v1.4.164(164) is fine. Anything to do?
