### ISSUE TITLE
Ftp passive mode doesn't work.

### ISSUE THREAD

**Issue by McUsr** [deadlyjack/Acode#371]
Every parameter entered correctly. To be fair, I have an '@' in the name that get translated to %40, but not sure if that had something to do with it  the translation. The commandline client, and Filezilla works just fine. The funny thing is that the first line of the content of the  Error dialogue  says okay.

**Comment by deadlyjack** [comment]
Please can you provide more details, on what device you are using, the version of Acode, and what server you are using for the FTP? Thank you.

**Comment by McUsr** [comment]
Thanks for looking into it.

I'll come back to you with an ftp site that works the same way.

Tommy.

tor. 7. apr. 2022, 10:33 p.m. skrev Ajit Kumar ***@***.***>:

**Comment by deadlyjack** [comment]
It should work in latest version.
