### ISSUE TITLE
Typescript, Tsx & Jsx autocomplete & snippets not supported 

### ISSUE THREAD

**Issue by EAGLE1309** [deadlyjack/Acode#372]
I have been using Acode for creating **reactjs and nextjs** apps but unfortunately `jsx, tsx and also typescript` doesn't seems to have autocomplete. It's actually painful to write everything and switch from `js & html` continuously to write faster!

**Comment by deadlyjack** [comment]
You should move this issue to [ace](https://github.com/ajaxorg/ace/issues)
