### ISSUE TITLE
Acode doesn't show which line is throwing error in JavaScript!

### ISSUE THREAD

**Issue by mosheur15** [deadlyjack/Acode#373]
I was trying to edit a JavaScript file. But I got an error on the console saying there is a error in my code.

![Screenshot_20220331-035849_Acode](https://user-images.githubusercontent.com/58356351/160938913-fda19423-052a-4224-884d-cad753703bfb.jpg)

But the problem is <b>I can't figure out which line is throwing the error. The console doesn't show any hints or line number. I also tried to set preview mode to "browser" but the browser console shows the same message. </b>I wrote at least 150+ lines. It is really annoying to manually find error by reading the whole file.

correct me if I am wrong, I think the previous versions had no such issues. I don't know if it's a  bug or the feature has been removed. But <b>please fix this issue as soon as possible.</b>

My device: Samsung A10 (android 11)

**Comment by deadlyjack** [comment]
Please can you provide a sample code to test? Because it's working for me.

**Comment by McJoe21** [comment]
Use a browser called F12 to do the thing that you want
