### ISSUE TITLE
Cant create file to termux location ver1.5.3

### ISSUE THREAD

**Issue by riparuk** [deadlyjack/Acode#375]
when i create file and Its happened (termux location path/)

![Screenshot_20220407-150547.png](https://user-images.githubusercontent.com/94559656/162151234-2136c1a6-e1ad-4494-bddc-b0415c27d6c3.png)
The file is not saved! When i open the app again its happen

![Screenshot_20220407-150238.png](https://user-images.githubusercontent.com/94559656/162150623-20a82343-76cc-4be9-a184-66ec50d60f8e.png)

If i choose termux location is "path/:" with ':' its happened
![Screenshot_20220407-150405.png](https://user-images.githubusercontent.com/94559656/162151138-d5a3df55-2b15-4476-8ea5-2dc57678e260.png)

**Comment by deadlyjack** [comment]
Don't create files in the root directory of Termux. Create your files is Termux/storage/
