### ISSUE TITLE
Can't exit Search/Replace Settings menu

### ISSUE THREAD

**Issue by CantBeCorrect** [deadlyjack/Acode#380]
The settings menu for the Search and Replace function (where one can e.g. toggle case sensitivity) can't be exited, neither by using the back button in Acode, nor by using hardware buttons. No visible error messages, the menu just stays. It does not matter, which options are selected. 
The app has to be killed to return to normal.

The bug appeared after the most recent update. 

Acode Version: 1.5.4
Android Version: 12

![Screenshot_20220414-151832_Acode.png](https://user-images.githubusercontent.com/86210957/163399072-543c4095-ecd3-4a19-a6ef-a2635c5d35d0.png)

**Comment by woshilaiba** [comment]
> The settings menu for the Search and Replace function (where one can e.g. toggle case sensitivity) can't be exited, neither by using the back button in Acode, nor by using hardware buttons. No visible error messages, the menu just stays. It does not matter, which options are selected. The app has to be killed to return to normal.
> 
> The bug appeared after the most recent update.
> 
> Acode Version: 1.5.4 Android Version: 12
> 
> ![Screenshot_20220414-151832_Acode.png](https://user-images.githubusercontent.com/86210957/163399072-543c4095-ecd3-4a19-a6ef-a2635c5d35d0.png)

The same on Android 11

**Comment by deadlyjack** [comment]
Fixed in version ^1.5.5.
