### ISSUE TITLE
Acode can not find any folders

### ISSUE THREAD

**Issue by Kalmai221** [deadlyjack/Acode#381]
I try and open my project but the only folder I see is "Internal Storage" that is shown to be empty in the app

**Comment by TA874** [comment]
Internal (and external) storage isn't empty but Acode can't access it's content as required by Google, or else Acode won't be available on Google Play Store anymore. Please use ***select document*** or ***add path*** options, they redirect to Google's file manager to be able to open a file or import a folder. Also on Android 11 or above, you cannot import the whole internal/external storage. The only folder (and it's files/subfolders) Acode always has access is ***/storage/emulated/0/android/data/(Acode's package name)/files***

**Comment by chrisrapson** [comment]
@ghost those instructions aren't working for me. 

I can open up the `add path` menu, choose the folder,  and confirm that I want to "Allow Acode to access files in `folder name`". Now I can see the folder and the files inside it in the Acode "file browser". If I select the folder and press the tick,  now the folder and its contents show up in the left menu, below the list of `Active files`. But when I try opening any of the files from either the left menu or the Acode file browser, nothing happens.

I am able to open the files from the Android file manage, if I use `open with` and select Acode. I can edit and save them. The only problem seems to be opening them.

Do you have any suggestions what else I could try? I'm on version 1.8.3.
