### ISSUE TITLE
[Feature request] Use javascript mode for .mjs & .cjs files

### ISSUE THREAD

**Issue by pufferfish101007** [deadlyjack/Acode#382]
`.mjs` (module js) & `.cjs` (commonjs i.e. using `require`) files are becoming more common, especially in the nodejs ecosystem. Ipbe found myself editing mjs files and having to set language highlighting to javascript manually, which is annoying. It would be great if these could be added as file extension for javascript.
I've already made the necessary changes in https://github.com/pufferfish101007/acode/tree/patch-1, but didn't want to make a pr in case it got denied.

**Comment by deadlyjack** [comment]
I've I have fixed the issue, Please wait for the update to be published. Thank your for reporting it.
