### ISSUE TITLE
FEATURE REQUEST (ADD DEFAULT PREVIEW FOR HTML)

### ISSUE THREAD

**Issue by A-TECHH** [deadlyjack/Acode#384]
and default preview option to file editing options so that wen enabled one can be able to preview index.html file from css and javascript.
When working with multiple js and css files i always have to re-open my index.html file to preview thank you , good  luck and keep up the good work  👏👏👏 👍

**Comment by deadlyjack** [comment]
Open the project folder that contains the index.html file. You'll see the run button in the top right corner even if any file is currently active.

**Comment by A-TECHH** [comment]
am working with multiple files and folders and not all files are linked directly with the html file.
SPCK has this feature, this is what i mean..
![Screenshot_20220417_123657](https://user-images.githubusercontent.com/102123629/163712697-8e3ba0e4-32b2-4f67-9ae3-8f014b9c0fd9.jpg)

The launch default option there. when set i can preview in any file except html files

**Comment by deadlyjack** [comment]
Open the whole project in Acode and you will get the same feature.  Join the telegram [group](https://t.me/foxdebug_acode) for more help.
