### ISSUE TITLE
App restarts, not all foldings are remembered

### ISSUE THREAD

**Issue by TA874** [deadlyjack/Acode#386]
How to reproduce: https://youtu.be/mbA_4b7vCAU

**Comment by TA874** [comment]
version: v1.5.4

**Comment by TA874** [comment]
![Point Blur_Apr182022_174623](https://user-images.githubusercontent.com/78432747/163834463-81bd4c09-dc27-4037-a27a-fabc5d12d45a.png)
Android 11, One UI 3.0

**Comment by deadlyjack** [comment]
Hi, this is fixed in the latest version v1.6.0 (197)
