### ISSUE TITLE
[FEATURE REQUEST] — Enhancing quick tools

### ISSUE THREAD

**Issue by leandrocm86** [deadlyjack/Acode#393]
I feel the "quick tools" option may be a bit underestimated. After all, its purpose is to facilitate editing - the main goal of a text editor!
I have the following suggestions to make this great option even better:

- A new row for keyboard keys: having CTRL, ALT, HOME, END would be great for us phone users, and we wouldn't need a different keyboard app for editing.

- The buttons for arrow keys should be moved to this new "keyboard row". In their place, there could be other buttons more similar to the others in that row (line actions), such as: remove line, select to line start, select to line end, toggle comment.

I'm open to discuss other ideas about the quick tools. **I really feel it's a game changer**. The main reason for people to prefer editing on a PC over the phone is the power that a full keyboard and a mouse can give. The use of quick tools buttons help shortening that efficiency gap between PC and phone.

**Comment by deadlyjack** [comment]
Thank you for the suggestion. I'll consider this recommendation in next update.

**Comment by pyramid3d** [comment]
Great application!
I am using Acode to edit source code and document files (.md, .txt). A keyboard shortcut or quick tools icon to toggle Settings>EditorSettings>TextWrap would be of great help. Thanks!
