### ISSUE TITLE
[FEATURE REQUEST] Highlighting HTML code inside JavaScript string literal 

### ISSUE THREAD

**Issue by mzaini30** [deadlyjack/Acode#398]
![image](https://user-images.githubusercontent.com/7939342/168493662-88cc8db9-d154-49e9-992a-25ef27f6522c.png)

Example setting in Sublime Text: https://forum.sublimetext.com/t/how-to-enable-css-highlighting-in-template-literal-strings/45264/6

**Comment by deadlyjack** [comment]
You should move this issue to [ace](https://github.com/ajaxorg/ace/issues). I have used ace editor inside acode. If they add it, I will update it.
