### ISSUE TITLE
Problem formatting code 

### ISSUE THREAD

**Issue by userbrdev** [deadlyjack/Acode#399]
editor messes up all code when using format code option
It doesn't format well when we have these quotes => `
![Screenshot_20220509130109](https://user-images.githubusercontent.com/83094160/168933787-310c1cc0-50ad-4c90-9134-fe0dea16b158.jpg)

**Comment by deadlyjack** [comment]
user prettier plugin. or report this issue at [ace](https://github.com/ajaxorg/ace/issues)
