### ISSUE TITLE
Show git changes of the current folder

### ISSUE THREAD

**Issue by linsaftw** [deadlyjack/Acode#400]
If there is a git project in the current folder show git changes as a prefix of the opened project files and folders like on VSCode (M for modified and U for the created ones).

**Comment by nicesapien-too** [comment]
Yea cool idea, I think it should be added. If I was able to build Acode by myself, I would add that. I was encountering a problem, i opened a issue but Deadlyjack closed it without helping much.

**Comment by biraj21** [comment]
Please refer to https://github.com/deadlyjack/Acode/issues/483#issuecomment-1223927901.
