### ISSUE TITLE
Permission to allow management of all files

### ISSUE THREAD

**Issue by ajpalok** [deadlyjack/Acode#401]
In F-droid version of Acode app have the permission to allow to read and write all files rather than media files! All files permission was helpful for folder setup and also helpful for selecting folders from SD card, but this newer version of Acode from GitHub doesn't have that which makes some bad user experience.
  
![all files permission](https://user-images.githubusercontent.com/66951426/169334229-2df5c0fc-e210-4198-b073-e3ddd4b1c7ee.png)
  
Here is the screenshot of the previous version. where newer versions don't have the first option to allow _management of all files_.

**Comment by deadlyjack** [comment]
Google rejects any update if I add this. Nothing there I can do. Sorry.

**Comment by ajpalok** [comment]
Is that will be available on F-droid version?
