### ISSUE TITLE
Impossible to open folder with %2F in the name

### ISSUE THREAD

**Issue by tYYGH** [deadlyjack/Acode#404]
I have Nexcloud files on my phone, from my home-server where Nextcloud is hosted in a subfolder. Thus my Nextcloud path looks like https://example.org/nc, which becomes in `Android/media/com.nextcloud.client/nextcloud/` a subfolder named `yves@example.org%2Fnc`.
Instead of this name, Acode displays `nc`, and upon selection, tells that `nc` does not exist, which is true.

This makes using Acode on my dev projects impossible :-(

Until this is fixed, can you tell me where Acode stores the list of favourite folders? I would like to try and put the correct path in there myself.

Thanks for this excellent editor! Definitely the best I found on FDroid 👍

**Comment by deadlyjack** [comment]
Hi, I've fixed this issue. Please wait for the update to be published. Thank you for reporting it.
