### ISSUE TITLE
[FEATURE REQUEST] snippets for typescript

### ISSUE THREAD

**Issue by ternenges** [deadlyjack/Acode#405]
javascript snippets are not available when using typescript.
It will be nice to at least enable javascript snippets in typescripts and better if typescript snippets are available. Great Job Really Love this 10 stars, LOL. 🥇 👍 💯

**Comment by deadlyjack** [comment]
You should move this issue to [ace](https://github.com/ajaxorg/ace/issues). If they fix it, I'll update it.
