### ISSUE TITLE
[FEATURE REQUEST] Add option to hide soft keyboard.

### ISSUE THREAD

**Issue by ternenges** [deadlyjack/Acode#406]
some mobile devices don't  have options  for disabling toch key board when physical key board is connected. this setting will come very handy if implemented. thank you.

**Comment by griffi-gh** [comment]
Then just use a keyboard that has this option.

**Comment by deadlyjack** [comment]
This is harder to achieve for a Cordova app. Only option to do it using keyboard settings.
