### ISSUE TITLE
[Bug?] Some documentproviders throw an error message despite working

### ISSUE THREAD

**Issue by Vixeliz** [deadlyjack/Acode#408]
I've noticed in some documentproviders when creating new files or folders it'll throw this error message: 
![Screenshot_20220602-022715_Acode](https://user-images.githubusercontent.com/38061852/171576918-be853514-408a-4156-bd28-ca7da2bddcac.jpg)

However when simply minimizing and reopening said folder in the sidebar the file was indeed successfully created which can be confirmed by looking at the documentprovider in another application. This doesn't technically affect functionality but is annoying.

**Comment by deadlyjack** [comment]
fixed in the latest version i.e. v1.6.0 (197).
