### ISSUE TITLE
F-Droid builds are out of date

### ISSUE THREAD

**Issue by balporig** [deadlyjack/Acode#410]
The current F-Droid version getting quite old `1.4.164 (164) - Added on 2021-10-12`

**Comment by jstetten** [comment]
Very out-of-date. @deadlyjack, are you still planning to support F-droid in the future? Planning to move away from open source?

**Comment by deadlyjack** [comment]
I don't know how to update there. I have no idea. If anyone can help.

**Comment by jstetten** [comment]
Since ACode is the premiere (IMO) open source coding app and central to the flow of a great deal of open-source-minded developers, I'd like to ask for @IzzySoft's guidance, when he has time — as he's the font of all Android open source repo knowledge.

**Comment by IzzySoft** [comment]
I can take a look (which would have been easier if I had known the package name :wink:). Seems like F-Droid is no longer able to build the app:

* disable: webpack fails
* disable: Task 'assembleRelease' not found in project ':app'.

1.4.164 was the last version with a successful build. 1.5.4 failed with the above errors, 1.5.5 was not even tried as at the tag it still identifies as 1.5.4 (i.e. version was only adjusted AFTER tagging, should have been BEFORE; so lifting the tag to the corresponding commit would trigger another build).

> he's the font of all Android open source repo knowledge.

:flushed: Oops…

**Comment by deadlyjack** [comment]
Do you know how to fix YAML prebuild section? There are some corrections.

```yaml
prebuild:
      - mkdir -p platforms
      - npm install
      - node ./utils/config.js p paid
      - ./node_modules/.bin/webpack --progress --mode production
      - cordova platform add android # change to android@9
      - node ./utils/loadStyles.js
      - sed -i -e '/signingConfig signingConfigs.release/d' -e '/gms/d' -e '/core-google-shortcuts/d'
        platforms/android/app/build.gradle
```

**Comment by IzzySoft** [comment]
No, sorry – I'm not a developer, and completely unfamiliar with node stuff (so for me it would rather be copy-pasting blindly). I couldn't even test that or, if it throws errors, guess what they mean and how to fix. Maybe you could open a merge request with that at fdroiddata? You would most likely know how to interpret output. Should you need help there then, a team member more familiar with node would certainly be able to help.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
...Did http://github.com/deadlyjack/Acode/pull/430 remediate this?

**Comment by IzzySoft** [comment]
No idea. The last tag I see here is 1.6.0, which was before that PR was merged; the corresponding build is disabled at F-Droid's end:

```yaml
  - versionName: 1.6.0
    versionCode: 186
    disable: webpack fails
    commit: 0b5dd6d3b723ac4f1d2a8f591af3541d603106b1
```

We will learn more when the next tag was picked up. And to repeat myself: I cannot test this, I'm no developer :wink: But maybe I find someone to check, no promises though.

**Comment by OmlineEditor** [comment]
download and view the latest build log for version 1.6.0:
https://f-droid.org/repo/com.foxdebug.acode_186.log.gz

look at the lines where there are the words **ERROR**.
there seems to be a problem with the file:  `/src/components/inputHints.js` 
sometimes he does not see the extension, sometimes the letter case is different.

**Comment by deadlyjack** [comment]
Thank you so much for the report. I have fixed this. It was supposed to be '../inputhints' instead of '../inputHints'. It might work in the next update.

**Comment by licaon-kter** [comment]
Building 05acef9d1c9d47fae25055948a2e133074ddae27 fails with:
[com.foxdebug.acode_196.log.gz](https://github.com/deadlyjack/Acode/files/9232767/com.foxdebug.acode_196.log.gz)

**Comment by OmlineEditor** [comment]
> Building [05acef9](https://github.com/deadlyjack/Acode/commit/05acef9d1c9d47fae25055948a2e133074ddae27) fails with: [com.foxdebug.acode_196.log.gz](https://github.com/deadlyjack/Acode/files/9232767/com.foxdebug.acode_196.log.gz)

now there is only one error and the error is strange

`2022-08-01 09:43:51,786 ERROR: Could not build app com.foxdebug.acode: Error running prebuild command for com.foxdebug.acode:1.6.0`

perhaps you need to change the version from 1.6.0. to 1.6.1 and upload new corrected sources code?

**Comment by OmlineEditor** [comment]
> Where are the "corrected sources code" if not here in this repo? :)

it seems to me that f-droid does not download the repository, it downloads the archive from the list of releases. are you sure that the entire repository is being downloaded?

**Comment by licaon-kter** [comment]
F-Droid clones the repo at the right commit one wants.

**Comment by OmlineEditor** [comment]
> Not sure I follow, what is missing exactly? Link to the missing files?

all files are there but differ in content in the repository and in the archive here https://github.com/deadlyjack/Acode/archive/refs/tags/v1.6.0.zip

I thought this particular archive was used to build

**Comment by licaon-kter** [comment]
I've heard that github archives sometimes (not sure why) have different contents.

But no, we always use git to clone the whole repo, then checkout the needed commit.

**Comment by griffi-gh** [comment]
> Since ACode is the premiere (IMO) open source coding app and central to the flow of a great deal of open-source-minded developers, I'd like to ask for @IzzySoft's guidance, when he has time — as he's the font of all Android open source repo knowledge. 

it's not that big of a deal,  you're not going to code anything serious on your phone lol

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11628 Finally it builds and works. I still need to patch the code but thanks to https://github.com/deadlyjack/Acode/pull/430 some patches are not needed.

**Comment by deadlyjack** [comment]
Thanks for the help, I appreciate it.

**Comment by licaon-kter** [comment]
Close this then

**Comment by AeliusSaionji** [comment]
Seems like it's broken again- last version 1.6.0

I thought development had ceased until just now.

**Comment by licaon-kter** [comment]
@AeliusSaionji there's no release nor any tags, maybe they existed in the past so F-Droid could [magically update](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.foxdebug.acode.yml#L263)... but they ain't now :(

**Comment by linsui** [comment]
Updated. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12763

**Comment by Beryesa** [comment]
Can we have the minor updates as well? Pretty please 🥺

**Comment by linsui** [comment]
Updated. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13286 I have to take some change from https://github.com/deadlyjack/Acode/pull/659.
