### ISSUE TITLE
Reliability detecting changed files

### ISSUE THREAD

**Issue by Markus00000** [deadlyjack/Acode#421]
When editing files that are synchronized across devices, Acode does not seem to reliably detect when opened files on disk have changed while it is running. At least not in a timely manner.

In my experience, the reliability is higher when resuming and lower while Acode is idling (while being the foreground app). If the current file has been modified in Acode, it does not seem to warn about background changes even after minutes of editing.

If Acode cannot be notified instantly about changed files (like with inotify), then maybe it could at least check for changes more often. Particularly when:

* The user tries to make the first edit to a (seemingly) unmodified file.
* The user is continuously editing the file.
* Acode is resumed.

Version: 1.6.0

**Comment by deadlyjack** [comment]
Hi, I've improved file checking process, this will be available in latest update. Please wait for the update to be published. Thank you for reporting it.
