### ISSUE TITLE
shortcut not work

### ISSUE THREAD

**Issue by Ahmadreza-1995** [deadlyjack/Acode#426]
im using codeboard keyboard(have Ctrl,Shift & .... keys) in acode.some shortcuts not work & when i edit keybinding json file and change or add shortcut its not work & its not changed in command pallette. i test codeboard in acode 1.5.5 or other apps like acode & it works good. in 1.6.0 version json file changes not save in comman pallete and not work.please help me

**Comment by deadlyjack** [comment]
Fixed in version v1.6.0 (version code: 189)

**Comment by Ahmadreza-1995** [comment]
> Fixed in version v1.6.0 (version code: 189)

Thanks
