### ISSUE TITLE
Acode doesn't properly check file's save state v1.6.0

### ISSUE THREAD

**Issue by TA874** [deadlyjack/Acode#439]
https://youtu.be/z94e22444mc

**Comment by deadlyjack** [comment]
Thanks for reporting. I'll fix it.

**Comment by TA874** [comment]
As a result I will not update to v1.6.0 (but update to v1.5.5) untill this issue is fixed in the next version

**Comment by deadlyjack** [comment]
Fixed in 1.6.0 (192)
