### ISSUE TITLE
Acode(Prettier) scrolls to last line when saving

### ISSUE THREAD

**Issue by maddogandnoriko** [deadlyjack/Acode#442]
I just updated yesterday and with Prettier installed, when I save Acode scrolls to the last line of code. Without Prettier the code then loses most indenting/formatting. I'm on a GalaxyA02s with Android 11.

**Comment by deadlyjack** [comment]
Move this issue to [acode-plugin-prettier](https://github.com/deadlyjack/acode-plugin-prettier)
