### ISSUE TITLE
[Feature Request] Custom Snippets

### ISSUE THREAD

**Issue by b1mind** [deadlyjack/Acode#45]
Would be nice to be able to write/edit our own snippets (and have them be priority when typing).

Also docs with syntax and how-to for it. (be nice if it used VScodes json format).

p.s. Loving this IDE app, keep up the hard work.

**Comment by natema** [comment]
In the app I can navigate to `Settings > Other settings > Key bindings > Edit` which opens a `.key-bindings.json` file in the `acode` folder, but I can't find any documentation on how that is supposed to work.
