### ISSUE TITLE
[Feature Request] Add intent to view restricted folders

### ISSUE THREAD

**Issue by fatboychummy** [deadlyjack/Acode#453]
Hello! I've got a programming app which saves its data to `/Android/Data`, however its builtin editor is rather garbage (and does not have git). I was hoping to use this to edit those files, but it seems this app does not have a way to declare intent for accessing those restricted folders.

The top answer on [this StackOverflow question](https://stackoverflow.com/questions/68625169/how-get-permission-for-specific-folder) explains how one would declare the intent and access those folders without the "Administrate *all* files and folders" permission being required. I would love to help further than this (if I could have came here with a PR instead of an issue I'd have been quite happy), but unfortunately I am not very well versed in JS / Java yet.

This will potentially help with issues like #401.

**Comment by deadlyjack** [comment]
Unable to fix it. Sorry. May be I'll look into it again in future.
