### ISSUE TITLE
Acode detected as virus trojan

### ISSUE THREAD

**Issue by amir-hz** [deadlyjack/Acode#454]
![Screenshot_20220721_184402](https://user-images.githubusercontent.com/7609160/180206043-3c9c3ea4-581c-4ecc-8a9e-aec5fd16a672.jpg)
the antivirus on my android (Vivo with FuntouchOS) detected Acode as a virus.  Even though I bought this application from the Play Store

**Comment by deadlyjack** [comment]
Hi, this is false positive detection. You have nothing to worry about. Acode is totally safe.
Check this [virustotal.com](https://www.virustotal.com/gui/file/4d1d42539a33c38233b0f38a95cfba4d4beb23a1e4489130e2809249a2335da9?nocache=1) report.

**Comment by amir-hz** [comment]
Great, thanks!
