### ISSUE TITLE
Sftp add crash

### ISSUE THREAD

**Issue by SrBanYT2143** [deadlyjack/Acode#460]
Sftp crash app

**Comment by SrBanYT2143** [comment]
What?

**Comment by SrBanYT2143** [comment]
it's still crashing when i try to add an sftp and connect

**Comment by deadlyjack** [comment]
Please provide more details, how you are getting this error. A screen
recording would be helpful.

**Comment by SrBanYT2143** [comment]
I think it might be when I changed the port to 2022

**Comment by SrBanYT2143** [comment]
Uploading vidma_recorder_31072022_193820.mp4…

**Comment by SrBanYT2143** [comment]
Em 31 de jul de 2022 19:23, "Ajit Kumar" ***@***.***>
escreveu:

> Please provide more details, how you are getting this error. A screen
> recording would be helpful.
>

**Comment by SrBanYT2143** [comment]
https://user-images.githubusercontent.com/76711582/182048239-a7cfe32d-992a-4680-bdfd-51a683dc4171.mp4
