### ISSUE TITLE
Issue with Hackers keyboard

### ISSUE THREAD

**Issue by icefront** [deadlyjack/Acode#461]
It seems, that the newest version, 1.6.0 has problems with Hacker's Keyboard. Tested on Android 12 and 13, Samsung Galaxy S22 ultra and Samsung Galaxy A70.
The arrow keys do not work (the cursor cannot be moved).

**Comment by deadlyjack** [comment]
Clear app data to fix it.

**Comment by icefront** [comment]
There are countless FTP sites configured for this app. Clearing the data will delete all connection configurations. There should be a way to save these configurations, resetting the app is always the most destructive way to fix things...

**Comment by deadlyjack** [comment]
Go to settings, backup, after resetting app restore settings.
