### ISSUE TITLE
Whether animation is enabled should be determined by Android.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [deadlyjack/Acode#462]
Acode should adhere to whether animation has been mandated as enabled or disabled by Android via ![this page.](https://user-images.githubusercontent.com/42837531/181773028-3ce48307-7a67-407f-b5b4-fefb8d513dcb.jpg)

**Comment by deadlyjack** [comment]
thanks for the suggestion I am adding it.

**Comment by deadlyjack** [comment]
Available in v1.6.0 (version code: 197)
