### ISSUE TITLE
Support Material 3.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [deadlyjack/Acode#464]
My rationale is available at "http://github.com/QuickLyric/QuickLyric/issues/271#issue-1054902836".

**Comment by biraj21** [comment]
We understand your reasoning but there are no plans to change the user interface as of now.  The styling is completely written by us from scratch so it would take a lot of effort to change to Material UI right now. And our main focus is to release the stable version of Acode with the most required features. We hope you understand. Thank you.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Understood, although I suggest that you at least close at not planned rather than complete, or ideally merely leave this open until it is able to be implemented, because ACode's current interface is aesthetically unpleasant and, more importantly, *inaccessible* enough that I am not easily able to suggest it to others.
