### ISSUE TITLE
[BUG] ACode Pro no longer responds to arrow keys on a physical keyboard

### ISSUE THREAD

**Issue by Etanarvazac** [deadlyjack/Acode#465]
As title, cursor no longer moves when pressing an arrow key.

**Comment by PopSlime** [comment]
Also not working on virtual keyboards. Even the arrow buttons in the toolbar are also not working.

**Comment by Fedeshadow** [comment]
> As title, cursor no longer moves when pressing an arrow key.

Deleting and reinstalling the app worked for me

**Comment by PopSlime** [comment]
> > As title, cursor no longer moves when pressing an arrow key.
> 
> Deleting and reinstalling the app worked for me

Clearing app data also worked, but restoring a backup file from an older version reproduces the bug. Seems that it's a backward compatibility issue.
