### ISSUE TITLE
SFTP problem

### ISSUE THREAD

**Issue by jailrobeta** [deadlyjack/Acode#467]
Garasi Potong:
💠 Device Name : redmi 10 selene_id
💠 Device Android Version android 11
💠 Device ROM name (if any) miui
💠 Custom Languages, Fonts, custom rom tweaks enabled (if any) english

when i set this, with file id_rsa.pub, said a suitable key format could not be found.

so i change to password type

then still said a suitable key could not be found.....

but solution is just click cancel and choose password. its work no problem again

but. when i use password authentication type... 
every close a app.. i must re enter password again, and the authentication type change to key file..

i must re setting again every close app.

**Comment by SrBanYT2143** [comment]
True

**Comment by deadlyjack** [comment]
Closed in favour of #458
