### ISSUE TITLE
Acode inserts suggestion instead of expanding Emmet abbreviation when pressing tab

### ISSUE THREAD

**Issue by DarkCat09** [deadlyjack/Acode#472]
Description in this GIF: https://i.ibb.co/K23X7LS/acode-suggestions.gif  
Maybe it's better to firstly insert Emmet HTML when pressing <kbd>Tab</kbd> if it's possible, and if not, insert suggestion.  
Or just set different keys for Emmet (e.g. tab) and for suggestions (e.g. enter).

**Comment by deadlyjack** [comment]
Press esc before expanding emmet.
