### ISSUE TITLE
Bug: cursor position incorrect when entering 'combining diacritical marks' or Thai script 

### ISSUE THREAD

**Issue by windwerfer** [deadlyjack/Acode#476]
expected: cursor position after entering a normal and a combing char: 1 char shifted

what happens: cursor moves 2 positions

result: the cursor position is off for all following char in that line (if there are a lot of combining char it becomes very hard to edit text without trying out at wich place the actual cursor position is)

to replicate copy the following lines
h̅  type h + u+305  
or in asian langages (eg Thai)
ก้   type ก +  ้  (u+e01 + u+e49)

a more extreme example (cusor is off by about 7 char at the end of the line)
แม้ว่าชาวเน็ตจะไม่สนใจมองผ่านเมื่อตอนแรกๆ

ps thank you very much for the hard work. i really like this editor.

**Comment by deadlyjack** [comment]
Can you share a test file so I can test it myself?

**Comment by windwerfer** [comment]
thanks for the quick reply, here a test file.
[https://drive.barthoptik.de/diacritics.txt](file)

**Comment by deadlyjack** [comment]
Hi, I've tried solving it, but it didn't work. I request you to open this issue at https://github.com/ajaxorg/ace thank you.

**Comment by windwerfer** [comment]
thank you very much for trying. i will post the issue over there.

**Comment by windwerfer** [comment]
there is a duplicate there already:
https://github.com/ajaxorg/ace/issues/4685
but i cant comment on it somehow to elaborate on the subject.
wait and see than.
