### ISSUE TITLE
Syntax error message remaining fixed

### ISSUE THREAD

**Issue by DarkLordRafa** [deadlyjack/Acode#477]
The white box sintaxe error is getting fixed on screen
![2022_08_12_23 36 35](https://user-images.githubusercontent.com/93549989/184465375-aaa873fa-fdb7-4756-8d4f-5b736f4f04b2.jpg)
![2022_08_12_23 36 55](https://user-images.githubusercontent.com/93549989/184465380-44a4e422-8ee3-42d3-85a3-b6af080fa45a.jpg)

**Comment by deadlyjack** [comment]
This feature is removed from core editor and will be available as plugin in later updates. Thank you so much reporting it.
