### ISSUE TITLE
Latest scroll update did nothing for me

### ISSUE THREAD

**Issue by DarkLordRafa** [deadlyjack/Acode#478]
The scroll behavior still too fast for me, even setting to slow, changed nothing. Maybe the problem is my phone model? (Moto E5), or android version? (8.0.0). Before the recent updates the scroll was not so fast

https://user-images.githubusercontent.com/93549989/184467978-fb4965b9-9293-471e-a4ef-386b2449989b.mp4

**Comment by deadlyjack** [comment]
Hi, I've fixed the issue in latest update, please wait for the update to be release. Thank your for reporting it.
