### ISSUE TITLE
Add my favorite fonts and make the column display the number of lines smaller

### ISSUE THREAD

**Issue by NTT1906** [deadlyjack/Acode#48]
Can you? Please :'3
[Fonts](https://cdn.discordapp.com/attachments/683325546981097549/714850003398557747/SegoeWP-Semibold.zip)

**Comment by deadlyjack** [comment]
If it's monospaced font, I'll add it if not it will not work.

**Comment by NTT1906** [comment]
I don't really sure. It works perfectly with other editor application, your not

**Comment by NTT1906** [comment]
My English is not really good, my grammar is suck

**Comment by NTT1906** [comment]
I don't know, i had tried to modify your application and when i use the modify one to code. The code is weird. It doesn't put the code where i tap
