### ISSUE TITLE
No longer able to type... at all.

### ISSUE THREAD

**Issue by NewSpectrum** [deadlyjack/Acode#480]
# Issue Details

## Summary:

As of yesterday, __8/12/2022__ (with the latest update), I'm no longer able to type in any way, no matter what I try- *except* in the command bar.

### Diagnostic Information:

|  Item/Title   | Specification    | Details |
| :-------: | :------ | :------ |
| <b>Device</b> | <br /><b>Device</b><br /><ol><li> Model Number  </li>   <li> Manufacturer  </li>   <li> OS Information  </li> <ul>   <li> Android Version  </li>   <li> Kernel Version  </li>   <li> One UI Version  </li> </ul>   <li> Hardware Version  </li></ol> | <br ><b>Galaxy Note 9</b><br /><ol><li> SM-N960U  </li>   <li> Samsung  </li>   <li> OS Information  </li> <ul>   <li> Android Version  </li>   <li> 4.9.186  </li>   <li> One UI v2.5  </li> </ul>   <li> REV1.1  </li></ol> |
| <b>Application</b> | <br /><b>Acode</b><br /><ol><li> App Version  </li>   <li> App Source  </li>   <li> Beta?  </li>   <li> Updated on:  </li></ol> | <br /><b>App Details</b><br /><ol><li> 1.6.0  </li>   <li> Google Play Store </li>   <li> No (but I want to be)  </li>   <li> 08/12/2022  </li></ol> |

<br />

## Example

https://user-images.githubusercontent.com/100762874/184490428-0229712a-a825-4e97-b2f5-ceceb4ac480c.MP4

<br />

### Remaining Input Options: Paste

That's it. All I can do now is paste from the top toolbar.

<br />

# Steps Taken

## Major Steps

1. Restarted phone
2. Forced app to shut down & stop via settings
3. Cleared app data & cache
4. Reinstalled app

<br />

## In-App

1. Attempted to change language syntax & file extension
2. Used command palette to invoke a variety of commands hoping one of them would activate the keyboard (obviously, no success there)
3. Used the Paste tool in the top toolbar. As mentioned above, this was successful.
4. Used 4 different keyboards (which had to be switched to externally):
    a. Microsoft Swiftkey
    b. Google Gboard
    c. Coding Keyboard
    d. Samsung Stock Keyboard
5. Attempted long-press & double-tap gestures
6. Opened multiple different files

**Comment by InsanePhin** [comment]
i'm having the same problem

Model : Samsung S10
Android : 12.1
App Version : 1.6.0 (202)

**Comment by InsanePhin** [comment]
But the update fixed it

It came up 9 hours ago

1.6.0 (203)

**Comment by NewSpectrum** [comment]
Yeah I just figured that out, but I had to download it from the pinned post in the Telegram chat. lol

[Telegram Chat Link](https://t.me/foxdebug_acode)

[Pinned APK Release Message](https://t.me/foxdebug_acode/62498)
