### ISSUE TITLE
[feature request] Git support?

### ISSUE THREAD

**Issue by griffi-gh** [deadlyjack/Acode#483]

**Comment by InsanePhin** [comment]
You can already pull files from git repositories and commit them

**Comment by griffi-gh** [comment]
> You can already pull files from git repositories and commit them

wait how? I have a local git repo and it doesn't show up anywhere

**Comment by griffi-gh** [comment]
What i do now it cd into the direcotry in termux and do git add/commit

**Comment by biraj21** [comment]
Acode doesn't have local Git support and there are no plans for it right now.  But as @InsanePhin said, you can connect with your remote repositories on GitHub by adding a PAT in Menu > GitHub.
![git](https://user-images.githubusercontent.com/37879496/186145376-e69ccc00-e2e1-4b29-bd1e-d4c51fe63b91.jpeg)
![github](https://user-images.githubusercontent.com/37879496/186145387-a1bd803f-0da4-4513-b6e6-add01a638a74.jpeg)

We are planning to add support for remote repositories that are hosted on platforms other than GitHub.
