### ISSUE TITLE
Acode is now junky SPAMware.

### ISSUE THREAD

**Issue by cubetronic** [deadlyjack/Acode#484]
ads? bubye.

**Comment by cubetronic** [comment]
oh, and version 1.6 from releases doesn't even work. had to get it from 3rd party.

**Comment by deadlyjack** [comment]
> ads? bubye.

Google Play clearly shows 'contains ads'. You are some random toxic and idiot human on the internet.

> oh, and version 1.6 from releases doesn't even work. had to get it from 3rd party.

Why get it from 3rd party if you don't like it?

**Comment by 14725** [comment]
Many just have no access to Google Play...
