### ISSUE TITLE
Code snippets not showing more

### ISSUE THREAD

**Issue by DarkLordRafa** [deadlyjack/Acode#486]
Code snippets for auto complete are not showing more after recent updates

![2022_08_14_09 47 18](https://user-images.githubusercontent.com/93549989/184537678-2d9345ac-142b-4355-afda-4b8d2e03b761.jpg)

**Comment by iTzVoko** [comment]
Are you still facing this problem?

**Comment by DarkLordRafa** [comment]
Yeah. And scroll still too fast while selecting text

**Comment by McJoe21** [comment]
It made coding easier

**Comment by iTzVoko** [comment]
> Yeah. And scroll still too fast while selecting text

Try to clear app data then tell me what happened

**Comment by DarkLordRafa** [comment]
> Try to clear app data then tell me what happen to your problem after this
I have checked older versions and tested, uninstalled and reinstalled, the last release from july 26th looks good for me, and i am using it now

**Comment by deadlyjack** [comment]
I removed it on purpose, soon there will be a plugin with better newer snippets.
