### ISSUE TITLE
[Bug] Capitalizing all words in strings

### ISSUE THREAD

**Issue by DarkCat09** [deadlyjack/Acode#488]
For example:  
In the menu (three points icon at the top right corner) I see "Open Recent" instead of "Open recent".  
There is "Editor Settings" instead of "Editor settings" on the main settings page.  
In "Go To Line" string ("Перейти К Строке" in Russian) Acode also capitalizes preposition "to" (just one letter "к" in Russian) which looks weird.

Acode: `1.6.0 (201)`  
WebView: `104.0.5112.69`  
OS: `RR 5.8.5 Android 7.1.2`

Maybe, I found a way to fix it. Look at the 27th line here: https://github.com/deadlyjack/Acode/blob/main/src/components/listItems.js#L27  
Function capitalize called with index 0, so only the first character should be uppercase, but capitalize(i) for unknown reasons is applied to the whole string.

```js
// strings.example.capitalize(0)
strings.example.charAt(0).toUpperCase() + strings.example.slice(1)

/* Or write a function */

const capitalize1st = (s) => return s.charAt(0).toUpperCase() + s.slice(1);
capitalize1st(strings.example)
```

**Comment by deadlyjack** [comment]
Hi, thanks for suggestion, I've implemented your suggestion, please wait for the update.
