### ISSUE TITLE
Make a Discord server

### ISSUE THREAD

**Issue by VenomousSteam81** [deadlyjack/Acode#492]
It would be cool to have a Discord support server.

**Comment by iTzVoko** [comment]
Actually there is a Telegram group for support [here](https://acode.foxdebug.com/help)

**Comment by biraj21** [comment]
We will see. If we create a Discord server, we will make it public. Till then as @iTzVoko  mentioned, you can join our [Telegram group](https://t.me/foxdebug_acode). You can also mail us at dellevenjack@gmail.com or raise a GitHub issue. Thank you.
