### ISSUE TITLE
Putting the app on f-droid repo.

### ISSUE THREAD

**Issue by 4mohamedaliii** [deadlyjack/Acode#494]
Since the app is OpenSource it should be on f-droid repo because people search for OpenSource apps there.

**Comment by iTzVoko** [comment]
> It should be on f-droid repo

Acode is already published [their](https://f-droid.org/packages/com.foxdebug.acode)

**Comment by 4mohamedaliii** [comment]
okay sorry.
Put I hope you put the link in readme.md next to Play store link.

**Comment by Indranil012** [comment]
> > It should be on f-droid repo
> 
> Acode is already published [their](https://f-droid.org/packages/com.foxdebug.acode)

But the last update was `Version 1.4.164 (164) - Added on 2021-10-12`

**Comment by deadlyjack** [comment]
#410
