### ISSUE TITLE
Cannot use Github

### ISSUE THREAD

**Issue by InsanePhin** [deadlyjack/Acode#498]
app version : 1.6.0 (211)

android 12
one ui 4.1

Literally i can't use the github feature.

**Comment by deadlyjack** [comment]
What features are you not able to use? How can I regenerate the issue? What is your device manufacturer and Android version?

**Comment by InsanePhin** [comment]
> What features are you not able to use? How can I regenerate the issue? What is your device manufacturer and Android version?


Phone Info

- Samsung S10
- Android 12
- One UI 4.1
- SM-G973N

App Info

- 1.6.0 (203)

It's an indefinite token, but it says it can't be used

![Screenshot_20220823-072033_Acode.png](https://user-images.githubusercontent.com/61483137/186029060-df961063-f463-422d-9f60-475868722a88.png)

**Comment by biraj21** [comment]
Are you sure that the token you are using is correct and it has permissions to access your repositories?

For testing, I created a token with the following permissions and I was able to log in and write to my repositories.
![Screenshot from 2022-08-23 17-14-45](https://user-images.githubusercontent.com/37879496/186150237-6508ac58-8a22-468b-8f4f-251950662e56.png)

**Comment by InsanePhin** [comment]
> Are you sure that the token you are using is correct and it has permissions to access your repositories?
> 
> For testing, I created a token with the following permissions and I was able to log in and write to my repositories.
> ![Screenshot from 2022-08-23 17-14-45](https://user-images.githubusercontent.com/37879496/186150237-6508ac58-8a22-468b-8f4f-251950662e56.png)
> 

The token I used is a super admin-like token with all privileges.

**Comment by InsanePhin** [comment]
I'll check the token some more

**Comment by InsanePhin** [comment]
I fixed it 
My token is hacked
