### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by axel358** [deadlyjack/Acode#499]
On some devices like my phone the text is somewhat blurry all the time. On my computer however the text looks good when u open a file but gets blurry as soon as u scroll down, sometimes u have to scroll up several lines for it to look normal again

**Comment by biraj21** [comment]
> On some devices like my phone the text is somewhat blurry all the time. On my computer however the text looks good when u open a file but gets blurry as soon as u scroll down, sometimes u have to scroll up several lines for it to look normal again

Can you share the screenshot?

**Comment by biraj21** [comment]
Can you share the screenshot?

**Comment by axel358** [comment]
Before
![normal](https://user-images.githubusercontent.com/72220889/186417773-16f57d80-a48b-41b3-83cf-ff8ad5f8203c.png)

After
![blurry](https://user-images.githubusercontent.com/72220889/186417909-d389fedf-cc40-43c4-8921-e3c69bb920ba.png)

I know it doesn't look like much of a difference but trust me there is. Specially when ure scrolling through the document looking for something it can be really painful to the eyes

**Comment by deadlyjack** [comment]
What device you are using? Is it google chrome OS i.e. Chromebook or Samsung DEX?

**Comment by axel358** [comment]
Just regular Android 7 for x86 on a 1366×768 Toshiba laptop
