### ISSUE TITLE
[feature request]: Option to set a default port for preview

### ISSUE THREAD

**Issue by rBok6** [deadlyjack/Acode#501]
It would be nice if you could add an option to allow the users to set a default port for the in-app preview. This would be useful when working Termux and Acode at the same time. I know you can edit the address on the preview but that's not a good user experience doing it every time. Here's an idea of how it could look. This sub menu could be shown while holding the preview button for a few secs.

![Screenshot_2022-08-23-12-57-43-14_e3c1f266f17b29c7b40472751f031275.png](https://user-images.githubusercontent.com/13161094/186223875-8de47719-fb88-476a-8b11-a95e5fb3d82b.png)

**Comment by deadlyjack** [comment]
Hi, thanks for suggestion, I've provided an option to set port number in app settings. Please wait for the update.

**Comment by rBok6** [comment]
So, it seems Acode can't use the same port as Termux since it changes to port 3001, if It's set to 3000 on custom setting. Also Acode
