### ISSUE TITLE
Changes to files using Git are not saved locally.

### ISSUE THREAD

**Issue by InsanePhin** [deadlyjack/Acode#505]
https://user-images.githubusercontent.com/61483137/186789667-f9f81e8d-d7fc-4847-ac95-dd487f4682a6.mp4

Changes cannot be saved as shown in the video above

**Comment by InsanePhin** [comment]
Phone Info

- Samsung S10
- Android 12
- One UI 4.1
- SM-G973N


App Info

- 1.6.0 (203)

**Comment by deadlyjack** [comment]
I've fixed this issue, wait for the update.

**Comment by InsanePhin** [comment]
Thanks 😊
