### ISSUE TITLE
Can't change search settings

### ISSUE THREAD

**Issue by mr-nfamous** [deadlyjack/Acode#511]
It isn't possible to do regex/case sensitive searches because as the following clip shows, changes to settings, even on a fresh install, have no effect/don't appear to be saved:

https://user-images.githubusercontent.com/24905627/187896953-a2652d07-e24b-4e57-9544-195682486d1a.mp4

That was recorded on Galaxy S10 (SM-G973U1), Android 12, package com.foxdebug.acode version 1.6.0 (whichever version of 1.6.0 it was added to play store 2022/08/31

**Comment by deadlyjack** [comment]
Update app to latest version i.e. 1.6.0 (224)

**Comment by mr-nfamous** [comment]
It still isn't fixed.

**Comment by mr-nfamous** [comment]
I created a backup and it looks like the issue is that the search option interface changes the values of whatever the "regexp" and "case sensitive" keys in the backup are based on instead of "regExp" and "caseSensitive", which the app actually uses. I.e. editing the value of "regExp" and "caseSensitive" to true in a backup file and then restoring will allow case sensitive regex search to work, as in:

    "search": {
                "caseSensitive": true,
                "regExp":true,
                "wholeWord":true,
                "backwards":true,
                "regexp":false,
                "case sensitive":false
            },`

**Comment by deadlyjack** [comment]
Thanks for the hint. This is dumb mistake from my side. I'll fix it.
