### ISSUE TITLE
[Theme Requesrt] Catppuccin

### ISSUE THREAD

**Issue by Vixeliz** [deadlyjack/Acode#513]
I'm not sure if theme request are allowed or not so feel free to close. However since I don't see any way to specifiy a custom theme I figured I'd ask. I think the addition of the catppuccin themes would be amazing as they are very nice to look at. Here is the github if you are interested: 
https://github.com/catppuccin/catppuccin

**Comment by deadlyjack** [comment]
You can customize theme in settings -> themes -> custom theme.

**Comment by Vixeliz** [comment]
My bad however i do notice one thing there appears to be no custom theme option for the editor itself or am I missing something?

**Comment by deadlyjack** [comment]
![Screenshot_2022-09-03-22-14-50-79_a2cf8efcdd42a8e6f7906303f104fb67.jpg](https://user-images.githubusercontent.com/38699939/188280325-2ae4e828-6632-428a-8b87-427d9ae9e0b0.jpg)

The selected item is  custom theme.

**Comment by Vixeliz** [comment]
Yes that's for the app though right? The editor tab has no custom theme.
