### ISSUE TITLE
[FEATURE REQUEST] Attach to running server with port number 

### ISSUE THREAD

**Issue by 3egle** [deadlyjack/Acode#517]
The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.

What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.

this can be achieved by just running the web view with string then append the port to the host ("http://127.0.0.1:{port}").

It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.

Thank you and keep up the good work i really enjoy using the app.

**Comment by vexymous** [comment]
I don't understand what do u meant with (attach)
How ever this feature it is available in the new version 1.6.0

u can find in the in Settings -> Preview Settings
And u can change things like (preview browser ,preview host, preview port)

to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)

I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve

**Comment by vexymous** [comment]
> The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> 
> What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> 
> this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> 
> It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> 
> Thank you and keep up the good work i really enjoy using the app.



> The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> 
> What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> 
> this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> 
> It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> 
> Thank you and keep up the good work i really enjoy using the app.

I don't understand what do u meant with (attach)
How ever this feature it is available in the new version 1.6.0

u can find in the in Settings -> Preview Settings
And u can change things like (preview browser ,preview host, preview port)

to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)

I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve

**Comment by 3egle** [comment]
> > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > Thank you and keep up the good work i really enjoy using the app.
> 
> > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > Thank you and keep up the good work i really enjoy using the app.
> 
> I don't understand what did u meant with (attach) How ever check this feature it is available in the new version 1.6.0
> 
> u can find in the in Settings -> Preview Settings And u can change things like (preview browser ,preview host, preview port)
> 
> to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)
> 
> I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve


No that is not what i meant. I mean running if i start a server on 8080 i want acode to just load the server.mean while acode starts a server a server on the allocated port.
I want it load the webserver like a normal browser

**Comment by vexymous** [comment]
> > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > Thank you and keep up the good work i really enjoy using the app.
> > 
> > 
> > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > Thank you and keep up the good work i really enjoy using the app.
> > 
> > 
> > I don't understand what did u meant with (attach) How ever check this feature it is available in the new version 1.6.0
> > u can find in the in Settings -> Preview Settings And u can change things like (preview browser ,preview host, preview port)
> > to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)
> > I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve
> 
> No that is not what i meant. I mean if i start a server on 8080 i want acode to just load the server.mean while acode starts a server on the allocated port. I want it load the webserver like a normal browser

I not sure that I'm following, are you sure from what are talking about, kuz it doesn't make any sense to me, can you dumb it more ?

**Comment by 3egle** [comment]
> > > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > > Thank you and keep up the good work i really enjoy using the app.
> > > 
> > > 
> > > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > > Thank you and keep up the good work i really enjoy using the app.
> > > 
> > > 
> > > I don't understand what did u meant with (attach) How ever check this feature it is available in the new version 1.6.0
> > > u can find in the in Settings -> Preview Settings And u can change things like (preview browser ,preview host, preview port)
> > > to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)
> > > I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve
> > 
> > 
> > No that is not what i meant. I mean if i start a server on 8080 i want acode to just load the server.mean while acode starts a server on the allocated port. I want it load the webserver like a normal browser
> 
> I not sure that I'm following, are you sure from what are talking about, kuz it doesn't make any sense to me, can you dumb it more ?


Alright. Let's assume we are working on a web project, basically we are using react, first we start the project with a command like (yarn dev), it start a server on localhost:3030. Now to view the running page we have to use a browser like chrome, but instead i we won't to use acode's built-in browser so i dont have to move back and forth from the browser.
So what i am asking is providing a place were to place the url (localhost:3030) and it is persistent (it doesn't reset as soon as soon i leave the view), and use Acode's built-in browser in place of chrome.

**Comment by vexymous** [comment]
> > > > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > > > Thank you and keep up the good work i really enjoy using the app.
> > > > 
> > > > 
> > > > > The option to choose local port is nice, and it will be more better to add an option to turn it off and rather attach to an already running server using the provided port.
> > > > > What i mean is that for example i start a dev server in termux running on port 8080 now if i tell Acode to run 8080 it won't because Acode also start a server but what i will wont it to do is attach to the already the already running server.
> > > > > this can be achieved by just running the web view with string then append the port to the host ("[http://127.0.0.1:{port}](http://127.0.0.1:%7Bport%7D)").
> > > > > It is possible to do this by editing the url in the browser but it is not persistent. Making it persistent is the core opinion here.
> > > > > Thank you and keep up the good work i really enjoy using the app.
> > > > 
> > > > 
> > > > I don't understand what did u meant with (attach) How ever check this feature it is available in the new version 1.6.0
> > > > u can find in the in Settings -> Preview Settings And u can change things like (preview browser ,preview host, preview port)
> > > > to achieve what I think u want is by changing the Preview port to ur server port in ur case (8080)
> > > > I Hope it was helpful, if not feel free to describe more what is it that u wanna achieve
> > > 
> > > 
> > > No that is not what i meant. I mean if i start a server on 8080 i want acode to just load the server.mean while acode starts a server on the allocated port. I want it load the webserver like a normal browser
> > 
> > 
> > I not sure that I'm following, are you sure from what are talking about, kuz it doesn't make any sense to me, can you dumb it more ?
> 
> Alright. Let's assume we are working on a web project, basically we are using react, first we start the project with a command like (yarn dev), it start a server on localhost:3030. Now to view the running page we have to use a browser like chrome, but instead i we won't to use acode's built-in browser so i dont have to move back and forth from the browser. So what i am asking is providing a place were to place the url (localhost:3030) and it is persistent (it doesn't reset as soon as soon i leave the view), and use Acode's built-in browser in place of chrome.

Apparently I've presented a solution for your issue, have u try it ?, like I mentioned earlier u can change the preview port and host to ur server's witch is in ur case localhost:3030, and evreytime u run ur acode web preview will load the localhost webpage on 3030, ofc u can open ur project in acode and editing it will kuze the project to change,  but if u meant (live view) of ur changes getting applied in real time, I think this is beyond the reach for now, due to the smartphones comparatively small screens, hope I got what u meant

**Comment by 3egle** [comment]
![Screenshot_20220913_131829](https://user-images.githubusercontent.com/61257646/189899627-17ca6ab3-19f3-46ee-8d18-610957b18b32.jpg)

![Screenshot_20220913_131838](https://user-images.githubusercontent.com/61257646/189899769-555a938f-cfa8-48bf-bbee-bb89cc352549.jpg)

![Screenshot_20220913_132046](https://user-images.githubusercontent.com/61257646/189899840-d09d660f-b245-46ee-a1be-f2bd11340df8.jpg)

![Screenshot_20220913_132505](https://user-images.githubusercontent.com/61257646/189900385-1f863e6a-e425-40aa-9493-b0015459afd6.jpg)

As you can see, 
- the first image i started a local server on 5193
- the second i set acode port to 5173
- the third after lunching the preview it started on 5174 because another server (my server) is running on 5173 so it automatcally started on 5174
- I have to manually change it in the url box to 5174 as you can see in the fourth image.

- so what i am asking is something like a check box that points "use this url for this project" so that when i close a preview the url still stands as i modified ealier
- I hope you understand me point now

**Comment by vexymous** [comment]
> ![Screenshot_20220913_131829](https://user-images.githubusercontent.com/61257646/189899627-17ca6ab3-19f3-46ee-8d18-610957b18b32.jpg)
> 
> ![Screenshot_20220913_131838](https://user-images.githubusercontent.com/61257646/189899769-555a938f-cfa8-48bf-bbee-bb89cc352549.jpg)
> 
> ![Screenshot_20220913_132046](https://user-images.githubusercontent.com/61257646/189899840-d09d660f-b245-46ee-a1be-f2bd11340df8.jpg)
> 
> ![Screenshot_20220913_132505](https://user-images.githubusercontent.com/61257646/189900385-1f863e6a-e425-40aa-9493-b0015459afd6.jpg)
> 
> As you can see,
> 
> * the first image i started a local server on 5193
> * the second i set acode port to 5173
> * the third after lunching the preview it started on 5174 because another server (my server) is running on 5173 so it automatcally started on 5174
> * I have to manually change it in the url box to 5173 as you can see in the fourth image.
> * so what i am asking is something like a check box that points "use this url for this project" so that when i close a preview the url still stands as i modified ealier
> * I hope you understand me point now

This version doesn't seem to be latest wich is 1.6.0
I can insure u that this problem has been fixed, u need to make sure that u have the latest version from the google play store.

![Screenshot_20220913-200720_Acode](https://user-images.githubusercontent.com/89711077/189988822-5e4a1832-7e47-44a0-a00f-f3d2fdffcd8f.jpg)

![Screenshot_20220913-200730_Acode](https://user-images.githubusercontent.com/89711077/189988908-8a76a6bb-9b8b-42bc-abc0-1a29f08bd3c3.jpg)

As u can see here the preview port remains **8080** even though the server started on **8088**, if the problem didn't get fixed you can change the server port to **1** since it needs root permission for that, the server won't run, now if ur problem is about that it doesn't load the **index.html** file and u have to type everytime the **host:port/index.html** that's something u have to set up ur server to do for u, it needs to forward all requests to **/index.html** so that the evreytime u call the **host:port** it loads the **/index.html** as the default ### path

**Comment by 3egle** [comment]
alright I was using a less version. thanks alots
