### ISSUE TITLE
Acode 1.6.0 not opening (stalls when initializing Github?)

### ISSUE THREAD

**Issue by e-t-l** [deadlyjack/Acode#523]
After updating to v1.6.0 (from F-droid), Acode will not start. The app opens, says, "Initializing Github," for a few moments, then says, "This is taking unexpectedly long time!" Acode fails to progress past this point, even after force-quitting the app and clearing the app cache.

EDIT: I just noticed there's two v1.6.0s on F-droid, v1.6.0 (231) uploaded on 9/14/22, and v1.6.0 (212) uploaded on 9/2/22. I encountered this on the latest version, (231), but I haven't yet downgraded to (212) to check if the issue persists there.

Running Android 12 on Google Pixel 3

**Comment by c-key** [comment]
Same in Android 13 (GrapheneOS) in Google Pixel 4a

**Comment by deadlyjack** [comment]
Can i get a few more details on this issue?

1. What is device default language?
2. Was it a fresh install or update?
3. Have tried clearing app data?
4. Device android version and manufacturer
5. Which is the last version that worked on your device?

 Thanm you for reporting the bug.

**Comment by e-t-l** [comment]
Default language English
Update (via F-Droid) 
Had not cleared app data, only cache*
As mentioned, Android 12 on Google Pixel 3
v1.6.0 (212)

*I uninstalled Acode then reinstalled v1.6.0 (212), and it worked. So I updated immediately to v1.6.0 (231), and as of right now it ALSO works.

So, basically what I have done (fresh install) is equivalent to if I had just wiped App Data. Soooo not sure what this means; maybe something about personalized settings, open files, etc. get corrupted when updating from one version to the next?

**Comment by c-key** [comment]
1. Default language English
2. Update (via F-Droid)
3. Have neither deleted app data nor the cache
4. As mentioned, Android 13 (GrapheneOS) on Google Pixel 4a
5. 1.4.164

I wouldn't delete the cache or app data, because I want to keep the data in the opened last file.

**Comment by pyramid3d** [comment]
1 EN
2 update f-droid
3 deleted cache only (after update)
4 Android 12
5 1.4.164

**Comment by deadlyjack** [comment]
@c-key try the latest version from telegram group.

**Comment by c-key** [comment]
@deadlyjack I habe bo Telegramm and I don't know, how I can download the version you meant. Is there another way?

**Comment by deadlyjack** [comment]
If can't access telegram (t.me/foxdebug_acode) what for it to be published on f-droid or play store.

**Comment by apokaliptis** [comment]
I'm also experiencing this, even after clearing cache and data and redownloading the app. Strangely enough, the free version with ads launches fine.

**Comment by apokaliptis** [comment]
I uninstalled the paid version of Acode v1.6.0 (235) and installed version off F-Droid, v1.6.0 (231), and it launches fine. As mentioned above, the ad supported Acode v1.6.0 (235) also works.
