### ISSUE TITLE
Text Wrap Option

### ISSUE THREAD

**Issue by pyramid3d** [deadlyjack/Acode#528]
In the latest build version 1.6.0 (231) there is no editor option for toggling text wrap, while the previous version 1.4.164 still had this option.
As I am frequently toggling between markdown files (no text wrap needed) and source code files (text wrap necessary), I request for this option to be available in the text editor either through the Settings/Editor menu or as a configurable key shortcut command (or both).
I also added this a similar suggestion for the quick tools in issue #393 (https://github.com/deadlyjack/Acode/issues/393#issuecomment-1225600674)

Cheers, keep up this great tool!

**Comment by deadlyjack** [comment]
Hi, thanks for reporting but text wrap settings is available in settings 👉 editor settings 👉 scroll settings 👉 text wrap.

**Comment by pyramid3d** [comment]
Oops, there it went and me didn't find :-?
Thanks for the quick feedback!

**Comment by C-O-D** [comment]
Sorry for referring to this again but would it be possible to place the text wrap option somewhere where it's accessable more quickly? Since I'm toggling this a lot it would be MUCH more convenient...

**Comment by pyramid3d** [comment]
Hi @C-O-D,
I also added this a similar suggestion for the quick tools in issue https://github.com/deadlyjack/Acode/issues/393 (https://github.com/deadlyjack/Acode/issues/393#issuecomment-1225600674)
