### ISSUE TITLE
[FEATURE REQUEST] Moving text cursor with volume buttons

### ISSUE THREAD

**Issue by mrsobakin** [deadlyjack/Acode#529]
A useful feature, surprisingly many code editors lack. It would make editing much easier, especially on phones.

Perhaps it can be implemented via plugin? Moving the text cursor is easy, but I'm not sure how to catch volume button press events.

Thank you.

**Comment by deadlyjack** [comment]
Thanks for your suggestion. I've created the plugin. You can install it from settings, plugins.
