### ISSUE TITLE
Can't open UTF8 linux (log) files

### ISSUE THREAD

**Issue by Micha-he** [deadlyjack/Acode#536]
I can't open UTF8 Linux log files, not local or remote. Another editor can!

![Screenshot_20220926-230634](https://user-images.githubusercontent.com/36689516/192382054-a0b29b8d-2bea-4cc4-b330-075e791cee38.png)

**Comment by deadlyjack** [comment]
Hi, can you share a demo file to test?

**Comment by Micha-he** [comment]
Here's my logfile:

[Enigma2-debug-20220926_17-10-48.log](https://github.com/deadlyjack/Acode/files/9651438/Enigma2-debug-20220926_17-10-48.log)

**Comment by deepkrg17** [comment]
This log includes the Esc (\x1B) character. So Acode is taking it as Binary.
Acode doesn't opens that files which include => \x00 - \x08 and \x0E - \x1F characters.

**Comment by deepkrg17** [comment]
This log includes the Esc (\x1B) character. So Acode is taking it as Binary.
Acode doesn't open that files which include => \x00 - \x08 and \x0E - \x1F characters.

**Comment by pkiff** [comment]
I ran into this problem too. Trying to read a log file from a current, standard cPanel install. These are the log files that get sent by cPanel when there is an update. Not being able to open this file is a serious issue for me.

Are you saying that cPanel is generating log files with incorrect or invalid headers? All the other various code editors I have open them okay. Is there any possibility that Acode maybe needs to modify its file identification algorithm?

**Comment by deadlyjack** [comment]
@Micha-he thanks for the file. I'll fix it.

**Comment by deepkrg17** [comment]
@deadlyjack This is fixed now.
