### ISSUE TITLE
Stuck on launching  screen

### ISSUE THREAD

**Issue by apokaliptis** [deadlyjack/Acode#543]
I'm trying to run Acode on my phone but it keeps getting stuck on “Initializing Github...” followed by “This is taking unexpectedly long time!” I tried restarting my phone, redownloading the app, deleting the cache, etc.; all to to no avail.

This is my favorite code editor on Android so far, so I really hope to get it working again.

Acode v1.6.0 (235) Ad Free Edition
Android 13
Pixel 6

**Comment by apokaliptis** [comment]
I just downloaded the free version and it seems to be working fine. The issue I'm experiencing seems to only affect the ad free version I paid for.

**Comment by apokaliptis** [comment]
Duplicate of #523. Closing.

**Comment by hamadzidani** [comment]
how to speedup launching because it shows "loading...(stuff)"?

**Comment by apokaliptis** [comment]
> how to speedup launching because it shows "loading...(stuff)"?

You should open a new discussion or open a new issue for your problem rather than asking this in a closed issue. It's very unlikely that you'll get an answer to your question by commenting on a closed issue.
