### ISSUE TITLE
External keyb often not working in landscape mode

### ISSUE THREAD

**Issue by goyalyashpal** [deadlyjack/Acode#556]
Hi!

* The `com.foxdebug.acode,231,1.6.0` via fdroid is not recieving inputs from external keyboard in landscape mode. The white bar which appears at bottom is not appearing consistently here.
* It was working earlier, then i used the find feature, then that white bar stopped appearing persistently (i.e. it appears, then immediately disappears).
* ... it is not working ever since, even after weeks
* Following is the screenrecording of the bug:

https://user-images.githubusercontent.com/19423063/197320692-d82b6495-b77d-4b53-bfc3-58b88fb4f343.mp4

https://user-images.githubusercontent.com/19423063/197320702-b53b627e-31ed-4134-83e9-b2e9809d6a7d.mp4

**Comment by yashpalgoyal1304** [comment]
related issue: maybe https://github.com/deadlyjack/Acode/issues/156

**Comment by yashpalgoyal1304** [comment]
ping @deadlyjack
