### ISSUE TITLE
eslint not working in PRO version 

### ISSUE THREAD

**Issue by legend-sabbir** [deadlyjack/Acode#557]
eslint , syntax error check not working in PRO version(238) . Downloaded plugin and restarted acode , did all stuff but not working please consider fixing it . Thanks!

**Comment by deadlyjack** [comment]
Please can you share more details about this issue, like an screenshot or screen recording

**Comment by legend-sabbir** [comment]
https://user-images.githubusercontent.com/105509363/198414194-faa91b98-b2b1-4556-a636-ff44ed8638de.mp4

I cleared data before recording . It is not showing any error as you can see . Need any more details

**Comment by deadlyjack** [comment]
Please share details about your device and app version code.

**Comment by legend-sabbir** [comment]
Device: Huawei y9 2019
Android version: 9.1.0
Acode version: Pro 1.6.0(239)

**Comment by bajrangCoder** [comment]
Checkout other LSP plugin
