### ISSUE TITLE
Html: shouldn't format text inside <pre>

### ISSUE THREAD

**Issue by inspir3dArt** [deadlyjack/Acode#56]
The pre tag defines preformatted text. Text in a pre element is displayed in a fixed-width font, and the text preserves both spaces and line breaks. I use it, for example, to surround a code element with it, when I wanna display a code block. 

The Format feature of acode is currently reformatting text inside of pre. That makes it really hard to work on HTML documents that contain things like code snippets.

**Comment by deadlyjack** [comment]
Hi, in next version I'll use better formatter for HTML, JavaScript and CSS
