### ISSUE TITLE
Please somone response. How to add snippets?

### ISSUE THREAD

**Issue by ahmedrabbiff** [deadlyjack/Acode#562]
![Screenshot_20221104-071837](https://user-images.githubusercontent.com/99005852/199864635-ebb9f936-c16c-489b-b373-6d0b985c9fe1.jpg)
Here he said that, open command palette to set snippets . Where i can found command palette?

**Comment by TysonOS** [comment]
![Screenshot_20221105-220711](https://user-images.githubusercontent.com/88590347/200149725-3958e107-8fa0-4a57-85a5-83b9815e0456.png)
You can use this button or the F1 key

**Comment by deadlyjack** [comment]
Use CTRL-SHIFT-P for command palette. Or go settings, search keybindings and update your keyboard shortcuts.
