### ISSUE TITLE
Cursor move not working with app: Simple Keyboard

### ISSUE THREAD

**Issue by NaCl-5844** [deadlyjack/Acode#563]
### Setup
Keyboard App: https://github.com/rkkr/simple-keyboard
Source: f-droid
Settings in keyboard app:  Preferences > Space swipe cursor move

### Issue with Acode:
Acode can track the correct cursor position but doesn't update the screen until a character is pressed. 
E.g:
[ '|' == cursor ]

1) Type: "hello world|"
2) Scroll back to start:  "hello world|" 
3) Type x: "x|hello world"

I love this app but hate not using my fave keyboard, hope there's a possible fix <3

**Comment by RaSan147** [comment]
Same for Gboard

**Comment by deadlyjack** [comment]
Have you tried it after change keyboard settings to no suggestion?
