### ISSUE TITLE
Add node.js compiler and yarn or npm 

### ISSUE THREAD

**Issue by Aluwi21** [deadlyjack/Acode#565]
Please add node.js compiler and yarn/npm it will help to testing my project.

**Comment by feri-irawan** [comment]
Hi bro, you can use Termux app and install Node js, npm and yarn there.

```
$ pkg install nodejs-lts
$ npm i -g yarn
```

**Comment by Aluwi21** [comment]
> Hi bro, you can use Termux app and install Node js, npm and yarn there.
> 
> ```
> $ pkg install nodejs-lts
> $ npm i -g yarn
> ```

but npm can't be used, because im using android 11 and the android 11 does not allow the user to access the entire storage

**Comment by JavesBastatas** [comment]
You can access storage in Termux using `termux-setup-storage` command. More details can be found in [Termux Wiki](https://wiki.termux.com/wiki/Internal_and_external_storage).
___
I like the suggestion though. Having in-app nodejs in Acode Editor is handy. But it could be unnecessary feature when you can just use a dedicated tool for that, a terminal like Termux.
