### ISSUE TITLE
Auto Complete appends the text you typed before you selected a 'completion'

### ISSUE THREAD

**Issue by Josh-Reimer** [deadlyjack/Acode#569]
Acode's autocomplete feature appends whatever you were typing before you selected one of its 'guesses'.
For example, you are trying to type the keyword 'open'. You type 'op' and Acode guesses a few different keywords of which one is 'open'. You tap on the suggestion and Acode applies it. Then, you begin typing parenthesis or something, and it adds 'op' right before what you just, just typed. 

My device is an ancient Samsung Galaxy A5(2017) running Android Oreo 🙁.

You can reproduce this bug by following my example above.

**Comment by bajrangCoder** [comment]
It's not anymore

**Comment by Josh-Reimer** [comment]
Awesome
