### ISSUE TITLE
[Bug]: Plugins not loading

### ISSUE THREAD

**Issue by deepkrg17** [deadlyjack/Acode#574]
After the update of Plugins API, plugins are not loading in Acode.
### Bug :
Checked the data folder and found that the main files are not downloaded, they are of 0 bytes.
Maybe `fsOperation(Url).readFile()` is not working perfectly.
https://github.com/deadlyjack/Acode/blob/main/src/lib/installPlugin.js#L36-L38

**Comment by deadlyjack** [comment]
Thanks for the help. I've fixed it.
