### ISSUE TITLE
Error opening plain text file

### ISSUE THREAD

**Issue by danboarder** [deadlyjack/Acode#575]
Can't open a plain todo.txt file, getting a "Cannot open binary file" . I sync text notes to Atom editor on a Mac using Dropbox and it's worked fine before.  Using Pixel 6 Pro, Android 13. Acode 1.6.0 (239). I've noticed this issue with some .txt files while many others still open fine. 
![Screenshot_20221124-011135](https://user-images.githubusercontent.com/418939/203746020-b36e4454-04fc-4179-a8f1-83894efaec0d.png)

Another note - I am able to open the problem todo.txt file in another Android text editor quickedit on the same device without issue.

**Comment by deadlyjack** [comment]
#536
