### ISSUE TITLE
Feature request: Include NoName Fixed as a font option 

### ISSUE THREAD

**Issue by bgo-eiu** [deadlyjack/Acode#591]
NoName Fixed is an open source monospace font for Arabic script which has better character support than most generic monospace fonts. It also maintains distinctions between characters which are not made in all monospace fonts; for example, the font used on GitHub makes certain distinct letters look exactly the same. This can cause a lot of confusion. The font may be found here: https://github.com/aliftype/noname-fixed

Due to Arabic text being cursive, it is hard to read if fonts are mixed. Ideally this font could be applied as the default for all characters in the Unicode blocks for Arabic and its extended alphabets.

**Comment by bajrangCoder** [comment]
You can add it through plugin
