### ISSUE TITLE
Closing Brackets

### ISSUE THREAD

**Issue by amnesia-m4x** [deadlyjack/Acode#595]
Normally, when typing in a bracket "{", the app automatically closes it. However, this will not work if a closing bracket already exists. For example, when I type in in Java: 
class Test {
    pubilc void func() { _<- here the Bracket won't close..._
} _<- ... because of this bracket_

With the on-screen keyboard, you can close the bracket manually, but I use a physical keyboard and if I type the closing bracket, it would hide the content between that open bracket and the next closed bracket. 

It would be like this:
class Test {
    pubilc void func() { <-> }

And there is no other way to close this bracket than to disconnect the physical keyboard to close it manually with the on-screen keyboard. 

I think it would be enough to remove the function as a shortcut from the physical keyboard.
(hiding stuff after pressing "Alt Gr + }")

**Comment by rBok6** [comment]
Doesn't it close when you hit enter? That works for me, at least with touch keyboard.

**Comment by amnesia-m4x** [comment]
It works with the touch keyboard. But I'm using a physical keyboard and when I type the "}" after the open bracket the content between the open bracket and the next closed bracket becomes hidden.

**Comment by amnesia-m4x** [comment]
Yes. I tried both Windows and Unix and got the same issue.
