### ISSUE TITLE
Bug in renaming github file

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#610]
See some images: 

![Screenshot_20230109-115649](https://user-images.githubusercontent.com/101356556/211341512-b52c826a-b467-4842-8191-69ce9efe1f03.jpg)

![Screenshot_20230109-120738](https://user-images.githubusercontent.com/101356556/211341523-15f11743-be88-4964-a18a-bcaa235adfab.jpg)

![Screenshot_20230109-120754](https://user-images.githubusercontent.com/101356556/211341526-a55a9536-544c-48c8-80d1-7a2429480e37.jpg)

![Screenshot_20230109-120801](https://user-images.githubusercontent.com/101356556/211341519-771c7f1e-721c-4b62-bece-f2df13f6c438.jpg)

**Comment by sebastianjnuwu** [comment]
@deadlyjack Any predictions for the resolution or not at all?

**Comment by kyoyacchi** [comment]
I'm having same issue.

**Comment by sebastianjnuwu** [comment]
> I'm having the same issue. @deadlyjack can you check this out?

he even solves problems quickly, but unfortunately he doesn't interact with people here lately :/

**Comment by deadlyjack** [comment]
Hi, I am so sorry for the issue. I'll fix it as soon as possible. I don't know why it's not working. I've tried multiple time to fixed but it helped. I'll try again soon. Thank you for reporting it.
