### ISSUE TITLE
After last update 1.7.0 paid version wont start

### ISSUE THREAD

**Issue by fuss** [deadlyjack/Acode#612]
Hello! After last update 1.7.0 paid version wont start. I tried clean install but after the permission request - endless download with the logo "A".
Samsung A03, android 12.

**Comment by deadlyjack** [comment]
Please share version code.

**Comment by fuss** [comment]
after the last update13.01.2022 the program is already running

**Comment by deadlyjack** [comment]
share screen recording please

**Comment by fuss** [comment]
I'm already updated app to version 1.7.0 (**262**). Last update at google play market works fine. And i can't record previous bug. Maybe issues was **261** version. So issues not actually.
