### ISSUE TITLE
After last update 1.7.0 paid version Search button missing from toolbar

### ISSUE THREAD

**Issue by RaSan147** [deadlyjack/Acode#613]
the search bar is now only visible on the pen icon menu

and the search button is replaced by `esc` button

**Comment by RaSan147** [comment]
![Screenshot_2023-01-17-20-02-35-67](https://user-images.githubusercontent.com/34002411/212918932-d40bac08-aaf9-4127-bb28-9e1244fb97c0.jpg)

Can you replace these buttons with Search and Ctrl button?

**Comment by bajrangCoder** [comment]
Check edit menu (pencil icon) at top , you can find `Search` option there.

![InShot_20230119_070043996](https://user-images.githubusercontent.com/71929976/213334463-1d5ba4d9-de16-4bb4-bfb4-eabbfeac5954.jpg)

**Comment by RaSan147** [comment]
@bajrangCoder i know where to find it, but its handy to keep the search button near keyboard, going there every time to search is painful

**Comment by RaSan147** [comment]
Fixed it for myself
