### ISSUE TITLE
Weird Cursor behaviour.

### ISSUE THREAD

**Issue by adr420** [deadlyjack/Acode#614]
### Issue
Weird cursor behaviour.

### Description
Quick tools trigger mode is set to `click`.

I clicked ⟨ button (continuously) and then ⟩ and the cursor started moving uncontrollably.

This may be happened by chance but it can be fixed.

### Fix
As soon as ⟩ button is clicked the ⟨ should stop its function 

OR

It seems (i have not seen the code) the buttons are working in a asynchronous way (click response is somewhat delayed) making them synchronous would be fix and a nice thing to do.

**Comment by adr420** [comment]
https://user-images.githubusercontent.com/69690253/212467835-2b857387-8f51-4914-8d26-385fec10625c.mp4

**Comment by deadlyjack** [comment]
App version code?

**Comment by adr420** [comment]
Acode 1.7.0(260)

**Comment by RaSan147** [comment]
Could you try using a different keyboard other than Gboard?
Try this one: https://play.google.com/store/apps/details?id=yellowtech.simplekeyboardwithemojis.inputmethod
Gboard often mess with coding apps

**Comment by adr420** [comment]
The problem seems to be solved now...
