### ISSUE TITLE
FUNCTIONALITY TIPS 

### ISSUE THREAD

**Issue by fera765** [deadlyjack/Acode#631]
Hi, I really like the project, and it would be interesting to add the ctrl button to the shortcuts.

Another tip would be to add support for the vs code extension would be awesome.

**Comment by griffi-gh** [comment]
support for vscode extensions is just impossible

**Comment by RaSan147** [comment]
> support for vscode extensions is just impossible to implement.

yet the author managed to create extension support (i thought it was impossible too😅)

**Comment by griffi-gh** [comment]
extension support is fairly easy to implement in an app like this.  
vscode extensions will never this is just ridiculous
