### ISSUE TITLE
error when uploading a plugin

### ISSUE THREAD

**Issue by devguts** [deadlyjack/Acode#633]
it happens to any plugin I try to upload, please fix it

![Screenshot_2023-01-24-15-56-47-308_com android chrome](https://user-images.githubusercontent.com/123426723/214383669-fb1a2ba3-3f37-4c16-b1d0-24d88d134b8f.jpg)

**Comment by deadlyjack** [comment]
share that plugin at acode@foxdebug.com so I can try it myself. Thanks cor reporting it. ☺️

**Comment by deadlyjack** [comment]
share that plugin at acode@foxdebug.com so I can try it myself. Thanks cor reporting it. ☺️


readme.md should be in lowercase.

**Comment by devguts** [comment]
here it is

https://www.mediafire.com/file/681mhai8u4cfc9d/colory-acode-plugin%25283%2529.zip/file

Em ter., 24 de jan. de 2023 17:12, Ajit Kumar ***@***.***>
escreveu:

**Comment by devguts** [comment]
i think its all good now

Em ter., 24 de jan. de 2023 17:31, Guts ***@***.***> escreveu:

**Comment by bajrangCoder** [comment]
Same zip file i had tried it's uploading.

With proper internet connection try again....

**Comment by devguts** [comment]
here it is the plugin with readme.md in lowercase
https://www.mediafire.com/file/0uwflclagcem31h/plugin.zip/file

Em qua., 25 de jan. de 2023 08:52, Raunak Raj ***@***.***>
escreveu:
