### ISSUE TITLE
[Plugin request] Backets pair colorizer

### ISSUE THREAD

**Issue by rBok6** [deadlyjack/Acode#635]
Hello, I was wondering if it could be possible to add Brackets pair colorizer to Acode plugins. I really like this plugin and it's very useful for almost any programing language.

Here's the source to one of the most popular projects: [Brackets Pair colorizer](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2)

**Comment by RaSan147** [comment]
Instead of plug in, requesting to make it default? It would be really helpful (specially detecting if the bracket is closed or not.

**Comment by rBok6** [comment]
Yeah that's also a good idea 👏🏻👏🏻

**Comment by bajrangCoder** [comment]
Already available through plugin
