### ISSUE TITLE
issues with jumping back to the top of a file after scrolling

### ISSUE THREAD

**Issue by tigersmith12** [deadlyjack/Acode#641]
if you open a file and scroll down to where you want to edit once you click then grab the cursor to move where you will start typing it will do 1 of 2 things crash or jump back to the top where you was last

i have a android 13 Samsung galaxy 21ultra

im not sure how to give you logs or a dump if you could inform me how to do so i can provide those

**Comment by RaSan147** [comment]
Its a bit wierd stuff, imo what happens there is
The cursor remains in the top, we scroll down using slider, then when we try to scroll using normal swipe.
The app thinks that we are still in the cursor position and scrolls from that point. *Thats the bug*

Also additional info about slider, sometimes slider suddenly vanish from vartical line and create a useless horizontal slider at bottom. Scrolling fix this but still a bug tho

**Comment by deadlyjack** [comment]
Hi, thanks for reporting this. It's already known to me, and am looking for a way to fix it.
