### ISSUE TITLE
SFTP Doesn't work with Windows

### ISSUE THREAD

**Issue by VinkyV** [deadlyjack/Acode#647]
Acode can't connect to windows OpenSSH Server via SFTP, it says Operation not permitted.
![Screenshot_20230210-020334_Acode](https://user-images.githubusercontent.com/75137786/217958763-5c6da447-a8a7-42e5-bba2-69b5779da403.jpg)

**Comment by deadlyjack** [comment]
Can you share configuration so I can test it myself. Thank you 😊

**Comment by VinkyV** [comment]
I used default Windows OpenSSH Server in Windows Components

**Comment by VinkyV** [comment]
Without any configuration
