### ISSUE TITLE
How do I open Command Pallete?

### ISSUE THREAD

**Issue by SamJones04** [deadlyjack/Acode#650]
I want to clone a repository, how can I see the command Pallete

**Comment by sebastianjnuwu** [comment]
It is not possible to clone a repository just open it using the github plugin download and in the command palette write "open repository" put your token there and choose your repository ok?

**Comment by deadlyjack** [comment]
Go to settings, app settings, key bindings, search pallete. change key bindings to ctrl-shift-p

**Comment by Jetrom17** [comment]
> Go to settings, app settings, key bindings, search pallete. change key bindings to ctrl-shift-p

Make a change here about this.

https://acode.foxdebug.com/faqs/13388599490

Please.
