### ISSUE TITLE
[BUG] Wrong php blade file syntax highlighting

### ISSUE THREAD

**Issue by mortezaDev9** [deadlyjack/Acode#655]
![Screenshot_20230225-163828_Acode.jpg](https://user-images.githubusercontent.com/113019884/221358784-d01a03d4-7b6b-447b-a8c4-3093fb4c0cd5.jpg)

And when I change the syntax highlighting for a blade file to php_laravel_blade, all the new files get created with .php extension will set to php_laravel_blade not  php.

Please fix it, it's really annoying.

**Comment by bajrangCoder** [comment]
Actually there is no highlighting for balde , either wait for any plugin dev to develop it or check ace editor repo
