### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by colin-walker** [deadlyjack/Acode#660]
Since updating to v1.8.0 (272) I am getting an error on startup:

`undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

I can dismiss it and everything seems to work fine.

I have the Lint and GitHub plugins installed if that helps to troubleshoot.

**Comment by deadlyjack** [comment]
working on it.

**Comment by colin-walker** [comment]
Fixed in 1.8.1

Thanks 😊
