### ISSUE TITLE
Disable Line Wrapping

### ISSUE THREAD

**Issue by AKNoryx28** [deadlyjack/Acode#662]
Hi, how can i disable line wrapping? does that setting already exist?
I also have a suggestion to add a zoom in/out code editor feature with two fingers

**Comment by partlyblue** [comment]
The line wrapping setting is under: Editor Setting > Scroll Settings > Text wrap

The zoom in/out feature seems neat.

**Comment by Rudxain** [comment]
> Editor Settings > Scroll Settings > Text wrap

I wish it was moved out of scroll settings
