### ISSUE TITLE
Unable to access folder via FTP

### ISSUE THREAD

**Issue by colin-walker** [deadlyjack/Acode#672]
In 1.8.1 I've started getting an error when trying to open a specific folder:

> Attempt to invoke virtual method "long
java.util.Calendar.getTimelnMillis()" on a
null object reference

I can access that folder via any other FTP app.

I can access any other folder fine just just this one folder gives the error.

**Comment by colin-walker** [comment]
Issue has randomly stopped. Not sure what's going on.

**Comment by sebastianjnuwu** [comment]
This error occurs because the Calendar class does not have a method called "getTimelnMillis()". The correct method is "getTimeInMillis()". So if the code is calling the wrong method, it won't be found and will throw an error.

**Comment by sebastianjnuwu** [comment]
I suggest you always leave your app up to date and close the issue as it no longer occurs to you.

**Comment by colin-walker** [comment]
Agreed. Closing for now.
