### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by jianjianxu** [deadlyjack/Acode#673]
I run `cordova platform add android`, it showed:
```
Using cordova-fetch for cordova-android@^10.1.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.foxdebug.acode
        Name: Acode
        Activity: MainActivity
        Android target: android-31
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.2
ENOENT: no such file or directory, open '/works/Acode/platforms/android/app/src/main/java/org/apache/cordova/file/FileUtils.java'
```
I run `yarn build android paid prod`, it also showed:
```
ENOENT: no such file or directory, open '/works/Acode/platforms/android/app/src/main/java/org/apache/cordova/file/FileUtils.java'
```
then I run `cordova build android --release`, it showed:
```
ENOENT: no such file or directory, open '/works/Acode/platforms/android/app/src/main/java/org/apache/cordova/file/FileUtils.java'
```

**Comment by RaSan147** [comment]
I manually added the file plugin after cordova add platform android. Working fine now

https://github.com/deadlyjack/Acode/pull/659/commits/1fbdd5ee0e2cf0d145d0440cc3ade1375c68883a

**Comment by jianjianxu** [comment]
Thank you

**Comment by deadlyjack** [comment]
You need to install the cordova plugins. Have you ran npm install?

**Comment by jianjianxu** [comment]
I have installed cordova by npm. Maybe the reason is the java opensdk？

**Comment by RaSan147** [comment]
> You need to install the cordova plugins. Have you ran npm install?

I also tried, it was right in the package.json, still didn't get why either it wasn't being installed or not being visible.
Installing via cordova (after adding cordova android) did work.
