### ISSUE TITLE
Menu panel sticks after being scrolled horizontally (usually mistakenly)

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/Acode#675]
The menu containing files and folders sticks as in the image below:
![IMG_20230401_093413](https://user-images.githubusercontent.com/34959120/229275741-76529913-3190-4b55-a1b1-26102573982d.jpg)

This happens if I mistakenly scroll the menu bar horizontally when files are open. It always occurs, and you can reproduce it.

At this point nothing can close it, you'll have to restart Acode to be able to work again.

**Comment by deadlyjack** [comment]
Can you share a screen recording? I'm unable to reproduce it.

**Comment by PatAbah** [comment]
Okay, I've made the screen record. Your finger has to be on the menu's
scroll bar while scrolling horizontally to reproduce it.

**Comment by PatAbah** [comment]
Okay, I've made the screen record. Your finger has to be on the menu's scroll bar while scrolling horizontally to reproduce it. 
👇
https://user-images.githubusercontent.com/34959120/230795195-87c75468-ca8d-41b0-99aa-1f4551d7f634.mp4

**Comment by PatAbah** [comment]
> Can you share a screen recording? I'm unable to reproduce it.

Okay, I've made the screen record. Your finger has to be on the menu's scroll bar while scrolling horizontally to reproduce it.
👇

https://user-images.githubusercontent.com/34959120/230795218-049ec09d-83b2-42d6-a1a3-2ea3f4f3ccc7.mp4

**Comment by deadlyjack** [comment]
Okay, it seems weird, can you share what's the inner Width of your device? To get innerWidth, open console, type innerWidth, you'll get a number, send it to me.

**Comment by PatAbah** [comment]
> Okay, it seems weird, can you share what's the inner Width of your device? 
393

**Comment by PatAbah** [comment]
> Weird, do you use some kind of plugin? The file manager icon (beside plugins) isn't blue 🟦 normally (tried different theme, still not showing blue)

It's the GIT Dust theme I think. It doesn't affect this glitch though. The menu thing happens irrespective of any theme plugin.

**Comment by PatAbah** [comment]
Currently using v1.8.7, I no longer face the issue.

**Comment by PatAbah** [comment]
Closing.

**Comment by PatAbah** [comment]
Hi. I noticed that an auto withdrawal was placed on my account on 09 Aug
2025, of ₹1,076.23.

I've changed my withdrawal option from PayPal to crypto as I doubt my
PayPal account ***@***.***) has the ability to receive rupees.

ID like the payment request canceled and he money returned to balance, or
the money sent to my chooses crypto wallet if possible.

Thank you.
User id: 208

**Comment by bajrangCoder** [comment]
> Hi. I noticed that an auto withdrawal was placed on my account on 09 Aug
> 2025, of ₹1,076.23.
> 
> I've changed my withdrawal option from PayPal to crypto as I doubt my
> PayPal account ***@***.***) has the ability to receive rupees.
> 
> ID like the payment request canceled and he money returned to balance, or
> the money sent to my chooses crypto wallet if possible.
> 
> Thank you.
> User id: 208

Please note: The transaction will be processed to your designated new default crypto account in the coming month.
