### ISSUE TITLE
Can't scroll toolbar

### ISSUE THREAD

**Issue by 1Code-0** [deadlyjack/Acode#676]
https://youtu.be/EbDkd901ZR0
V: 1.8.1
VC: 274

**Comment by RaSan147** [comment]
Interesting issue 🤔 (ps: you can directly post video on github, theres a photo *actually any file* to post)

**Comment by deadlyjack** [comment]
Go to settings, app settings, change quicktools tirgger mode, and let me know it it works or not.

**Comment by deadlyjack** [comment]
That's why the option is given. Only one option work on many devices and
another one rest of the devices.
