### ISSUE TITLE
This file contains binary data. Do you want to open it?

### ISSUE THREAD

**Issue by NotAColdSun** [deadlyjack/Acode#683]
I get this message when opening a text file, and when opened, it looks messy. Android phone.
Please, help.
Error while uploading Screenshot_20230411_135631_Acode.png --><!-- Error while uploading Screenshot_20230411_135619_Acode.png

**Comment by RaSan147** [comment]
@NotAColdSun * Screenshot is not uploaded

**Comment by avocadeys** [comment]
@NotAColdSun, a binary file is gibberish because the data in it is designed for the machine to read and not for humans.
