### ISSUE TITLE
[Feature Request] Better Code Completion Php

### ISSUE THREAD

**Issue by Lesauw** [deadlyjack/Acode#684]
Please add that you can access other files and automatically get suggested Php uses, functions, variables, etc. like with VSCode.

**Comment by RaSan147** [comment]
Better suggestion:
Make a plugin:
Selectable language model download with prettifier, import access among files (different languages use different way to import assets) and some code completion suggestions.
Might be a little tough (I'm lying, it will hurt a lot) to make such tool. But if i can be done
Boom, VS code in mobile with 0 competitors
