### ISSUE TITLE
[ BUG ] Scroll bar us files/plugins on the left!

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#687]
In the right menu, when I press to show the plugins, it shows some more, there is no way to scroll to show the others and also in the side menu files, I tried to reinstall to solve it, but no It worked @deadlyjack want more details about more I think you can understand!

https://user-images.githubusercontent.com/101356556/233865082-7076bdbf-6494-4878-a6b0-1102ca51ff92.mp4

**Comment by sebastianjnuwu** [comment]
at the moment only bug in the navbar of the plugin > explore

**Comment by deadlyjack** [comment]
fixed in version 1.8.3 178

**Comment by sebastianjnuwu** [comment]
@deadlyjack The Scroll bar of the plugins was solved but in the folders don't try to open a folder with several other folders like `node_modules` and drag it to the last one at least in mine it's not working.

📂
  --📂
   -- 📂
       -- 📁📁📁📁 ( Doesn't slide to see other folders)
