### ISSUE TITLE
[BUG] Cursor goes crazy when the left or right arrow keys is long pressed

### ISSUE THREAD

**Issue by avocadeys** [deadlyjack/Acode#689]
Acode version: v1.8.2 (276)

Every time I long press the arrow keys, the cursor suddenly goes crazy even though I stopped long pressing it. The only way to stop it is to restart the app. The bug only occurs when using the app's built-in arrow keys.

I noticed this bug when I updated the app to the latest version.

Here's the screenrecord.

https://user-images.githubusercontent.com/121883478/234983888-d9162dff-9427-47e9-8eed-e470a442577f.mp4

**Comment by kenny-kvibe** [comment]
+1
same bug & if pressed even more it goes even faster
restarting the apk resets it

**Comment by deadlyjack** [comment]
It's seems like touchend event is not catched. try change quickTools trigger mode in settings.

**Comment by avocadeys** [comment]
hello, @deadlyjack! i followed what you said and it worked. thanks again!
