### ISSUE TITLE
Autosave suggestion

### ISSUE THREAD

**Issue by inspir3dArt** [deadlyjack/Acode#69]
The time based autosave might not be the best option, because frequently, unnecessary write operations are not good for sdcards. With it disabled, projects that load JavaScript from a html file don't run correctly if not all project files are saved. I would suggest a event based autosave, that saves everything when the app gets closed or minimized and saves all unsaved files in the current project if you hit the run button.

**Comment by deadlyjack** [comment]
Hi @inspir3dArt thanks for the suggestion, I really can't remove autosave option but I can consider your other suggestion, like save all open files when user clicks run button or when user minimize the app.

**Comment by inspir3dArt** [comment]
Thanks, it would solve my problem, so I'm fine with it.

I still think replacing the current version of autosave with a event based one would be better and need no additional options. If it saves at the following events, wouldn't it fully replace the current system?

1. Save the current file when the user switch to or open another file.

2  save the current file when using the run button.

3. save the current file when the app gets closed, gets to background or the screen turns off.

Maybe I'm wrong or I'm looking at it to naive. At the end of the day I'm happy with whatever you choose to be the best way 😀

**Comment by CypherpunkArmoury** [comment]
Why not add it as an option

**Comment by deadlyjack** [comment]
I'll add it soon.

**Comment by gmiwoj** [comment]
So... how about that save on minimize/switch app feature? 
Tinkering with code and constantly switching apps and having to click save e v e r y s i n g l e t i m e  thousand times a day i feel my life wasting away on endless, dumb, easily avoidable nuisance. Plz fix :p

**Comment by tienomeis** [comment]
It might be more easy to implement it that way, that the currently shown file is saved on unfocus of the editor window.
