### ISSUE TITLE
Neither `Lint` nor `Ace Linters` plugins recognise Javascript private class fields

### ISSUE THREAD

**Issue by JuxtNorth** [deadlyjack/Acode#694]
The `Lint` and `Ace Linters` plugins show an error when javascript private class fields are used. For example, according to the plugins, Line 2 and 5 in the below code are erroneous.
```
class Foo {
  #bar;
  
  constructor () {
    this.#bar = 12;
  }

}
```

**Comment by bajrangCoder** [comment]
Report it to plugin repo
