### ISSUE TITLE
No support for numeric separators.

### ISSUE THREAD

**Issue by North077** [deadlyjack/Acode#695]
Acode fails to recognise Javascript `Numeric Separators`. The `Lint` plugin shows a `Syntax Error` and the syntax highlighting stops if there are `Numeric Separators` in between numbers. 
```
const dec = 1_00_000;
const hex = 0xff_fff;
const bin = 0b011_100_111;
// Syntax Highlighting stops after the first `Numeric Separator`
```

**Comment by deadlyjack** [comment]
You can raise this issue at https://github.com/ajaxorg/ace
