### ISSUE TITLE
Emmet Support for JS and others features 

### ISSUE THREAD

**Issue by UserOEM** [deadlyjack/Acode#697]
Hi. It's possible to implement in Acode pro emmet support for JS, to get a list of all possible comamnds when I type 'document. ' or any other available commands when I start to type (like in vscode) ? 

e.g. document.getElementById/querySelector etc.
e.g. 'log'  tab for console.log()

I saw that it is doable for html but didn't found nothing for JS. It would be nice to have, when I click on any file or folder (three dots), option to 'copy path' and 'copy to other project'. Thanks in advance.

**Comment by RaSan147** [comment]
Out of laziness i did this as a header for all my js files 😆

```js
const log = console.log,
	byId = document.getElementById.bind(document),
	byClass = document.getElementsByClassName.bind(document),
	byTag = document.getElementsByTagName.bind(document),
	byName = document.getElementsByName.bind(document),
	createElement = document.createElement.bind(document);

```

**Comment by UserOEM** [comment]
Hi @RaSan147 . Thanks for replying. I know that I can manually add shortcuts. I was thinking of writing a js snippet to be more like in vscode...as I already mentioned, when I start to type or when I use a variable/object, I would like **to get the list** of all possible commands for certain variable/object or general list of things that are available. I have installed Snippets plugin and insert pre-made snippets. For example, if I write custom snippets:

#get element
snippet getElementById
&emsp;&emsp; command 
snippet getElementsByClassName
&emsp;&emsp; command
snippet getElementsByTagName 
&emsp;&emsp; command
snippetget querySelector
&emsp;&emsp; command
snippetget querySelectorAll
&emsp;&emsp; command

I want to mention that the list in Acode is three rows height. When I start to type 'get' I wil get the list of three commands. First two will be (getElementById, getElementsByClassName)  and the third will be some random command that contains 'get' keyword e.g. 'singleton'. 

**The first problem** - triggering the list based of an element 
I'm trying to group all get/query element commands to be triggered when I type '.' (dot) or any other commands based of an element - object/array/variable ect. For example:

[array].entries
&emsp;&emsp;&ensp;&nbsp; fill
&emsp;&emsp;&ensp;&nbsp; filter
&emsp;&emsp;&ensp;&nbsp; forEach
&emsp;&emsp;&ensp;&nbsp; map
&emsp;&emsp;&ensp;&nbsp; ...ect

element.getElementById
&emsp;&emsp;&emsp;&ensp; getElementsByClassName
&emsp;&emsp;&emsp;&ensp; getElementsByTagName
&emsp;&emsp;&emsp;&ensp; querySelector
&emsp;&emsp;&emsp;&ensp; ...ect
  
number.toFixed
&emsp;&emsp;&emsp;&nbsp; toLocaleString
&emsp;&emsp;&emsp;&nbsp; toSting
&emsp;&emsp;&emsp;&nbsp; ..ect

// Trigger is working
trigger \(?f\(
endTrigger \)?
snippet func
&emsp;&emsp; command

// Tried following for the dot but doesent work
#dot 
trigger . 
snippet getElementById
&emsp;&emsp; command
trigger . 
snippet getElementsByClassName
&emsp;&emsp; command

#escaping dot 
trigger \.
snippet getElementById
&emsp;&emsp; command
trigger \.
snippet getElementsByClassName
&emsp;&emsp; command

#adding dot direct in the snippet 
snippet .getElementById
&emsp;&emsp; command
snippet .getElementsByClassName
&emsp;&emsp; command

**The second problem** - the number of rows is not enough. 
I need at least five, six rows or even more (it depends from the screen size). It would be good to put in the settings, so the user can change number of displayed rows e.g from 3,4,5...till 10. 

I would appreciate some help about these two problems. Thanks in advance.

**Comment by RaSan147** [comment]
From what it seems in the app, it doesn't support language data types and methods (.function()) things, i agree that would be huge help for everyone.

**Comment by bajrangCoder** [comment]
Check plugins
