### ISSUE TITLE
}-key missing on german bluetooth keyboard 

### ISSUE THREAD

**Issue by qapp** [deadlyjack/Acode#70]
German keyboard layout doesn't allow me to type '}' on a physical keyboard in the editor window. However the key works in the rename window of acode (F2). To type } on a german keyboard you press AltGr+0. I didn't change any key bindings in acode.

**Comment by inspir3dArt** [comment]
This could be relevant to the problem:
https://github.com/atom/atom/issues/2907

**Comment by deadlyjack** [comment]
Thanks for the reference. I'll find solution and fix it soon.

**Comment by Niskill2** [comment]
Seems like i have the same problem...

**Comment by tienomeis** [comment]
Solved it in the settings.
1. Go to Settings / Other Settings / Key bindings -> Edit
2. Change key bindings for foldOther and unfoldall to null.
It will look like this:

  "foldOther": {
    "description": "Fold other",
    "key": "null"
  },
  "unfoldall": {
    "description": "Unfold all",
    "key": "null"
  },
