### ISSUE TITLE
无法更改文件编码

### ISSUE THREAD

**Issue by mailtoxin** [deadlyjack/Acode#707]
原文件编码是GB18030，默认打开为utf-8，显示为乱码，更改为GB18030后依然为乱码。
![Screenshot_2023-05-31-07-34-56-404_com foxdebug acode](https://github.com/deadlyjack/Acode/assets/65784106/f9d7bfce-d63c-4bf2-a7b8-02ef79d3d832)
![Screenshot_2023-05-31-07-34-42-862_com foxdebug acode](https://github.com/deadlyjack/Acode/assets/65784106/bad2faee-b6ea-46d2-a5ec-e2af18de55a4)

**Comment by deadlyjack** [comment]
Thank you for reporting it. I'll try to fix it as soon as possible.
