### ISSUE TITLE
Kindly Bump build target to 33

### ISSUE THREAD

**Issue by RaSan147** [deadlyjack/Acode#709]
Cordova recently bumped their version (and package install installs that one instead of the mentioned version) and building this repo causes Error, since the official cordova now requires 33

![image](https://github.com/deadlyjack/Acode/assets/34002411/aa9689d2-be61-462f-8153-ea08ae923762)

simply modifying these files fix it. (idk if it causes any issue since I got none yet)
https://github.com/RaSan147/Acode/commit/229b6358aa2b0117b0d34244ea4ea903f61d8f3a

**Comment by deadlyjack** [comment]
It's not very easy to uodate to latest cordova. And it's also not needed to update. you need to install cordova 10 to build the app.
