### ISSUE TITLE
Please update CTRL, SHFT activate color scheme

### ISSUE THREAD

**Issue by RaSan147** [deadlyjack/Acode#710]
there's a plugin command button (now no longer working with v1.8.4 build 178 the github latest version)  has a amazing color indicator to make it understandable whether its activated or not.

But the CTRL, SHFT buttons only put on a darker background (extremely less visible) making it hard to determine its activation state. please update this (also adding a goto button and the old command pallet button would be really helpful)

**Comment by deadlyjack** [comment]
Thanks for the suggestion. I will improve it.

**Comment by RaSan147** [comment]
Seems its fixed. Closing issue. Thanks
