### ISSUE TITLE
Can't open text opened from X-plore file manager

### ISSUE THREAD

**Issue by MicroBeast** [deadlyjack/Acode#711]
Opening text (or any file types actually) from X-plore file manager doesn't open in Acode (free or pro).

Acode: any versions
X-plore: any versions
Device:
- Vivo Y15s, Android 12go. 
- Samsung M205g, Android 10. 
- Xiaomi Redmi 4A, Android 7.1.2, 
- Samsung T-555, Android 7.1.1

**Comment by deadlyjack** [comment]
Fixed in 1.8.4
