### ISSUE TITLE
Global search scanning binary files

### ISSUE THREAD

**Issue by RaSan147** [deadlyjack/Acode#713]
Global search is really fast but it also searches binary fines and ends up capturing lots of unwanted search results. Kindly ignore files with binary content. (Maybe keep enabled when regex on since they has binary support)

Ps: app is crashing a lot these days. Hope things get better soon.

**Comment by deadlyjack** [comment]
Detecting binary file is a lot task, for now you can use exclude files settings.

**Comment by RaSan147** [comment]
understandable...
thanks for the info.
lets keep this issue open for a while

**Comment by deadlyjack** [comment]
Yup, if there are too many files app cannot handle it. So I restricted it to few thousand files. You can check and let me know. Also if it's crashing you can change maximum files and folder from settings.
