### ISSUE TITLE
Can't open files from within Acode (even after reading similar issues and FAQ)

### ISSUE THREAD

**Issue by chrisrapson** [deadlyjack/Acode#714]
It seems like Android 12 permissions changed folder access a lot... I saw a few other issues about this, and some suggestions how to work around it. Unfortunately those suggestions aren't working for me. 

In the `Files` menu I can open up the `add path` option, choose the folder, and confirm that I want to "Allow Acode to access files in folder name". Now I can see the folder and the files inside it in the Acode "file browser". If I select the folder and press the tick, now the folder and its contents show up in the left menu, below the list of `Active files`. But when I try opening any of the files, nothing happens. I've tried opening them from either the left menu or the Acode file browser, neither is working for me. 

I am able to open the files from the Android file manager, if I use open with and select Acode. I can edit and save them. The only problem seems to be opening them from within Acode.

Do you have any suggestions what else I could try? I'm on version 1.8.3.

**Comment by chrisrapson** [comment]
@deadlyjack here's a screen recording:

https://www.dropbox.com/s/5ifoxl9xpnf6wc5/Screen_Recording_20230607_211414_Acode.mp4?dl=0

**Comment by chrisrapson** [comment]
I tried reinstalling now... There was no change. Do you have any other
ideas?

This is on Android 13, security patch from May 1st 2023.

**Comment by Belu-momhn** [comment]
Acode is android of the only ~~vscode~~

**Comment by deadlyjack** [comment]
That's weird. Try updating the app, it may fix it.

**Comment by deadlyjack** [comment]
> @deadlyjack I had already tried uninstalling and re-installing, but I gave it another try... still no luck. When you say "update", I see 1.8.4 here on github, but only 1.8.3 in the Google Play Store, so I think I'm on the newest version available to me.
> 
> It's a Samsung Galaxy S23. Compatibility says "Works on your device".
> 
> Could it be an obscure permissions issue? I have allowed "Music and audio", "Photos and videos" and "Notifications". There is nothing listed under "Not allowed".

Try clearing app data once. I'll try it on the s23 and see what's wrong. Thank you, for reporting.

**Comment by chrisrapson** [comment]
Clearing the app data removed all my configurations, so the app looks like your demo screenshots again. Unfortunately, it hasn't fixed the bug. I can still open folders, but not files.

**Comment by chrisrapson** [comment]
I'm on v1.8.3 from the Google Play Store.

**Comment by Belu-momhn** [comment]
- Warning

**Comment by heartlog** [comment]
@chrisrapson are you using some kind of theme ?
Try clear data and uninstall app.
Reinstall latest GitHub version.
Go to app settings and give it all files access.
1) music and audio
2) photos and videos
Uncheck- remove permission if app is unused.

Try making that acode folder in different location (sd card).

*Check accessibility some times app revokes app permission and background usage.
