### ISSUE TITLE
Unable to creat new file

### ISSUE THREAD

**Issue by Octopustank** [deadlyjack/Acode#715]
The problem occurs in two themes: 
**1.** 
For example, I creat a new file, name it ,and I choose Internal Storage to save, but it failed.
![Screenshot_20230605_203510_com foxdebug acode](https://github.com/deadlyjack/Acode/assets/113182591/d41e67ab-1d44-4246-af28-1824b9a9b362)
**2.**
If I want to save this new file to a external storage, and I've already granted  saving permission , but still failed. 
![Screenshot_20230605_203753_com foxdebug acode](https://github.com/deadlyjack/Acode/assets/113182591/bc14ea8e-d3a2-4d24-b089-2281a99f4bd6)

**However,** reading files from external storage or changing those files are both successful. 

Thanks a lot !
(OS:  Harmony 3.0.0)

**Comment by deadlyjack** [comment]
Which version of app you are using?

**Comment by Octopustank** [comment]
I'm using v1.8.0. I got it from F-Droid.&nbsp;



---Original---
From: "Ajit ***@***.***&gt;
Date: Fri, Jun 9, 2023 05:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deadlyjack/Acode] Unable to creat new file (Issue #715)




 
Which version of app you are using?

**Comment by deadlyjack** [comment]
Try to remove the directory from acode and add again.
