### ISSUE TITLE
Bug with Microsoft Swiftkey keyboard

### ISSUE THREAD

**Issue by s4ntiksu** [deadlyjack/Acode#719]
When you enter a property in the CSS or code. I don't know how I don't know how to fix it, But this bug is just annoying when writing code.

**Comment by deadlyjack** [comment]
what bug?

**Comment by s4nt1k** [comment]
> what bug?

Uploading screen-20230613-151747.mp4…

**Comment by s4nt1k** [comment]
@deadlyjack https://drive.google.com/file/d/1w_vNGWZy-ZMSJ4gzbdTeOBWyRxoePQZA/view?usp=drive_link
That's the kind of thing I'm doing, maybe I'm wrong, maybe I'm not.

**Comment by deadlyjack** [comment]
It's not Acode. It's SwiftKey keyboard.

**Comment by s4nt1k** [comment]
@deadlyjack ok
