### ISSUE TITLE
The problem with erasing spaces

### ISSUE THREAD

**Issue by qhouz** [deadlyjack/Acode#725]
If you use tabs, the code editor easily removes them.

But if you use spaces, they will be erased one at a time instead of the number that is specified in the settings, so it would be great if this problem was fixed and made like in vscode.

**Comment by sebastianjnuwu** [comment]
My app has a similar problem after the last update, I select something to delete and it just deletes the whole line, imagebs below:
![Screenshot_20230625-125111~2](https://github.com/deadlyjack/Acode/assets/101356556/b8cf6f09-ef70-4340-8389-2c34a5b90c16)
![Screenshot_20230625-125105~2](https://github.com/deadlyjack/Acode/assets/101356556/1e59b55c-efe6-42ea-8781-840e267f0f66)

**Comment by bajrangCoder** [comment]
Set Keyboard mode to Aggressive from Acode App > Settings> App Settings> key board mode
