### ISSUE TITLE
file title in the app doesn't show the selected tab

### ISSUE THREAD

**Issue by alexbodn** [deadlyjack/Acode#730]
hello friends,
 there is a title over the tab labels, with additional info on one file.
it is usually regarding the file in the active tab, 
but at app start, it's regarding the file in the last tab, even though another tab is marked active.

thanks,
alex

**Comment by deadlyjack** [comment]
Which version you are using?

**Comment by alexbodn** [comment]
the last payed version

**Comment by bajrangCoder** [comment]
It's not more
