### ISSUE TITLE
undo doesn't work cleanly

### ISSUE THREAD

**Issue by alexbodn** [deadlyjack/Acode#731]
undo seems to leave some text selected, and it gets overwritten by text typed after it.
it goes like this:

type abc => abc
backspace=> ab
undo => abc
type d => abd

looks as undoing the deletion is a pasting, but the text remains selected (though not visibly), as it's replaced by later typing.

**Comment by deadlyjack** [comment]
This is expected behavior as it should be known what did the undo replaced.

**Comment by alexbodn** [comment]
it doesn't happen in other editors.
if a text is not marked as selected, there's no clue i'm about to replace it.
