### ISSUE TITLE
Can not set default encoding on open file

### ISSUE THREAD

**Issue by shutaozhenzhen** [deadlyjack/Acode#737]
in `openFile` function in `openFile.js`
```js
    const binData = await fs.readFile();
    const fileContent = helpers.decodeText(binData);
```
so file content are open with default encoding `utf-8`, which can not change

change encoding command in cammand.js do not solve this problem
```js
  async 'encoding'() {
    const encoding = await TextEncodings();
    const file = editorManager.activeFile;
    file.encoding = encoding;
    const text = file.session.getValue();
    const decodedText = new TextEncoder().encode(text);
    const newText = new TextDecoder(encoding).decode(decodedText);
    file.session.setValue(newText);
    file.isUnsaved = false;
    editorManager.onupdate('encoding');
    editorManager.emit('update', 'encoding');
  },
```
chinese char will be decode as `\65533` in default open on `openFile`
reEncoding `\65533\65533` will turn to `Uint8Array(6) [
  239, 191, 189 , 239, 191, 189]` and  decode with `gbk` as `锟斤拷`

**Comment by deadlyjack** [comment]
Hi thank you for reporting it. I think we should connect over telegram, discord or whatever means you'd like to because I might need your help.

**Comment by shutaozhenzhen** [comment]
I have joined tg

**Comment by deadlyjack** [comment]
You can dm me at t.me/ajitkumar_dev
