### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sls1005** [deadlyjack/Acode#756]
Please provide the shortcut buttons to:

1. Enable/disable text-wrap.
2. Make the invisible characters visible.

**Comment by alexbodn** [comment]
see ... | settings | editor settings

**Comment by MicroBeast** [comment]
> see ... | settings | editor settings

I think the request mean quicker access from 3 dots menu or pencil menu.

The current implementation is Settings > Editor Settings > Scroll Settings. Placed 1 step deeper than previous versions. Try to keep enter that 3 step settings if you just want to check between Wrap or Unwrap.

**Comment by sls1005** [comment]
>I think the request mean quicker access from 3 dots menu or pencil menu.

Yeah, that's exacly what I meant.

Sometimes I want to see the whole code, so I use line wrap; sometimes I have to check if the indentation is correct, so I disable line wrap and turn on invisible-character-visualizing, because some languages only allow using spaces for indentation, while some only allow tabs, but I'd then turn it off because seeing the visualized spaces makes me overwhelmed. I hope to be able to quickly switch between these functions.
