### ISSUE TITLE
about the icons

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#759]
I noticed that in the last update the icons were changed and in some files it no longer appears as before, for example, the licensa appeared in both uppercase and lowercase.

![Screenshot_20230717-193312](https://github.com/deadlyjack/Acode/assets/101356556/d70d98f9-0c45-411f-8cdb-64077be0fb25)

**Comment by sebastianjnuwu** [comment]
I wanted to know how to customize example icons That starts with a "point" like `.replit` and others like `readme.md` when I was testing it worked more dps not just getting `a.readme`
![Screenshot_20230717-193911~2](https://github.com/deadlyjack/Acode/assets/101356556/58af6608-a44f-4d7d-b6cf-92ffe6728811)


```js
.file_type_readme::before {
  display: inline-block;
  content: '';
  background-image: url(#{$readme});
  background-size: contain;
  background-repeat: no-repeat;
  height: 1em;
  width: 1em;
}
```

With `tsconfig.json` it worked

**Comment by deadlyjack** [comment]
You need aad it using modelist. See https://acode.foxdebug.com/plugin-docs/ace-modes?title=Ace%20Modes

```js
addMode('markdown', ['\.readme'], 'Read me']
```

**Comment by sebastianjnuwu** [comment]
> You need aad it using modelist. See https://acode.foxdebug.com/plugin-docs/ace-modes?title=Ace%20Modes
> 
> ```js
> addMode('markdown', ['\.readme'], 'Read me']
> ```

This serves to place icons in example files:
`.replit`: Replit icon, `vercel.json`: vercel icon
