### ISSUE TITLE
Directory Parsing Issues

### ISSUE THREAD

**Issue by krypterro** [deadlyjack/Acode#764]
On the latest build, 1.8.5 (298) on Android ACode now continuously wastes resources trying to map remote folders over SFTP. This is a problem when there is low bandwidth, and a very large number of files. 

In Python we often use virtual environments, which is where our software libraries live, and there can easily be several thousand small files.

Ideally ACode would not index any folder beginning with . on Linux (hidden folders) unless the user opens the folder, but in this case ACode fails, so I'm not sure what the problem is there.

![Screenshot_20230718_155129_Acode](https://github.com/deadlyjack/Acode/assets/41011655/2d5e77eb-aa36-4aea-8dec-7a5aba8caf4a)

**Comment by deadlyjack** [comment]
Ok, I'll give option skip listening files. Listing files would help search over project.

For now go settings and click on edit settings.json and change the value of maxFiles and maxFolders to zero.
