### ISSUE TITLE
Preview settings 

### ISSUE THREAD

**Issue by daviddanielng** [deadlyjack/Acode#775]
How does the preview settings work? I have a server locahost:8080. I have done everything for the previewer to send me to my server everytime I preview a document but is is not working.
![Screenshot_20230724-101112](https://github.com/deadlyjack/Acode/assets/107226253/569386e0-febc-4e6a-9664-747a48c1c420)

**Comment by sebastianjnuwu** [comment]
Hello this server to view the example index.html html file you run and it will appear at this address
