### ISSUE TITLE
Project Mode

### ISSUE THREAD

**Issue by Elovel** [deadlyjack/Acode#782]
hi .please implement project mode to this cool app instead working inside folders (like spck editor)

**Comment by s4ntiksu** [comment]
What? Like with folders it is possible to work too it is possible. Or is it different?

**Comment by Elovel** [comment]
nope, it's different . i love spck editor but not have syntax checker for python .

**Comment by s4ntiksu** [comment]
So the problem is not in code. The problem is with the plugins.
