### ISSUE TITLE
Plugin creating

### ISSUE THREAD

**Issue by wiktorInny** [deadlyjack/Acode#793]
Please, create a tutorial about creating plugins. I download plugin template and run npm run start-dev and I have errors. I need tutorial step by step how to run this in vscode.

**Comment by sebastianjnuwu** [comment]
Run `yarn build` and right after `yarn build-release` you will see a zip file "dist.zip" that will be the plugin!

**Comment by wiktorInny** [comment]
Thanks. Is possible to run and debug plugin on windows/linux ?

**Comment by sebastianjnuwu** [comment]
> Obrigado. É possível executar e depurar o plug-in no Windows/Linux?

It is possible to create your plugin both on Windows and Linux, for example I created my plugins on my cell phone.

There is still no way to see changes in the plugin in real time in acode just copying in zip and adding in the app
