### ISSUE TITLE
[BUG] Results not showing in multi-file search

### ISSUE THREAD

**Issue by xssolve** [deadlyjack/Acode#794]
When using the multi-file search with a query that contains "(", the number of results shows up correctly, but the results themselves are not visible.
![Screenshot_20230811_212517_Acode](https://github.com/deadlyjack/Acode/assets/62601321/7d20f241-2287-411b-b1c8-001effd97947)

**Comment by deadlyjack** [comment]
Thanks for reporting it, I'll fix it.
