### ISSUE TITLE
Plz add Custom snippet options 

### ISSUE THREAD

**Issue by Gul7333** [deadlyjack/Acode#798]
Very difficult to write js ,php or other languages code,,,only few snippet are predefined....
Plz add a option of creating custom snippets in app.

**Comment by Jisan901** [comment]
You can use custom snippets on latest version,  by changing the 'snippets' directory

**Comment by sebastianjnuwu** [comment]
> You can use custom snippets on latest version, by changing the 'snippets' directory

Complementing his information, you can create your own snippets see [here](https://github.com/deadlyjack/Acode/issues/798#issuecomment-1679450670) an example.

**Comment by Gul7333** [comment]
How can I do this,,,, I have downloaded snippet plugin and created my snippet but they are not working,,as you pointed to dist directory and edit snippet...
 how to do it ,,, do I have to build the app again after editing snippet in dist directory,,,,,which I don't know...

**Comment by UserOEM** [comment]
@Gul7333 https://github.com/deadlyjack/acode-plugin-snippets

**Comment by Gul7333** [comment]
This plugin doesn't work in my mobile....
I have installed it ,,it is working fine,,,but custom snippet which I added are not showing ....other snippet work but custom snippet Doesn't work...
Also in acode command palette this plugin is not showing (set directory and reset directory)
So that's why I suggested acode team to make options of creating custom snippet as plugin doesn't work as they should on every mobile

**Comment by UserOEM** [comment]
Snippets are working but it's not possible to trigger a specific snippet using dot (unfortunately) or base on some condition but you can you any other character. You need to point the snippets folder. When you press 's' three snippets below will be triggered:

`snippet s DOMContentLoaded
	DOMContentLoaded${1}

snippet s navigator
	navigator{1}

snippet s serviceWorker
	serviceWorker{1}

snippet s register
	register{1}`

**Comment by UserOEM** [comment]
I'm also using it on phone with Acode Pro. More examples

`#get dataset
snippet s hasAttribute
	hasAttribute(${1:name})${2}
snippet s getAttribute
	getAttribute(${1:name})${2}
snippet s setAttribute
	setAttribute(${1:name}, ${2:value})${3}

#dataset
snippet s dataset
	dataset(${1:property-name})${2}

#cloneNode
snippet s cloneNode
	cloneNode(${1:deep? Boolean})${2}

#toFixed
snippet s toFixed
	toFixed(${1:number})${2}

#tagName
snippet s tagName
	tagName${1}

#toLowerCase
snippet s toLowerCase
	toLowerCase()${1}

#preventDefault
snippet s preventDefault
	preventDefault()${1}

#target
snippet s target
	target${1}
snippet s currentTarget
	currentTarget${1}
`

**Comment by UserOEM** [comment]
How to set snippets directory? 
top right corner, three dots -> settings  -> plugins  -> installed tab -> Snippets  -> top right corner icon settings -> Set snippets directory

Don't forget to restart the app every time you update/edit snippets or change directory.
