### ISSUE TITLE
FOSS is not legit in app store title

### ISSUE THREAD

**Issue by say2joe** [deadlyjack/Acode#799]
FOSS means FREE open source software. Not ad-based, GitHub repo, forked vscode knockoff. Please remove FOSS from your app.

**Comment by sebastianjnuwu** [comment]
> FOSS means FREE open source software. Not ad-based, GitHub repo, forked vscode knockoff. Please remove FOSS from your app.

"Hello! Thank you for sharing your concerns. I understand that 'FOSS' is often associated with open-source software without ads. However, it's important to remember that the definition of 'FOSS' includes the freedom to access the source code and the ability to modify it. Some 'FOSS' applications may choose to include ads to support ongoing development and offer a free experience to users. This decision can vary based on the needs of the developers and the community. If you have more questions about the app or would like to further discuss the use of 'FOSS' with ads, feel free to share your thoughts. It's always great to have different perspectives on the matter!"

**Comment by sebastianjnuwu** [comment]
> > FOSS significa software livre de código aberto. Não baseado em anúncios, repositório do GitHub, cópia vscode bifurcada. Por favor, remova o FOSS do seu aplicativo.
> 
> "Olá! Obrigado por compartilhar suas preocupações. Entendo que 'FOSS' é frequentemente associado a software de código aberto sem anúncios. No entanto, é importante lembrar que a definição de 'FOSS' inclui a liberdade de acessar o código-fonte e o capacidade de modificá-lo. Alguns aplicativos 'FOSS' podem optar por incluir anúncios para apoiar o desenvolvimento contínuo e oferecer uma experiência gratuita aos usuários. Essa decisão pode variar com base nas necessidades dos desenvolvedores e da comunidade. Se você tiver mais perguntas sobre o aplicativo ou gostaria de discutir mais o uso de 'FOSS' com anúncios, sinta-se à vontade para compartilhar seus pensamentos. É sempre bom ter diferentes perspectivas sobre o assunto!"

Anyway, that's the developer's choice!

**Comment by say2joe** [comment]
No, what you're describing is genetic open-source software. I've been building apps for over 25 years and while I'm always learning something new, I'm pretty sure I've got the definition of FOSS down. Also, I did verify that I'm correct before seeing your post. More importantly, I can't argue that there is some subjective understanding here but never the less to FREE means no ads (though technically I believe there's a loophole if you use an ad serving platform which is open source but I think it's a horrible situation despite f-droid allowing for it). Regardless, I don't think you even wrote any of the code so it's a mute point in my not so humble opinion. If you fork other developers work, then package it up to include ads, but you add nearly nothing I'm terms of functionality while not giving obvious credit where credit is due, you're stealing code to make a profit with little to no work on your behalf. I'm sorry but if you had made some dramatic code improvements or contributions, I wouldn't have said a word.

**Comment by sebastianjnuwu** [comment]
> Não, o que você está descrevendo é um software genético de código aberto. Venho construindo aplicativos/sites há mais de 25 anos e, embora esteja sempre aprendendo algo novo, tenho certeza de que entendi a definição de FOSS. Além disso, verifiquei se estou certo antes de ver sua postagem (para evitar parecer um tolo). Mais importante ainda, não posso argumentar que haja algum entendimento subjetivo aqui, mas, mesmo assim, GRATUITO significa sem anúncios (embora tecnicamente eu acredite que haja uma brecha se você usar uma plataforma de veiculação de anúncios de código aberto, mas acho que é horrível situação apesar do f-droid permitir isso). Independentemente disso, acho que você nem escreveu nada do código, então é um ponto discutível na minha opinião não tão humilde. Se você distribuir o trabalho de outros desenvolvedores, empacote-o para incluir anúncios, mas você não adiciona quase nada em termos de funcionalidade, sem dar crédito óbvio a quem o merece, você está roubando código para obter lucro com pouco ou nenhum trabalho em seu nome. Sinto muito, mas se você tivesse feito algumas melhorias ou contribuições drásticas no código, eu não teria dito uma palavra.

I'm not putting your knowledge on the line, before replying to your first comment I checked and talked to other developers on this subject and researched about (Fool I'm not, maybe uninformed), software using the term "FOSS" may use ads yes, many web browsers such as Firefox and Brave do and as per my interpretation of this [article](https://www.gnu.org/philosophy/floss-and-foss.pt-br.html#:~:text=Outros%20usam%20o%20termo%20%E2%80%9CFOSS,free%E2%80%9D%20se%20refere%20a%20liberdade.)

• Do you have any articles that prove that anyone using the term FOSS cannot run ads? 

• "forked vscode imitation" isn't something misguided? 

• "Without giving obvious credit where credit is due, you are stealing code for profit with or without work on your behalf." What? 

Can I be wrong? I can more as said before is due to lack of information!
