### ISSUE TITLE
play story customize

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#800]
Is it possible to constomize the image and description for a certain language (eg pt-BR) in the play story or is it not possible?

what is this for?
• `fastlane/metadata/android`

**Comment by sebastianjnuwu** [comment]
@deadlyjack

**Comment by deadlyjack** [comment]
It's possible but it's hard to maintain.

**Comment by sebastianjnuwu** [comment]
Ahh
