### ISSUE TITLE
Changes to .key-bindings.json not taking effect 

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/Acode#801]
I remember when the Command Button plugin was created, I recall using the Command Button and also modifying the json file to customize the controls, and the new command worked.

However, now that it has been replaced with Ctrl, I can no longer customize settings. I figured I could just open the .key-bindings.json file and make changes including modifications like "Ctrl-&" to perform certain action, but it doesn't work. Am I doing something wrong?

Controls already defined in the file work e.g., Ctrl-A to select all, Ctrl-P to paste, etc., but not when I replace a command.

For example, in the screenshot I attached, I want Ctrl-U to Select Up, but nothing happens on saving. 

![Screenshot_20230817-173548](https://github.com/deadlyjack/Acode/assets/34959120/e8432ab1-8b68-4af8-b07b-5b522899c883)

**Comment by bajrangCoder** [comment]
It's working
