### ISSUE TITLE
Default font not found

### ISSUE THREAD

**Issue by wiktorInny** [deadlyjack/Acode#806]
I have "Default font not found" message and it not disappear. It always show. Acode version 1.8.6
![Screenshot_20230828-084250](https://github.com/deadlyjack/Acode/assets/61705979/8e845a0c-98c2-4e17-9869-a4944c1814b3)

**Comment by deadlyjack** [comment]
Try to clear app data and restart the app.

**Comment by wiktorInny** [comment]
It works.
