### ISSUE TITLE
Search in file is broken, it only search backwards

### ISSUE THREAD

**Issue by asl97** [deadlyjack/Acode#809]
Typing in the search bar moves the cursor backwards, pressing enter or the forward button also moves it backwards.

https://github.com/deadlyjack/Acode/assets/4752645/fce2ee0d-e2f3-47d3-9c13-7efe63463d18

I tried reading the source code and honest couldn't understand why it's not working, the messageless commits doesn't help.

Maybe I am looking at the wrong places and the issue is older than the commit that changes it below.

https://github.com/deadlyjack/Acode/blob/0bd0fcfb8a67eccf93268704c95e714280d8ea8e/src/handlers/quickTools.js#L316-L322

https://github.com/deadlyjack/Acode/commit/ad1fc3d65b96e6fdc8e0eccae2a185b4de739bd3#diff-b46b01d6ed020a238065127cc51634b279fee3fe600705414a2ad9ef20052914R157

edit: version 1.8.6 (308) and 1.8.6 (311) from f-droid
____
<details>
<summary>edit2: I gonna just hide this section in a spoiler to avoid confusing the maintainers, this whole section of code just confuses me</summary>

previously:

button | arg1 | arg2
--- | --- |---
prev | false | true
next | true | true
oninput | false | false

<details>
<summary>
edit2 is clearly wrong, it's hidden in this section for record, see edit 3 below</summary>

Actually, is find parameters just flipped?

if `backwards` actually means forward, it kind of make sense.
(but that doesn't make much sense as they are paired with their respective names as an object before passing to the editor find)

`find(skip, backward)` -> `find(backward, skip)`

pseudo code:

```python
find search string backwards from cursor and move cursor
if arg2:
  return forward if arg1 else backward
return cursor
```
</details>

edit3: 
This make much more sense,

pseudo code:

```python
if existing_match and not arg1:
  move cursor to start of match

return backward if arg2 else forward
```

but it doesn't match with the current always move backwards behavior

currently:
button | arg1 | arg2
--- | --- |---
prev | 1 | true
next | 1 | false
oninput | 0 | false
enter | 1 | false

</details>

**Comment by deadlyjack** [comment]
Seems to working fine for me. Can you specify version of the app.

**Comment by asl97** [comment]
> Seems to working fine for me. Can you specify version of the app.

I did specify it, two weeks ago, version 1.8.6 (308) and 1.8.6 (311) from f-droid

**Comment by asl97** [comment]
I will edit this into my last post

update: I copy the settings.json from the fdroid setting to the google play version and the bug appears, I guess there is some setting that is not playing nicely, I will get back to you once I find time to dig into this properly
