### ISSUE TITLE
How does preview settings work?

### ISSUE THREAD

**Issue by LegalDavidDaniel** [deadlyjack/Acode#811]
I have a website that I use acode to fix bugs , I have developed a complicated mean of using git and termux to update the source code, I only use acode for editing, the thing is  acode opens  index.html but it can't run PHP code and make use of SQL database so I need acode to open a URL like www.example.com instead of locahost,
I have tried tweaking 
![Screenshot_20230901-131811](https://github.com/deadlyjack/Acode/assets/107226253/0fcaa4eb-a315-42d4-acf6-186dfa234fce)
I ended up with no result and frustrated .

**Comment by LegalDavidDaniel** [comment]
@deadlyjack

**Comment by deadlyjack** [comment]
If you have started server in other app like termux or php server, you can set preview port for that server. When you press run button if open servers url.

**Comment by LegalDavidDaniel** [comment]
No it doesn't open my server URL it opens another port.
For example:
If I have a server locahost:8080 and set host and post settings in preview
to 8080, it opens locahost:8081 instead of locahost:8080
