### ISSUE TITLE
Preview Broken

### ISSUE THREAD

**Issue by LegalDavidDaniel** [deadlyjack/Acode#812]
The preview sometimes renders a blank page , I have to open/reload the index.html in editor for it to work , then after a while it renders a blank page again
Video 👇👇
https://drive.google.com/file/d/1ISnJ7Uwggja3e8ITBhl7174PvVbrzIbd/view?usp=drivesdk

**Comment by LegalDavidDaniel** [comment]
@deadlyjack

**Comment by deadlyjack** [comment]
PHP is not supported. You have html in your root folder, Acode is running that html file.

**Comment by LegalDavidDaniel** [comment]
> PHP is not supported. You have html in your root folder, Acode is running that html file.

You don't understand, I don't want to run the PHP file, I want acode to run the root html(not a blank file) without me reloading/opening the index.html everytime I open the app.

**Comment by LegalDavidDaniel** [comment]
> PHP is not supported. You have html in your root folder, Acode is running that html file.

True acode is running the index.html but my index.html is not blank, why am I getting a blank page?
