### ISSUE TITLE
Feature Suggest 

### ISSUE THREAD

**Issue by LegalDavidDaniel** [deadlyjack/Acode#813]
I don't know where to suggest feature, nobody took note or wrote a comment on my post on idea tab
..

Can you add a feature that when format is long clicked 
![Screenshot_20230901-145731](https://github.com/deadlyjack/Acode/assets/107226253/341310ae-72c8-4175-b4bb-9ae3dbdf5ff7)

This should open
![Screenshot_20230901-145743](https://github.com/deadlyjack/Acode/assets/107226253/357a6c4d-ba97-4559-9a58-04a92d2cacfc)

**Comment by deadlyjack** [comment]
Long press in menu is not supported. It will break functionality if implemented.
