### ISSUE TITLE
Acode does not remember format option 

### ISSUE THREAD

**Issue by LegalDavidDaniel** [deadlyjack/Acode#815]
The app doesn't remember select format option after closing the app, you have to set it again when wherever you open the app.
https://drive.google.com/file/d/1JRQtcP9a3FH8mha1va8JrxH6qzwYrwnq/view?usp=drivesdk

**Comment by deadlyjack** [comment]
Unable to regenerate the issue even after following the video.

**Comment by LegalDavidDaniel** [comment]
> Unable to regenerate the issue even after following the video.

Editing the format setting settings.json fixed it
