### ISSUE TITLE
External mouse click on buttons in quick tools not working

### ISSUE THREAD

**Issue by mzivic7** [deadlyjack/Acode#818]
When using external wireless mouse connected through OTG, i am unable to click on quick tools.
If I open eg. find tool, I can't click on its buttons either.
Physical keyboard arrow buttons also won't move button selection when in find tool.
(Tried on Android 8 and 12)

https://github.com/deadlyjack/Acode/assets/92328096/1a237939-576d-40c8-ad2c-6d28818f08b2

**Comment by bajrangCoder** [comment]
Try by changing quick tools mode to click from `Settings>App Settings `

**Comment by mzivic7** [comment]
It works, thank you.
