### ISSUE TITLE
Broken autocorrect and editor is treated as password?

### ISSUE THREAD

**Issue by heartlog** [deadlyjack/Acode#821]
Facing the problem with Acode autocorrect and intellicence.
While typing some md files, autocorrect changes text to unexpected sentence and it's troublesome to write code.
Ex.
If I type- (Ignore the blur)
![Screenshot_20230908_090401_Acode](https://github.com/deadlyjack/Acode/assets/76758776/1bf21d21-8a3e-4404-a74d-7a0ef115e997)
It changes to when I hit enter on **Keyboard**.
![Screenshot_20230908_090422_Acode](https://github.com/deadlyjack/Acode/assets/76758776/3ed25eef-88cc-4a5c-9543-e6e86a23fcf8)

### Editor is treated as password? 
As you can see while typing in acode, the text is treated as password input. So, Password manager like dashlane activates auto-fill.

**Comment by deadlyjack** [comment]
To disable suggestion for the editor, the input mode is set to password as keyboard suggestions creates issue for some keyboards. You can change it from settings, open settings search keyboard mode, change to normal.
