### ISSUE TITLE
Add setting to hide system bars (immersive mode) 

### ISSUE THREAD

**Issue by mzivic7** [deadlyjack/Acode#822]
When using Acode in landscape, system bars are covering some part of screen.
So, it would be convenient to have them hidden, by enabling immersive mode.

This should be added as option in app settings.
Additional option: to automatically enter immersive mode when in landscape, and exit it when in portrait.

**Comment by deadlyjack** [comment]
Not planned as immersive mode causes issue with keyboard. I'll try to reimplement in future. Thanks for the suggestion anyway.
