### ISSUE TITLE
Custom Theme Resets After Closing/Restarting App

### ISSUE THREAD

**Issue by atikattar1104** [deadlyjack/Acode#825]
In Latest Fdroid Release, Whenever We Close/Reopen App, Previously Made Custom Theme Resets.

Android 10, MIUI 12.5

**Comment by sebastianjnuwu** [comment]
> Na versão mais recente do Fdroid, sempre que fechamos/reabrimos o aplicativo, redefinimos o tema personalizado anteriormente.
> 
> Android 10, MIUI 12.5

Hello, can you inform the theme you are using when this happens and the version of your app

**Comment by atikattar1104** [comment]
Custom Theme in 1.8.3

**Comment by atikattar1104** [comment]
The One Which Can Be Customized From Settings>Themes Section.

**Comment by deadlyjack** [comment]
I've fixed it. Wait for the update. Thanks for reporting.

**Comment by atikattar1104** [comment]
> > Custom Theme in 1.8.6
> 
> version code?
312
