### ISSUE TITLE
[Feature Request] Custom Theme For Editor.

### ISSUE THREAD

**Issue by atikattar1104** [deadlyjack/Acode#831]
Just Like `Custom` Theme, Which Allows User-Defined Colors, And Is Applicable On Entire App, The Same `Custom` Theme For Editor Section. Which Will Allow User-Defined Colors For Editor.

**Comment by bajrangCoder** [comment]
But that will be not good for normal user because in Editor theme there are a lots of instances like color , font style, etc.... are available.
Btw you can make your own editor theme using plugins (for template checkout [this](https://github.com/legendSabbir/acode-editorTheme-template))
