### ISSUE TITLE
Allow using 'import' in plugins

### ISSUE THREAD

**Issue by 7HR4IZ3** [deadlyjack/Acode#837]
![Screenshot_2023-09-17-15-08-49-609_com foxdebug acodefree](https://github.com/deadlyjack/Acode/assets/90985774/680b576c-ef2f-43b4-ac04-9235f3e3f703)

Line 10;

Add 'type="module"' to the script tag so plugins can import external files that using just one file.
/

**Comment by sebastianjnuwu** [comment]
> ![Screenshot_2023-09-17-15-08-49-609_com foxdebug acodefree](https://user-images.githubusercontent.com/90985774/268507339-680b576c-ef2f-43b4-ac04-9235f3e3f703.jpg)
> 
> Line 10;
> 
> Add 'type="module"' to the script tag so plugins can import external files that using just one file. /

What do you mean by that? Make the plugin in es6?

**Comment by 7HR4IZ3** [comment]
Right now, if the plugin has extra dependencies, you have use bundle it into just one js file using something like browserify, but using modules allows you to use import statement, thereby removing the need for bundling, at least for local files.

**Comment by bajrangCoder** [comment]
> Right now, if the plugin has extra dependencies, you have use bundle it into just one js file using something like browserify, but using modules allows you to use import statement, thereby removing the need for bundling, at least for local files.

Just import that dependency through script tag.

**Comment by 1Code-JS** [comment]
Maybe you can use [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)?
