### ISSUE TITLE
BUG: File loading failed!

### ISSUE THREAD

**Issue by LsxMm** [deadlyjack/Acode#841]
Starting Acode prompts file loading failure! It's not possible to reselect the file either
The Android version is 12
![Screenshot_20230925_183805](https://github.com/deadlyjack/Acode/assets/86006776/2717796b-56f7-4f60-9f64-665d40535b70)
![Screenshot_20230925_183130](https://github.com/deadlyjack/Acode/assets/86006776/73b90259-d4ca-4b17-88b7-e40575c3f2ff)

**Comment by NikhilTomar3000** [comment]
+1

**Comment by sebastianjnuwu** [comment]
Exactly, as you probably had Termux closed, the plugin gave an error when executing this file

**Comment by NikhilTomar3000** [comment]
> Exactly, as you probably had Termux closed, the plugin gave an error when executing this file

I didn't even execute the file. It actually prevents existing files from loading in editor as shown in images above. The opened files are not empty. They have written code but they aren't loaded properly in the editor when I re-open the app. I installed the plugin again just to check and the files again fail to load.

**Comment by deadlyjack** [comment]
Thanks for reporting, I'll check it and fix it.
