### ISSUE TITLE
Error: "iap is not defined"

### ISSUE THREAD

**Issue by kyoyacchi** [deadlyjack/Acode#844]
When i visit some extensions the app shows a popup with this error message
![Screenshot_20230927-134609](https://github.com/deadlyjack/Acode/assets/63583961/969d48a2-e6f9-45ee-bd9e-9f89521d68b3)
(1.8.6 from fdroid)

**Comment by bajrangCoder** [comment]
That's because that's not available in your country

**Comment by kyoyacchi** [comment]
> That's because that's not available in your country

Then, mind of adding an warning instead of showing error message, will ya?

**Comment by kyoyacchi** [comment]
Konuyu kapatıyor birde :D
