### ISSUE TITLE
Autocomplete icons disappeared 

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#845]
I noticed that in the last update of acode, the icons that remained for autocomplete disappeared

![Screenshot_20230927-194633](https://github.com/deadlyjack/Acode/assets/101356556/d9318a62-ee79-4dee-9dd0-f7077d48be0c)

**Comment by bajrangCoder** [comment]
These icons are not added by acode.
It's added by Extra Syntax highlighting plugin.

**Comment by sebastianjnuwu** [comment]
> These icons are not added by acode. It's added by Extra Syntax highlighting plugin.

Ok thanks, natively adding these icons doesn't work?

https://stackoverflow.com/questions/43896499/can-we-use-an-icon-in-ace-editors-autocomplete
