### ISSUE TITLE
Weird jQuery error

### ISSUE THREAD

**Issue by daviddanielng** [deadlyjack/Acode#848]
I have this error that would not go away, yes I am using jQuery library but why the errors on multiple lines.
![Screenshot_20230916-160914](https://github.com/deadlyjack/Acode/assets/107226253/da898378-fe5a-4e29-b838-59bf94519062)

My installed plugins
![Screenshot_20230929-163143](https://github.com/deadlyjack/Acode/assets/107226253/833167a9-fdee-4ab8-89cc-c002d5ff1a28)

**Comment by bajrangCoder** [comment]
Linter is not meant for jQuery
