### ISSUE TITLE
Feature Request - Shortcut to add nested directories at once while creating a folder.

### ISSUE THREAD

**Issue by JuxtNorth** [deadlyjack/Acode#849]
Code editors like VS Code, or even GitHub have a feature that allows the user to create a multi-level nested directory at once and place a file at the end.
 
To demonstrate, here's an example:
In VS code, if a user creates a new folder with the name `foo/bar/baz.ts`, this directory structure is created -
```
foo/
|-- bar/
|  |-- baz.ts
|  
``` 
As you may see, this is a very useful feature which would be great to have in Acode!

P.S: You can also add an emmet like syntax for this that allows creating multiple folders and files at specified levels etc.

**Comment by deadlyjack** [comment]
Great suggestion, I will add it.
