### ISSUE TITLE
Some functions not working after installing a plugin.

### ISSUE THREAD

**Issue by AozoraDev** [deadlyjack/Acode#863]
Yahoo!

Everything in options page and plugin page is not working after installing a plugin. I was installing Markdown Compiler plugin and then things getting messed up.
 
![Screenshot_20231014_205737](https://github.com/deadlyjack/Acode/assets/61007475/4f820d6f-f121-4bd2-bb51-8b34b6b026f4)
![Screenshot_20231014_205830](https://github.com/deadlyjack/Acode/assets/61007475/c52c530b-aa6c-4c3c-840d-ee89bc208e65)
![Screenshot_20231014_205719](https://github.com/deadlyjack/Acode/assets/61007475/0505f83a-991a-429d-a667-86c799b6fe6d)

**Comment by bajrangCoder** [comment]
Still you are facing this ? With latest Acode and plugin version

**Comment by AozoraDev** [comment]
Idk. It's been a year and i don't use Acode anymore.
