### ISSUE TITLE
Acode Preview Port Issue

### ISSUE THREAD

**Issue by fahadkhanrakib** [deadlyjack/Acode#876]
**Description:**
**Issue** **Summary:**
When attempting to use Acode with a React project running on localhost:5173 and setting the preview port to 5173, the code editor automatically previews on 5174.

**Expected Behavior:**
The Acode preview should correctly reflect the specified port (in this case, 5173) to match the local development environment.

**Steps to Reproduce:**

Run a React project on localhost:5173.
Open Acode and set the preview port to 5173.
Observe that the preview automatically uses port 5174.

**Comment by 1Code-0** [comment]
Acode version?

**Comment by fahadkhanrakib** [comment]
> Acode version?

Acode latest version 1.8.7(330)
