### ISSUE TITLE
Font Size Key Binding Does'nt Work with Hackers Keyboard

### ISSUE THREAD

**Issue by feri-irawan** [deadlyjack/Acode#888]
I have used Acode for 4 and a half years with Hackers Keyboard, which is the best keyboard I have ever seen for coding on mobile.

Font Size is a setting that I change often, but with the flow `Settings > Editor Settings > Font Size > Set Font Size`, it makes me slow.

I opened the `key-bindings.json` file, and I saw this:

```json
  "increaseFontSize": {
    "description": "Increase font size",
    "bindKey": "Ctrl-+"
  },
  "decreaseFontSize": {
    "description": "Decrease font size",
    "bindKey": "Ctrl+-"
  },
  "resetFontSize": {
    "description": "Reset font size",
    "bindKey": "Ctrl+0|Ctrl-Numpad0"
  }
```

I tried to press CTRL + + and CTRL + -, but it's not working.

I am using:
Android: 13
Acode: 1.8.7 (pro)
Keyboard: Hackers Keyboard v1.40.7

https://github.com/deadlyjack/Acode/assets/57158078/2a2ca4bd-e8dc-4f48-a551-5767cb34a0d4

**Comment by bajrangCoder** [comment]
It's not working (i guess it's disabled)
Btw you can try `FontZoomer` plugin

**Comment by feri-irawan** [comment]
I have installed `FontZoomer` but it still doesn't work @bajrangCoder 

https://github.com/deadlyjack/Acode/assets/57158078/455e8572-416f-4c4d-8681-d876af065e31

**Comment by bajrangCoder** [comment]
It might be bug but try the same keybindings with acode `ctrl` key

And `FontZoomer` also has option to increase/decrease font using volume button (you will need to set it from FontZoomer Plugin settings

**Comment by feri-irawan** [comment]
Well, I hope this can be fixed.
