### ISSUE TITLE
Error Saving System

### ISSUE THREAD

**Issue by MrElfajar** [deadlyjack/Acode#89]
After I saved my work and run it, it show me the preview but after I go back to my work the text I have wrote got removed/ deleted. So whenever I save, I have to exit the app first.

**Comment by tanveer188** [comment]
[video](https://drive.google.com/file/d/10pbhSnSHxCqZ7Y1BBAGMYIs5W88vXAAT/view?usp=drivesdk) @ @

**Comment by tanveer188** [comment]
please solve the isssue sir

**Comment by deadlyjack** [comment]
Thank you for reporting the issue. I'll fix it soon and update it.
