### ISSUE TITLE
Canais de tv

### ISSUE THREAD

**Issue by tibimawin1** [deadlyjack/Acode#890]
<!DOCTYPE html> <html> <head> <title>Page Title</title> <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> <script src="https://rriptvappcreator.bddeveloper903.repl.co/ajax/libs/jquery/3.4.1/jquery.min.js"></script> <script src="https://rriptvappcreator.bddeveloper903.repl.co/bootstrap/3.4.1/js/bootstrap.min.js"></script> <style> body { background-color:DeepSkyBlue; } .alignleft{ float:left; margin-left:5px; color:white; font-weight:bold; font-size:20px; } .alignright{ float:right; margin-right:10px; color:white; font-size:20px; font-weight:normal ; } h4{ margin-left:5px; color:white; font-weight:bold; font-size:20px; } .nta { position:relative ; overflow:hidden ; } div.scrollmenu { background-color:Deepskyblue; overflow: auto; white-space: nowrap; position:relative ; overflow-y:hidden ; } div.scrollmenu a { display: inline-block; color: white; text-align:center; padding: 4px; text-decoration: none; } div.scrollmenu a:hover { background-color: black; } .cen{ position:relative ; text-align:center; color:white; } .centered{ font-size:14px; font-weight:bold; position:absolute ; top:80%; left: 50%; transform:translate(-50%,-50%) } .cent{ font-size:auto; position:absolute ; top:95%; left: 50%; transform:translate(-50%,-50%) } .nt{ width: 105px; border-radius: 5px; height: 120px ; z-index:1; } .mnt{ width: 100px; border-radius: 2px; height: 100px; } </style> </head> <body> <div id="HeadCarousel" class="carousel slide " data-ride="carousel"> <ol class="carousel-indicators"> <li data-target="#HeadCarousel" data-slide-to="0" class="active"></li> <li data-target="#HeadCarousel" data-slide-to="1"></li> <li data-target="#HeadCarousel" data-slide-to="2"></li> <li data-target="#HeadCarousel" data-slide-to="3"></li> </ol> <div class="carousel-inner"> <div class="item active"> <a class="item" href="go:tsp1"> <img src="https://i.ibb.co/SKQ3Fp2/dataset-cover-1.png"> <div class="carousel-caption cap"> <h3></h3> </div> </a> </div> <div class="item "> <a class="item" href="go:gtv"> <img src="https://i.postimg.cc/j2dY4vJY/IPLBD.png"> <div class="carousel-caption cap"> <h3></h3> </div> </a> </div> <div class="item"> <a class="item" href="go:geo"> <img src="https://i.postimg.cc/1tvjsS4b/BDL.png"> <div class="carousel-caption cap"> <h3></h3> </div> </a> </div> <div class="item"> <a class="item" href="go:PSL"> <img src="https://i.postimg.cc/FF3Q0ddK/psllive.png"> <div class="carousel-caption cap"> <h3></h3> </div> </a> </div> </div> <a class="left carousel-control" href="#HeadCarousel" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span> </a> <a class="right carousel-control" href="#HeadCarousel" data-slide="next"> <span class="glyphicon glyphicon-chevron-right"></span>

 </a> </div> <div class="nta">
     
      <div id="rmpPlayer"></div> <div class="marquee yellow"><span><i class="fa fa-bell" style="font-size:26pt" aria-hidden="true"></i></span> <marquee scrollamount="10" direction="left" onmouseover="stop()" onmouseout="start()">No momento estamos atualizando nosso aplicativo, durante a atualização do aplicativo alguns canais podem ficar fora do ar, você será avisado via notificação. sinceramente sinto muito pelo inconveniente. Muitas felicidades por estar com o app de televisão </marquee> </div> 	 	<h2> 		

     
      <h4>LIVE</h4></div> <div class="scrollmenu"> <a href="go:tsp1"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/208143/logo/240x240/mobile_logo_532199001696331335.png"><h5 class="centered"></h5></div> <a href="go:gtv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/208144/logo/240x240/mobile_logo_382430001696331384.png"><h5 class="centered"></h5></div> <a href="go:gtv2"><div class="cen"> <img class="nt" src="https://i.postimg.cc/s28qbFY4/GTVBangladesh-Logo.png"><h5 class="centered"></h5></div> <a href="go:gtv3"><div class="cen ag"> <img class="nt" src="https://i.postimg.cc/s28qbFY4/GTVBangladesh-Logo.png"> <h5 class="centered"></h5> </div> </a> </div> </div> <div class="nta"> <a href="go:menu"><h4 class="alignleft">Popular TV Channels</h4><h4 class="alignright">See All</h4></a> </div> <div class="scrollmenu"> <a href="go:zeebangla"> <img class="mnt" src="https://images.toffeelive.com/images/program/340/logo/240x240/mobile_logo_094417001655891123.png"> <a href="go:starj"> <img class="mnt" src="https://images.toffeelive.com/images/program/18832/logo/240x240/mobile_logo_166779001683805822.png"> <a href="go:somoytv"> <img class="mnt" src="https://images.toffeelive.com/images/program/65/logo/240x240/mobile_logo_703286001655891016.png"> <a href="go:duronto"> <img class="mnt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVVn9ALbFhHSBQzXN-ptRNAmfWrwOV_dpK_Q&usqp=CAU">
     <a href="go:jolsamovis"> <img class="mnt" src="https://images.toffeelive.com/images/program/18834/logo/240x240/mobile_logo_267398001683804913.png">
     <a href="go:enter10"> <img class="mnt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4T4HfymvBW_yz32bMszMCabQ_EAplYs_0tA&s">
      <a href="go:sst1"> <img class="mnt" src="https://images.toffeelive.com/images/program/603/logo/240x240/mobile_logo_237244001666780563.png">      
      <a href="go:saath"> <img class="mnt" src="https://images.toffeelive.com/images/program/343/logo/240x240/mobile_logo_496322001666780228.png">
       <a href="go:cb"> <img class="mnt" src="https://images.toffeelive.com/images/program/2505/logo/240x240/mobile_logo_200057001655891962.png"> <a href="go:tsvip"> <img class="mnt" src="https://images.toffeelive.com/images/program/19779/logo/240x240/mobile_logo_132014001696928877.png">
 </div> <div class="nta"> <a href="go:Turkishd"><h4 class="alignleft">Sports</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:ten3"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/2418/logo/240x240/mobile_logo_992280001666781086.png"></div> <a href="go:ten1"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/49/logo/240x240/mobile_logo_559887001666781361.png"></div> <a href="go:ten2"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/50/logo/240x240/mobile_logo_832280001666781441.png"></div> <a href="go:ten3"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/51/logo/240x240/mobile_logo_066851001666781605.png"></div> <a href="go:ten5"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/351/logo/240x240/mobile_logo_027801001666782321.png"></div> <a href="go:eshd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4388/logo/240x240/mobile_logo_422191001674119624.png"></div> <a href="go:es"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4387/logo/240x240/mobile_logo_412057001674119486.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4 class="alignleft">Bangladeshi News</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:etor"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/53/logo/240x240/mobile_logo_107276001655890949.png"></div> <a href="go:indi"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/40/logo/240x240/mobile_logo_819689001655890845.png"></div> <a href="go:c24"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/52/logo/240x240/mobile_logo_262737001655890931.png"></div> <a href="go:dbc"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/335/logo/240x240/mobile_logo_946452001655891077.png"></div> <a href="go:atnn"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/42/logo/240x240/mobile_logo_554709001657185722.png"></div> <a href="go:n24"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/233/logo/240x240/mobile_logo_146142001655891039.png"></div> <a href="go:jtv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/46/logo/240x240/mobile_logo_222968001673182917.png"></div> 
 <a href="go:satv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/232/logo/240x240/mobile_logo_731969001673183522.png"></div>
 <a href="go:globaltv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/11841/logo/240x240/mobile_logo_456366001662385216.png"></div></div> </div> </div> <div class="nta"> <a href="go:CS"><h4
 class="alignleft">Bangladeshi Entertainment</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:chi"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/3/logo/240x240/mobile_logo_694865001655890816.png"></div> <a href="go:rtv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/338/logo/240x240/mobile_logo_401499001655891091.png"></div> 
 
 <a href="go:ntv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/41/logo/240x240/mobile_logo_811238001673183089.png"></div>
 
 <a href="go:bvision"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/337/logo/240x240/mobile_logo_519481001656610377.png"></div>
 <a href="go:atnb"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/38/logo/240x240/mobile_logo_483871001656610198.png"></div>
 
 <a href="go:annado"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/692/logo/240x240/mobile_logo_317599001655891632.png"></div>
 
 <a href="go:bsi"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/236/logo/240x240/mobile_logo_341242001655891063.png"></div>
 
 <a href="go:c9"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/9/logo/240x240/mobile_logo_363996001656610763.png"></div>
 
 <a href="go:mohona"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/368/logo/240x240/mobile_logo_784215001656610543.png"></div>
 
 <a href="go:mytv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/339/logo/240x240/mobile_logo_897303001655891103.png"></div>
 
 <a href="go:btvhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/63/logo/240x240/mobile_logo_118855001673182388.png"></div>
 
 <a href="go:bijoy"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/374/logo/240x240/mobile_logo_179345001655891258.png"></div>
 
 <a href="go:asian"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/25/logo/240x240/mobile_logo_913146001673185595.png"></div>
 
 <a href="go:banglatv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/375/logo/240x240/mobile_logo_453885001655891270.png"></div>
 
 <a href="go:deshtv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/39/logo/240x240/mobile_logo_569553001668421527.png"></div>
 <a href="go:nagorik"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/365/logo/240x240/mobile_logo_731536001673438371.png"></div> <a href="go:nexus"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/10908/logo/240x240/mobile_logo_027712001655892101.png"></div> <a href="go:sangsad"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/64/logo/240x240/mobile_logo_760805001655890979.png"></div> <a href="go:btvw"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/1/logo/240x240/mobile_logo_310000001673183767.png"></div> <a href="go:Ekushey"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/334/logo/240x240/mobile_logo_355998001673183662.png"></div> 
 <a href="go:btvch"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/418/logo/240x240/mobile_logo_799556001673182578.png"></div>
 <a href="go:rajdhani"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/177468/logo/240x240/mobile_logo_382457001694586201.png"></div></div> </div> </div> <div class="nta"> <a href="go:CS"><h4
 
 
 
 class="alignleft">indian Entertainment</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:stargold"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18835/logo/240x240/mobile_logo_482266001683805730.png"></div> <a href="go:starplus"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18841/logo/240x240/mobile_logo_664367001683806020.png"></div>
 <a href="go:starbharat"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18836/logo/240x240/mobile_logo_361773001683805911.png"></div>
 <a href="go:smaxhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/641/logo/240x240/mobile_logo_440775001666782769.png"></div>
 <a href="go:smax"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/352/logo/240x240/mobile_logo_612341001666782969.png"></div>
 <a href="go:sethd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/602/logo/240x240/mobile_logo_495351001666780441.png"></div>
 <a href="go:set"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/57/logo/240x240/mobile_logo_149299001666780350.png"></div>
 <a href="go:sabhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2420/logo/240x240/mobile_logo_688156001666785674.png"></div>
 <a href="go:sab"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/342/logo/240x240/mobile_logo_512950001666785776.png"></div>
 <a href="go:smax2"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/353/logo/240x240/mobile_logo_044841001666779831.png"></div>
 <a href="go:swah"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2422/logo/240x240/mobile_logo_037670001666785867.png"></div>
 <a href="go:spal"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2421/logo/240x240/mobile_logo_799518001666784496.png"></div>
 <a href="go:ztvhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/644/logo/240x240/mobile_logo_649814001655891557.png"></div> <a href="go:zanmol"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4567/logo/240x240/mobile_logo_165498001675857326.png"></div> <a href="go:colors"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2425/logo/240x240/mobile_logo_844782001655891780.png"></div> <a href="go:crista"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2436/logo/240x240/mobile_logo_637826001655891948.png"></div> <a href="go:&tvhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/801/logo/240x240/mobile_logo_974516001655891652.png"></div> <a href="go:&pic"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4570/logo/240x240/mobile_logo_000080001675856893.png"></div></div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  class="alignleft">Kids</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:nick"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/2430/logo/240x240/mobile_logo_823707001655891853.png"></div> <a href="go:cartoonn"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/27232/logo/240x240/mobile_logo_320294001679201065.png"></div> <a href="go:yay"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/612/logo/240x240/mobile_logo_091186001666784752.png"></div> <a href="go:dkids"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/611/logo/240x240/mobile_logo_430542001673177743.png"></div> <a href="go:nickjr"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2435/logo/240x240/mobile_logo_910829001655891932.png"></div> <a href="go:pogo"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/27159/logo/240x240/mobile_logo_740957001679201029.png"></div> <a href="go:sonic"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2434/logo/240x240/mobile_logo_464854001655891908.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
 
 class="alignleft">Bangla Movie</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:zbc"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/403/logo/240x240/mobile_logo_368845001655891378.png"></div> <a href="go:jolsamovis"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18834/logo/240x240/mobile_logo_267398001683804913.png"></div> <a href="go:cbc"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/10157/logo/240x240/mobile_logo_151189001655892087.png"></div> <a href="go:mbvip"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/12282/logo/240x240/mobile_logo_671378001663674667.png"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
 
 class="alignleft">Indian Movie</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:zeechd"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/804/logo/240x240/mobile_logo_370803001655891689.png"></div> <a href="go:b4umovie"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/366/logo/240x240/mobile_logo_702115001663003759.png"></div> <a href="go:zee action"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/355/logo/240x240/mobile_logo_569572001655891220.png"></div> <a href="go:zeebwood"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/400/logo/240x240/mobile_logo_624780001655891361.png"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> <a href="go:cp"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWnzl4FbrxLa4StOGKz3Ja6-5hTg-Ft2Bsiw&usqp=CAU"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
 
 class="alignleft">English Movie</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:sonypixhd"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/2419/logo/240x240/mobile_logo_287412001666784602.png"></div> <a href="go:sonypix"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/397/logo/240x240/mobile_logo_049568001666785583.png"></div> <a href="go:iflim"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18098/logo/240x240/mobile_logo_508084001673240324.png"></div> <a href="go:smovie"><div class="cen"> <img class="nt" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/STAR_Movies_logo.svg/2560px-STAR_Movies_logo.svg.png"></div> 
 <a href="go:bfm"><div class="cen"> <img class="nt" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL0DzS3qj9rEb6vmXIkp6NNhgCgmtfb-XU4F776eIY&s"></div>
 <a href="go:lotus"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/389/logo/240x240/mobile_logo_466667001673185088.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  class="alignleft">Islamic</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:quran"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/613/logo/240x240/mobile_logo_192652001655891524.png"></div>  
  <a href="go:sunnah"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/610/logo/240x240/mobile_logo_677105001655891492.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  class="alignleft">International News</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:alljazi"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/234/logo/240x240/mobile_logo_496491001655891051.png"></div> <a href="go:cnnvip"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/333/logo/240x240/mobile_logo_373682001676354236.png"></div> <a href="go:dw"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/363/logo/240x240/mobile_logo_700739001655891233.png"></div>
  <a href="go:zeenews"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/336/logo/240x240/mobile_logo_740569001675858107.png"></div>
  <a href="go:rta"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/662/logo/240x240/mobile_logo_851160001655891584.png"></div>
  <a href="go:euronewsvip"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/655/logo/240x240/mobile_logo_455321001655891572.png"></div>
  <a href="go:ariningtv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/372/logo/240x240/mobile_logo_311458001655891246.png"></div>
  <a href="go:cgtn"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/668/logo/240x240/mobile_logo_867839001655891607.png"></div>
  <a href="go:cnewsasia"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/393/logo/240x240/mobile_logo_435300001673184707.png"></div>
  <a href="go:zeebusnessvip"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4569/logo/240x240/mobile_logo_422385001655892034.png"></div>
  
  <a href="go:kbs"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18099/logo/240x240/mobile_logo_684353001673241863.png"></div>
  <a href="go:tv5"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/407/logo/240x240/mobile_logo_448662001655891393.png"></div>
  <a href="go:aljazziarob"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/658/logo/240x240/mobile_logo_982797001673184503.png"></div>
<a href="go:nhk"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/384/logo/240x240/mobile_logo_258111001655891294.png"></div> <a href="go:frince24"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/1768/logo/240x240/mobile_logo_079930001673184899.png"></div> <a href="go:rt"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/416/logo/240x240/mobile_logo_974196001691566060.png"></div> <a href="go:trtworld"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/131546/logo/240x240/mobile_logo_021540001691566120.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  class="alignleft">Music</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:zoom"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/7838/logo/240x240/mobile_logo_205245001655892068.png"></div> 
  <a href="go:gb"><div class="cen ag"> <img class="nt" src="https://i.postimg.cc/wjYv8PVH/download-1.png"></div>
  
  <a href="go:b4u"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/367/logo/115x115/mobile_logo_886909001563629905.png"></div> <a href="go:mtvm"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2432/logo/240x240/mobile_logo_564387001655891879.png"></div> <a href="go:moviebmusic"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/18831/logo/240x240/mobile_logo_146321001673415827.png"></div> <a href="go:mtvindia"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2431/logo/240x240/mobile_logo_398176001655891867.png"></div> <a href="go:zing"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/391/logo/240x240/mobile_logo_430259001655891309.png"></div> <a href="go:vh1hd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2433/logo/240x240/mobile_logo_609993001655891894.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  
  class="alignleft">Infotainment</h4><h4 class="alignright">See All</h4></a></div> <div class="scrollmenu"> <a href="go:animalphd"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18096/logo/240x240/mobile_logo_032001001673194753.png"></div>
  <a href="go:ngcvip"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18840/logo/240x240/mobile_logo_024343001683805110.png"></div>
  <a href="go:animalp"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/359/logo/240x240/mobile_logo_835681001673175607.png"></div>
  <a href="go:discoveryhd"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18093/logo/240x240/mobile_logo_868363001673181438.png"></div>
  <a href="go:ngcwildvip"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18837/logo/240x240/mobile_logo_951347001683805257.png"></div>
  <a href="go:discovery"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18097/logo/240x240/mobile_logo_297723001673195119.png"></div>
  
  <a href="go:discovarysin"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/378/logo/240x240/mobile_logo_604754001673177502.png"></div>
  <a href="go:foxlifevip"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18833/logo/240x240/mobile_logo_204706001683804802.png"></div>
  
  <a href="go:disasia"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/12083/logo/240x240/mobile_logo_141710001663004743.png"></div>
  
  <a href="go:disturbo"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/379/logo/240x240/mobile_logo_775127001673177876.png"></div>
  
  <a href="go:InvDHD"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18094/logo/240x240/mobile_logo_154805001673178308.png"></div>
  
  <a href="go:idiscovary"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/18095/logo/240x240/mobile_logo_452964001673178334.png"></div>
   <a href="go:tlchd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/608/logo/240x240/mobile_logo_648826001673178929.png"></div> <a href="go:tlc"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/358/logo/240x240/mobile_logo_048875001673178985.png"></div> <a href="go:historytv"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2429/logo/240x240/mobile_logo_009938001674474908.png"></div> <a href="go:bbcerathhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/670/logo/240x240/mobile_logo_363688001655891620.png"></div> <a href="go:bbcerath"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/396/logo/240x240/mobile_logo_708825001655891324.png"></div> <a href="go:teach"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/4786/logo/240x240/mobile_logo_570626001655892054.png"></div> </div> </div> </div> <div class="nta"> <a href="go:CS"><h4
  
  
   class="alignleft">English Entertainment</h4></a></div> <div class="scrollmenu"> <a href="go:zeecaf"><div class="cen ag"> <img class="nt" src="https://images.toffeelive.com/images/program/401/logo/240x240/mobile_logo_394610001675857887.png"></div> 
  
  <a href="go:Infinityhd"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2428/logo/240x240/mobile_logo_455256001655891827.png"></div> 
  <a href="go:Comedy Central HD"><div class="cen"> <img class="nt" src="https://images.toffeelive.com/images/program/2427/logo/240x240/mobile_logo_461931001655891802.png"></div> </div>
  
  </body> </html>

**Comment by 1Code-0** [comment]
https://github.com/deadlyjack/Acode/blob/main/CODE_OF_CONDUCT.md?
