### ISSUE TITLE
Characters writing twice on typing 

### ISSUE THREAD

**Issue by PatAbah** [deadlyjack/Acode#895]
Perhaps I might have entered a key sequence mistakenly, I'm not sure. But currently, when I type any word or letter in the editor, "if" for example, it changes to "ifif". It happens for everything irrespective if whether I type it out or select from autocomplete. It's really bugging me.

I know I can reinstall the app or something, but I'm looking for a permanent solution that doesn't involve me clearing the app data or reinstalling.

Is this a feature or an issue? If it is a feature, how did I activate it, and how can I deactivate it?

**Comment by bajrangCoder** [comment]
Try by changing `Acode>Settings>App Settings>Keyboard Mode` to either `2nd` or `3rd` option.

It's not any feature, it mainly happens due to mobile keyboard autocompletion related things

**Comment by PatAbah** [comment]
Thanks for the reply @bajrangCoder, but I never got the chance to try out your solution. The keyboard settings was on Normal (I think) when I noticed the behavior, and still on Normal currently. The behaviour just stopped on its own, same way it started on its own.
