### ISSUE TITLE
Product not available/ iap not defined

### ISSUE THREAD

**Issue by mokshraj** [deadlyjack/Acode#904]
Plugin shows up in list but isn't available to install and shows a error.
![Screenshot_20231224_191512](https://github.com/deadlyjack/Acode/assets/81727401/5bf7b0e6-30ee-4cf7-b20f-28626c5571c4)

**Comment by bajrangCoder** [comment]
Have you purchased this plugin?

**Comment by 1Code-0** [comment]
Have you installed acode from Google Play, F-Droid, or Telegram? If so, then what version and version code?

**Comment by mokshraj** [comment]
> Have you purchased this plugin?

No .

**Comment by mokshraj** [comment]
> Have you installed acode from Google Play, F-Droid, or Telegram? If so, then what version and version code?

F droid

**Comment by bajrangCoder** [comment]
> > Have you purchased this plugin?
> 
> No . This is just a example. There is other plugins like moonlight theme. I don't think it is paid

I thought this is not available in your country because these are paid plugins

**Comment by mokshraj** [comment]
> > > Have you purchased this plugin?
> > 
> > 
> > No . This is just a example. There is other plugins like moonlight theme. I don't think it is paid
> 
> I thought this is not available in your country because these are paid plugins

Even the moonlight one .

**Comment by bajrangCoder** [comment]
Yes Moonlight is also paid , you can check [here](https://acode.app/plugins)

**Comment by mokshraj** [comment]
> Yes Moonlight is also paid , you can check [here](https://acode.app/plugins)

Well,no need to keep the issue then.
Thanks for helping.

**Comment by mokshraj** [comment]
Thanks for helping. Just one thing, if you can make it so that it says it's paid instead of giving an error.

**Comment by bajrangCoder** [comment]
> Thanks for helping. Just one thing, if you can make it so that it says it's paid instead of giving an error.

Hmm,
As Acode uses Google SDK for payment and in some country it gives error (or not available)
