### ISSUE TITLE
.css not linking to html file 

### ISSUE THREAD

**Issue by EliteGamer064** [deadlyjack/Acode#909]
![Screenshot_20240102-193738_Acode](https://github.com/deadlyjack/Acode/assets/155469037/3631da0c-ece6-4148-8aff-e5722f9764ae)
When I style in .html and run it code it works but when style in .css it does not work and my style disappears. How can rectify this issue ? 
I recently updated to Acode 1.9.0 from 1 8.3 
![Screenshot_20240102-193314_Acode](https://github.com/deadlyjack/Acode/assets/155469037/c4bd540e-33cd-4ac2-9469-616cdffe6f1f)
![Screenshot_20240102-193327_Acode](https://github.com/deadlyjack/Acode/assets/155469037/bd2ec1e7-c75a-4171-89c8-cfe9e332bb23)
![Screenshot_20240102-193521_Acode](https://github.com/deadlyjack/Acode/assets/155469037/d94998ce-acc3-4730-a577-f80ceaeb52da)
![Screenshot_20240102-193550_Acode](https://github.com/deadlyjack/Acode/assets/155469037/5ba3937a-fbba-4eb1-9a40-3d65cbfebb22)

**Comment by sebastianjnuwu** [comment]
Clear the acode cache, I'm also facing the same problem and generally clearing the apricativo cache solves it

**Comment by Mayonnaisu** [comment]
@EliteGamer064 Hi, how did you solve the problem? I'm facing the same one now.

**Comment by EliteGamer064** [comment]
Wrong syntax on the html side.

**Comment by Mayonnaisu** [comment]
@EliteGamer064 I see. Thanks!
