### ISSUE TITLE
[BUG] The closed folder is not match with selected one

### ISSUE THREAD

**Issue by butthx** [deadlyjack/Acode#917]
Hi, in several versions back I found a bug which I thought was quite annoying.  When I want to close a folder, the folder closed by Acode is not appropriate.  

Example :
I have folder : 

```
- Folder A 
- Folder B 
- Folder C
```

When I want to close the folder C i hold or tap the three dots and select close folder. What should have been closed was folder C, but I didn't find that what was closed was folder A. When I tried again the closed folder was folder B. 

So the closed folder is not the folder I chose but the folder at index 0.

```
[INFO] 
DEVICE : Redmi Note 11 NFC
OS : MIUI 14.0.5 ID / Android 13 (T)
ACODE : 1.8.7 (330) Telegram Build
```

<video src="https://github.com/deadlyjack/Acode/assets/68604099/577eb99a-ab37-43b6-a37e-3ea95626d296" />

**Comment by deadlyjack** [comment]
Thanks for reporting this issue. I'm adding it to my todo list.

**Comment by deadlyjack** [comment]
Fixed, wait for the update.
