### ISSUE TITLE
Missing margin at the more menu, and file sorting inconsistency

### ISSUE THREAD

**Issue by ilias-7565** [deadlyjack/Acode#925]
It seems that at the location 1, there is no such margin that present at the location 2. That makes the more button harder to press.
![20240209_174610](https://github.com/deadlyjack/Acode/assets/66683424/95860ad2-0855-4e1d-b6de-292b0ce7b118)

p.s. i also noticed the weird file sorting issue.

**Comment by bajrangCoder** [comment]
Acode doesn't sort things

**Comment by bajrangCoder** [comment]
> p.s. i also noticed the weird file sorting issue.

Acode uses "sort by name" (lexicographical) sorting for these files which doesn't take numerical value in account
