### ISSUE TITLE
How to edit active header color?

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [deadlyjack/Acode#938]
![image_2024_03_04_17_16_31-01](https://github.com/deadlyjack/Acode/assets/72925898/657ae527-e8e7-4569-baf0-84092c14dfe8)

How to edit color of this yellow bar in custom theme? "active text color" seems not working. 

I'm using 1.9.0 (935) on Android 14.

**Comment by bajrangCoder** [comment]
Currently you can only do it through plugin
