### ISSUE TITLE
V1.10.0 - Some bugs 

### ISSUE THREAD

**Issue by sebastianjnuwu** [deadlyjack/Acode#945]
Hello, in this new version I found some bugs starting with the startup screen, it starts with one and changes to another like we print 

• The .md previously viewed are no longer being viewed

• In previous versions, "eruda" would work even when running on Chrome in this version.

• When you run HTML to view and edit etc. the resolution doesn't seem standard with the previous Chrome I think it was

**Comment by 1Code-0** [comment]
Version code?

**Comment by sebastianjnuwu** [comment]
> Código da versão?

V1.10.0

**Comment by sebastianjnuwu** [comment]
> > Código da versão?
> 
> v1.10.0 (944) - As I said the last version. I recently published a plugin and the readme was completely buggy, it has several bugs
