### ISSUE TITLE
Cannot open after 1.10.0 update from F-Droid

### ISSUE THREAD

**Issue by tondorw** [deadlyjack/Acode#953]
The loading animation takes forever and doesn't seem to complete. Have to downgrade to 1.9.0 to make it work.
Device is Samsung Tab S9

**Comment by s1nistr4** [comment]
Happening here too

**Comment by traviszech** [comment]
Add me to the list as well. Samsung S21 ultra newest firmware.

**Comment by Solayof** [comment]
> The loading animation takes forever and doesn't seem to complete. Have to downgrade to 1.9.0 to make it work.
> Device is Samsung Tab S9

Where can I get the downgrade version, I tried I don't find any. Can you help me out?

**Comment by text-dev** [comment]
Versions 1.8.6 and 1.8.8 had also the same issue.

**Comment by gsw945** [comment]
me to

**Comment by marzooqasp** [comment]
Samsung galaxy A71.
Same here.
The opening animation kept playing. And doesn't open.

**Comment by unixatch** [comment]
Same issue here, stuck on the loading animation, **_again_** for the 2nd time recently.

OS: `Android 12`
Phone UI: `Realme UI 3.0`
Phone: `Realme 7 5G, 6+2 GB of RAM`
Phone model: `RMX2111`
Version: `1.10.0`
From: `F-Droid`

**Comment by 1Code-0** [comment]
https://github.com/deadlyjack/Acode/issues/953?notification_referrer_id=NT_kwDOBsfwKrQ5OTg5ODQ3Nzg5OjExMzc2NjQ0Mg#issuecomment-2018565608?

**Comment by macearl** [comment]
> Can you guys running 1.10.0/1 share the 3-digit version code?

I'm experiencing the same issue. I'm currently on 1.10.0 (944) from the f-droid repository, where it was added on 24.03.2024

If there's anything else that's needed let me know

**Comment by nothingnesses** [comment]
> Can you guys running 1.10.0/1 share the 3-digit version code?

@1Code-0 How do you get that?

**Comment by Forza-tng** [comment]
> updated from fdroid to 1.10 build 945 and it's working now. is this the commit that fixed it? [26ed2fb](https://github.com/deadlyjack/Acode/commit/26ed2fbbfef507bf34a81e570dd938e6e9d7be29)

I can confirm on my S22 that build 945 now works.

**Comment by CmpJR** [comment]
> updated from fdroid to 1.10 build 945 and it's working now. is this the commit that fixed it? [26ed2fb](https://github.com/deadlyjack/Acode/commit/26ed2fbbfef507bf34a81e570dd938e6e9d7be29)

945 build from fdroid is also keep crashing. I tried playstore version too. Same problem there.
For me, after loading animation, it crush. I cleared all data (That means no plugins), but nothing happend
