### ISSUE TITLE
Error to open file

### ISSUE THREAD

**Issue by Z3ROCH13F** [deadlyjack/Acode#957]
I can't open file/folder and i got error message.

![Screenshot_2024-04-06-02-25-26-82_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/deadlyjack/Acode/assets/116209415/6be2028a-70fc-4d13-8f0c-93fae0b437ca)

Help me!
Thanks.

**Comment by Z3ROCH13F** [comment]
![Screenshot_2024-04-07-05-04-13-18_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/deadlyjack/Acode/assets/116209415/fe310512-fd95-481d-9482-1f04513f46fc)

![Screenshot_2024-04-07-05-04-18-69_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/deadlyjack/Acode/assets/116209415/aa2462a0-ecc7-4828-b213-df05783ce58d)

![Screenshot_2024-04-07-05-04-36-45_e3c1f266f17b29c7b40472751f031275.jpg](https://github.com/deadlyjack/Acode/assets/116209415/c6df3e2c-6f66-4995-a93b-e54fe01c5b7a)

**Comment by 1Code-0** [comment]
Which acode version (also include version code) are you using and where did you install it? Also, which device, manufacturer, and android version?
