### ISSUE TITLE
Syntax highlighting doesn't work in HTML

### ISSUE THREAD

**Issue by raintorres** [deadlyjack/Acode#962]
I'm just curious why it looks like the color for syntax highlighting doesn't work in HTML.
![b8dafa4e-50e6-4b23-83bd-8f110f1ef30a](https://github.com/deadlyjack/Acode/assets/136299953/872615c2-1e15-43f3-9a50-7c5c507f1f03)

and, the color only shows when a bracket is missing.
![3dd9ba97-3589-4b0b-9342-8b6b9020b301](https://github.com/deadlyjack/Acode/assets/136299953/7d32ebbd-be66-460f-9708-430cb03c7506)

In other languages, it works just perfectly fine.
![15ee09a9-d646-4e5d-b095-9b006a6e6b6f](https://github.com/deadlyjack/Acode/assets/136299953/047fac1e-b021-4d1f-afbf-637903362ae4)

I have another code editor which is " SPCK EDITOR", the syntax highlighting works just fine.
![11896bc0-14a1-403d-aa20-3891d216323b](https://github.com/deadlyjack/Acode/assets/136299953/bd1ca8c3-7b22-45f6-9b4b-5e5ffd4092e3)

Thank youu!! :)

**Comment by raintorres** [comment]
**Update: It works now!**

![92556f5d-e8b2-4e84-9b19-d7e5f84e959c](https://github.com/deadlyjack/Acode/assets/136299953/436bdb2f-d723-4519-8a44-4e9b62da1c3d)


It just doesn't show the colors because the default theme  for the "Editor" was "Dracula", so that's why it messed up with the colors of syntax highlight.

![271bf7ee-ec52-484e-9b57-c9a3e07ee443](https://github.com/deadlyjack/Acode/assets/136299953/f8020c2a-798e-4792-bce1-1bcffedd638a)
![2daf8150-6a05-4b32-9897-f05a03813c3a](https://github.com/deadlyjack/Acode/assets/136299953/0fe8920b-4701-4bbd-bc28-66a2112a3ac9)


Thank youu!! :)

**Comment by 1Code-0** [comment]
![Screenshot_20240421-165245_Chrome](https://github.com/deadlyjack/Acode/assets/113766442/05c28c35-6545-476f-b83d-db1e1790ae01)
?

**Comment by ByteJoseph** [comment]
Please Close the issue
