### ISSUE TITLE
white color

### ISSUE THREAD

**Issue by Ramadan-Botsher** [deadlyjack/Acode#963]
the default color for the website or any background is black , and if i try to chnge it to white does not work or any level of white
![Screenshot_٢٠٢٤-٠٥-٠٣-٢١-٢٣-١١-٨١١_com.foxdebug.acodefree-edit.jpg](https://github.com/deadlyjack/Acode/assets/107793891/7a69c149-5018-4a35-82aa-98fd019f5501)

**Comment by ByteJoseph** [comment]
This issue is because your system theme is in dark mode 🌒. 
Apply light mode theme for now.🔆
