### ISSUE TITLE
BUG when deleting file in a emoji-named dir

### ISSUE THREAD

**Issue by hmmuaa** [deadlyjack/Acode#964]
to reproduce:
1. in file explorer (in left-panel) create a new folder
2. name it “test😈” (an emoji char at the end)
3. create a file in *test😈*, name it “records.mjs”
4. open the file in editor
5. create another folder inside *test😈*, name it “records”
6. then delete *records* folder (in built-in file explorer)
7. the file *records.mjs* in editor now **error** marked “Deleted”
(the file is still exists)

version using: 1.10.0 945

**Comment by ByteJoseph** [comment]
You should try the latest version. 
I tried to reproduce this in version 1.10.2 .
Zero errors.
Or can you upload video
