### ISSUE TITLE
Incorrect syntax highlighting and formatting

### ISSUE THREAD

**Issue by sls1005** [deadlyjack/Acode#965]
# Kotlin

![Screenshot_20240512_115913_Acode](https://github.com/deadlyjack/Acode/assets/90055573/dd35b783-89f0-4a6e-baf1-2583317f43a4)

# Go

### Original

![Screenshot_20240513_122706_Acode](https://github.com/deadlyjack/Acode/assets/90055573/d4c63f0c-ac25-488d-97d0-6171e46d603e)

### Formatted

![Screenshot_20240513_122718_Acode](https://github.com/deadlyjack/Acode/assets/90055573/9c995427-f866-4d65-8962-aff8275c29e2)

`:=` is the declaration operator. No space is allowed in between, or it becomes a syntax error.

**Acode**: 1.10.1
**OS**: Android 14
**Device**: Samsung SM-M336B

**Comment by bajrangCoder** [comment]
Which code formatter are you utilizing for formatting your Go code?
