### ISSUE TITLE
Purchase not actived

### ISSUE THREAD

**Issue by toddy007** [deadlyjack/Acode#974]
![Screenshot_20240531-230514](https://github.com/deadlyjack/Acode/assets/111665673/d1199879-b24d-4adf-9127-0df97e525dbe)
I buyed "ts support" puglin and when i try to download It he says '{ error: "purchase not actived" }', someone can help?

**Comment by 1Code-0** [comment]
Where did you install the app, and what version and version code?

**Comment by toddy007** [comment]
I installed from Play Store, version 1.10.3. What would it be "version
code"?

Em sáb., 1 de jun. de 2024 04:25, 1Code ***@***.***> escreveu:

**Comment by 1Code-0** [comment]
> ...What would it be "version code"?... 

![Screenshot_20240602-051911_Zipper](https://github.com/deadlyjack/Acode/assets/113766442/01585324-1a36-4abd-8428-ae08f2d56f1e)

**Comment by toddy007** [comment]
The error was solved, thanks!

Em dom., 2 de jun. de 2024 00:21, 1Code ***@***.***> escreveu:

**Comment by ByteJoseph** [comment]
Close the issue

**Comment by toddy007** [comment]
Closed
