### ISSUE TITLE
Formatting error in markdown and .yml files

### ISSUE THREAD

**Issue by ronynn** [deadlyjack/Acode#975]
While writing on a markdown file, with word wrapping turned off, as the line becomes too long compared to the screen width, it gets pushed to the next line.

Perhaps prettier plugin does this to ensure code doesn't gets too wide. But I removed prettier as the formatter for markdown, restarted the app and this still continues.

I then made a .prettierignore file with *.md in it and then setting prettier as the formatter and restarting the app but that didn't stop this error.

It gets too problematic as comments get pushed to next line making errors in code. 

App version 1.10.2, but it was also occuring in 0.10.1.

Thank You.

**Comment by ByteJoseph** [comment]
Screenshots

**Comment by ronynn** [comment]
As I was trying to replicate the problem for taking screenshots, I checked the settings.json file to see that I had turned the hardWrap setting to true at some point earlier. 

Hard wrap adds line breaks at the print margin, which was causing this problem.

This problem is resolved, thank you.
