### ISSUE TITLE
Feature Request: Display Document Outline/Structure

### ISSUE THREAD

**Issue by maninthemiddle01** [deadlyjack/Acode#979]
I couldn't find a similar functionality in the settings or documentation, did I perhaps miss it? If not, it would be helpful if Acode included a feature to display the document outline or structure.

**Possible Implementation:**

* A side panel that displays the document structure based on headings, functions, classes, etc.
* Clicking on an element in the outline should jump the user directly to the corresponding location in the document.
* Optional: Ability to filter the outline (e.g., show only functions) or sort the elements.

**Benefits:**

* Faster and easier navigation in large files.
* Better overview of the file contents.
* Increased productivity when working with structured documents.

**Comment by bajrangCoder** [comment]
It's supported through plugin, check Acode Language client plug-in
