### ISSUE TITLE
How to run python code?

### ISSUE THREAD

**Issue by hanwuli** [deadlyjack/Acode#980]
I have installed some necessary plugins, including AcodeX-Terminal, Code Runner, Python 2.0. But it can't run any python files when I click the run button in the upper right corner, just prompt "start the acodex server in termux first! "  I later find acode termial can open from the side. Then still can't execute codes. 
Do I not know how to use it please? 
![Screenshot_2024-06-12-18-20-21-453-edit_com foxdebug acodefree](https://github.com/deadlyjack/Acode/assets/51591423/57f526c1-a6af-4f75-a76e-bb0b99dd0af6)

**Comment by ByteJoseph** [comment]
Download termux from Fdroid

**Comment by hanwuli** [comment]
> Download termux from Fdroid

Thank you. I read the official documents later and  it have  been solved yet.

**Comment by hanwuli** [comment]
> Download termux from Fdroid

Thank you. I read the official documents later and it has been solved yet.
