### ISSUE TITLE
How to disable the auto-complete tag feature?

### ISSUE THREAD

**Issue by michele-bs** [deadlyjack/Acode#983]
Hi, I can't disable the auto-complete tag feature. If I write <p>, Acode automatically write </p>.
Chatbot on [acode.app](https://acode.app) suggested me to uninstall the Auto Rename Tag plugin, but this plugin is not installed, actually.

Can you help me?

**Comment by bajrangCoder** [comment]
Share a recording

**Comment by bajrangCoder** [comment]
Or try by adjusting keyboard modes
