### ISSUE TITLE
Za

### ISSUE THREAD

**Issue by Zihadahmmed999** [deadlyjack/Acode#988]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>স্মার্ট পরিচয় পত্র</title>
<style>
  body {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 300vh;
    margin: 0;
  }
  .card {
    width: 900px;
    padding: 12px;
    background-color: #fff;
    box-shadow: 0 5px 10px rgba(0,0,0,0.1);
    border-radius: 8px;
    overflow: hidden;
    animation: slideIn 0.5s ease-in-out;
  }
  .card:hover {
    box-shadow: 0 10px 20px rgba(0,0,0,0.2);
  }
  .profile-img {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    margin: 0 auto 10px;
    display: block;
  }
  .card h2 {
    text-align: center;
    margin: 0;
  }
  .card p {
    text-align: center;
    color: #666;
  }
  @keyframes slideIn {
    from {
      transform: translateY(-20px);
      opacity: 0;
    }
    to {
      transform: translateY(0);
      opacity: 1;
    }
  }
</style>
</head>
<body>

<div class="card">
  <img src="profile.jpg" alt="প্রোফাইল ছবি" class="profile-img">
  <h2>মোঃ জিহাদ আহম্মেদ রমজান </h2>
  <p>সহকারী প্রকৌশলী </p>
  <p>পাওয়ার গ্রীড কোম্পানি  অব বাংলাদেশ </p>

**Comment by 1Code-JS** [comment]
?
