### ISSUE TITLE
Error With Module 

### ISSUE THREAD

**Issue by iamawanishmaurya** [deadlyjack/Acode#996]
I have install and connected my acode terminal to termux acodex but when even after  installing  the module in terminal it
Give me same error as module not found.![Screenshot_20240725-233317.png](https://github.com/user-attachments/assets/99f4cf7e-1219-422c-a45c-a840d8940ae6)

![Screenshot_20240725-233311.png](https://github.com/user-attachments/assets/00346e4c-be27-436e-b36e-d15de78c7402)

![Screenshot_20240725-233236.png](https://github.com/user-attachments/assets/d6674650-ca0a-4845-99df-d015b9b5a89c)

**Comment by 1Code-JS** [comment]
Try running `python <path>` (replace <path> with the file path where `Main.py` is) in the terminal perhaps?
